import {
  sortObjectAlphabetically,
  filterDeepNestedObjectByKeys,
  filterDeepNestedObjectByFields,
  addTranslationKey,
  getPresetFields,
  nanaPresetFields,
  adbPresetFields,
  ectPresetFields,
  redactSensitiveData,
} from './LeadHistoricalData.helper';

jest.mock('presentation/theme/localization', () => ({
  getString: jest.fn((key: string) => key),
  checkKeyExist: jest.fn().mockReturnValue(true),
}));

const unsortedObject = {
  c: 'world',
  a: {
    b: 'world',
    a: 'hello',
  },
  b: 'hello',
  d: null,
  e: {
    a: '',
    b: null,
  },
  f: [
    {
      g: null,
      h: 'hello',
      i: 'world',
      j: '',
    },
  ],
};

const rawData = {
  calls: [],
  contact: {
    assigned_to: {
      address_city: null,
      address_country: null,
      address_postalcode: null,
      address_state: null,
      address_street: null,
      authenticate_id: null,
      created_by: '1',
      date_entered: '2020-05-21T08:46:02+00:00',
      date_modified: '2020-07-20T04:35:45+00:00',
      deleted: false,
      department: 'marketing',
      description: null,
      employee_status: 'Terminated',
      external_auth_only: false,
      factor_auth: false,
      factor_auth_interface: null,
      first_name: null,
      id: '67c94893-c710-c093-9069-5ec63fa94546',
      is_admin: false,
      is_group: false,
      last_name: 'Parinda Jaisamut',
      messenger_id: null,
      messenger_type: null,
      modified_user_id: '1',
      phone_fax: null,
      phone_home: null,
      phone_mobile: null,
      phone_other: null,
      phone_work: '5598',
      photo: null,
      portal_only: false,
      pwd_last_changed: '2020-05-21T08:46:00+00:00',
      receive_notifications: true,
      reports_to_id: 'af75783b-c482-1523-a03d-58a25f4fbe76',
      show_on_employees: true,
      status: 'Inactive',
      sugar_login: true,
      system_generated_password: true,
      title: null,
      user_hash: '$1$bRFSKPT2$nlnZBBy5yeL52FhhgBu801',
      user_name: 'parinda',
    },
    data: {
      active_reason_c: '',
      age_c: 0,
      alt_address_building_c: '',
      alt_address_city: null,
      alt_address_company_c: '',
      alt_address_country: null,
      alt_address_floor_c: '',
      alt_address_moo_c: '',
      alt_address_more_c: '',
      alt_address_name_c: '',
      alt_address_postalcode: null,
      alt_address_road_c: '',
      alt_address_room_c: '',
      alt_address_soi_c: '',
      alt_address_state: null,
      alt_address_street: null,
      alt_address_village_c: '',
      assigned_user_id: '67c94893-c710-c093-9069-5ec63fa94546',
      assistant: null,
      assistant_phone: null,
      birthdate: null,
      call_subscribe_c: null,
      callback_datetime_c: null,
      campaign_id: '',
      clean_email_c: false,
      contact_id_c: '',
      contact_name_c: '',
      corporation_c: false,
      created_by: '3c0d03dd-0249-05fb-7357-58c64900cec5',
      credit_balance_c: null,
      date_entered: '2020-04-29T09:44:55+00:00',
      date_modified: '2020-05-23T08:01:55+00:00',
      date_reviewed: null,
      deleted: false,
      department: null,
      description: null,
      do_not_call: false,
      duplicate_email_c: false,
      ecamp_easycampaigns_id_c: '8aa4c26d-92aa-6d87-4a64-5e68b05dc328',
      email_subscribe_c: null,
      first_name: 'ดี้',
      gender_c: '',
      genesys_c: null,
      gg_customer_id_c: '2079470879.1588153406',
      global_unsubscribe_c: null,
      id: '10077ead-b4ed-27ef-945a-5ea94c93e38f',
      id_c: '10077ead-b4ed-27ef-945a-5ea94c93e38f',
      id_number_c: '',
      immortal_c: false,
      inactive_reason_c: '',
      is_foreigner_c: null,
      jjwg_maps_address_c: '',
      jjwg_maps_geocode_status_c: '',
      jjwg_maps_lat_c: 0,
      jjwg_maps_lng_c: 0,
      joomla_account_id: null,
      last_name: null,
      lawful_basis: '^^',
      lawful_basis_source: null,
      lead_source: 'portal',
      line_id_c: '',
      line_uid_c: null,
      marital_status_c: '',
      modified_user_id: '6622fe92-d88a-6573-d1e0-5c78b2b309d5',
      pdpa_agreed_c: null,
      pdpa_agreed_date_time_c: null,
      pdpa_disagreed_c: null,
      pdpa_unsubscribe_c: null,
      phone_fax: null,
      phone_home: null,
      phone_mobile: '0819996603',
      phone_other: null,
      phone_work: null,
      photo: null,
      policy_end_date_c: null,
      policy_flag_c: false,
      portal_account_disabled: false,
      portal_user_type: 'Single',
      pre_active_reason_c: 'no_answer',
      preactive_count_c: null,
      preferred_callback_time_c: '',
      primary_address_building_c: '',
      primary_address_city: null,
      primary_address_company_c: '',
      primary_address_country: null,
      primary_address_floor_c: '',
      primary_address_moo_c: '',
      primary_address_more_c: '',
      primary_address_postalcode: null,
      primary_address_road_c: '',
      primary_address_room_c: '',
      primary_address_soi_c: '',
      primary_address_state: null,
      primary_address_street: null,
      primary_address_village_c: '',
      proposal_flag_c: false,
      ref_id_c: '',
      reports_to_id: '',
      salutation: null,
      sms_subscribe_c: null,
      status_c: 'Pre_active',
      title: null,
    },
  },
  documents: [],
  email_addresses: [
    {
      confirm_opt_in: 'confirmed-opt-in',
      confirm_opt_in_date: null,
      confirm_opt_in_fail_date: null,
      confirm_opt_in_sent_date: null,
      confirm_opt_in_token: null,
      date_created: '2020-04-29T09:44:00+00:00',
      date_modified: '2020-05-25T07:42:10+00:00',
      deleted: false,
      email_address: 'Asae.handee@gmAil.com',
      email_address_caps: 'ASAE.HANDEE@GMAIL.COM',
      id: '61c5acf5-df7b-ec8f-0133-5ea94c047487',
      invalid_email: false,
      opt_out: false,
    },
  ],
  quotes: [
    {
      assigned_to: {
        address_city: null,
        address_country: null,
        address_postalcode: null,
        address_state: null,
        address_street: null,
        authenticate_id: null,
        created_by: '5ee4a147-abfa-e3dc-5a3e-598c2b329653',
        date_entered: '2018-09-03T08:27:51+00:00',
        date_modified: '2023-04-18T07:59:16+00:00',
        deleted: false,
        department: 'marketing',
        description: null,
        employee_status: 'Active',
        external_auth_only: false,
        factor_auth: false,
        factor_auth_interface: null,
        first_name: null,
        id: 'a84fd769-c52e-65c3-dc09-5b8cf04cfc12',
        is_admin: false,
        is_group: false,
        last_name: 'Suwat Meeboon',
        messenger_id: null,
        messenger_type: null,
        modified_user_id: '5639157a-3f78-681f-51b9-6007b3dc1189',
        phone_fax: null,
        phone_home: null,
        phone_mobile: null,
        phone_other: null,
        phone_work: '5533',
        photo: null,
        portal_only: false,
        pwd_last_changed: '2018-10-03T22:36:00+00:00',
        receive_notifications: false,
        reports_to_id: 'af75783b-c482-1523-a03d-58a25f4fbe76',
        show_on_employees: true,
        status: 'Inactive',
        sugar_login: true,
        system_generated_password: false,
        title: '6304001385',
        user_hash: '$1$jK5.584.$uEsjvy8/ub1alaULVcbW4/',
        user_name: 'suwat',
      },
      quote: {
        actual_amount_c: null,
        actual_gross_premium_c: null,
        actual_net_premium_c: null,
        additional_bailbond_c: null,
        additional_medical_expenses_c: null,
        additional_personal_accident_c: null,
        addtional_medical_expenses_c: null,
        alt1_adt_bailbond_c: null,
        alt1_adt_medical_expenses_c: null,
        alt1_adt_personal_accident_c: null,
        alt1_benefit_1_c: '',
        alt1_benefit_2_c: '',
        alt1_car_code_c: null,
        alt1_car_usage_c: null,
        alt1_cmi_price_c: null,
        alt1_condition_1_c: '',
        alt1_condition_2_c: '',
        alt1_condition_3_c: '',
        alt1_discount_broker_c: null,
        alt1_gross_premium_c: null,
        alt1_insurance_class_c: '',
        alt1_insurance_country_c: '',
        alt1_insurer_name_c: '',
        alt1_manual_quote_c: false,
        alt1_max_suminsured_c: null,
        alt1_owndmg_deductible_c: null,
        alt1_owndmg_firetheft_c: null,
        alt1_owndmg_flood_c: null,
        alt1_person_covered_no_c: null,
        alt1_plan_expire_c: null,
        alt1_plan_name_c: '',
        alt1_plan_name_detail_c: '',
        alt1_price_aft_disc_c: null,
        alt1_promotion_c: '',
        alt1_repair_type_c: '',
        alt1_roadside_assistance_c: false,
        alt1_saving_amount_c: null,
        alt1_specific_driver_c: false,
        alt1_suminsured_c: null,
        alt1_total_saving_amount_c: null,
        alt1_tpl_accident_injury_c: null,
        alt1_tpl_person_injury_c: null,
        alt1_tpl_propertydmg_c: null,
        alt2_adt_bailbond_c: null,
        alt2_adt_medical_expenses_c: null,
        alt2_adt_personal_accident_c: null,
        alt2_benefit_1_c: '',
        alt2_benefit_2_c: '',
        alt2_car_code_c: null,
        alt2_car_usage_c: null,
        alt2_cmi_price_c: null,
        alt2_condition_1_c: '',
        alt2_condition_2_c: '',
        alt2_condition_3_c: '',
        alt2_discount_broker_c: null,
        alt2_gross_premium_c: null,
        alt2_insurance_class_c: '',
        alt2_insurance_country_c: '',
        alt2_insurer_name_c: '',
        alt2_manual_quote_c: false,
        alt2_max_suminsured_c: null,
        alt2_owndmg_deductible_c: null,
        alt2_owndmg_firetheft_c: null,
        alt2_owndmg_flood_c: null,
        alt2_person_covered_no_c: null,
        alt2_plan_expire_c: null,
        alt2_plan_name_c: '',
        alt2_plan_name_detail_c: '',
        alt2_price_aft_disc_c: null,
        alt2_promotion_c: '',
        alt2_repair_type_c: '',
        alt2_roadside_assistance_c: false,
        alt2_saving_amount_c: null,
        alt2_specific_driver_c: false,
        alt2_suminsured_c: null,
        alt2_total_saving_amount_c: null,
        alt2_tpl_accident_injury_c: null,
        alt2_tpl_person_injury_c: null,
        alt2_tpl_propertydmg_c: null,
        amount_c: null,
        aos_quotes_id_c: null,
        approval_issue: null,
        approval_status: null,
        asset_assets_id_c: '10077ead-b4ed-27ef-945a-5ea94c93e38f',
        assigned_user_id: 'a84fd769-c52e-65c3-dc09-5b8cf04cfc12',
        beneficiary_c: null,
        benefit_1_c: '',
        benefit_2_c: '',
        billing_account_id: null,
        billing_address_city: null,
        billing_address_country: null,
        billing_address_postalcode: null,
        billing_address_state: null,
        billing_address_street: null,
        billing_contact_id: '10077ead-b4ed-27ef-945a-5ea94c93e38f',
        broker_code_c: null,
        callback_datetime_c: null,
        campaign_end_date_c: null,
        campaign_start_date_c: null,
        campid_c: '829968422',
        car_camera_c: false,
        car_cc_c: '',
        car_code_c: null,
        car_color_code_c: null,
        car_inspection_c: false,
        car_make_c: 'BMW',
        car_make_id_c: '10013',
        car_model_c: 'X1',
        car_model_id_c: '100094',
        car_modification_c: '',
        car_modification_value_c: null,
        car_ncb_c: null,
        car_regis_province_c: null,
        car_submodel_c: 'Wagon 4 Doors sDrive20d 2.0',
        car_submodel_id_c: '50527',
        car_usage_c: 'Personal',
        car_value_c: null,
        car_year_registration_c: '2013',
        card_token_c: null,
        carplate_c: null,
        chasis_number_c: null,
        check_log_c: false,
        claim_details_c: '',
        cmi_end_date_c: null,
        cmi_net_premium_c: null,
        cmi_number_c: null,
        cmi_only_c: false,
        cmi_price_c: null,
        cmi_received_date_c: null,
        cmi_send_date_c: null,
        cmi_start_date_c: null,
        com_diff_total_c: null,
        com_ect_cmi_cbc_amt_c: null,
        com_ect_cmi_cbc_per_c: null,
        com_ect_cmi_oic_amt_c: null,
        com_ect_cmi_oic_per_c: null,
        com_ect_cmi_ov_amt_c: null,
        com_ect_cmi_ov_per_c: null,
        com_ect_cmi_total_amt_c: null,
        com_ect_cmi_total_per_c: null,
        com_ect_vmi_cbc_amt_c: null,
        com_ect_vmi_cbc_per_c: null,
        com_ect_vmi_oic_amt_c: null,
        com_ect_vmi_oic_per_c: null,
        com_ect_vmi_ov_amt_c: null,
        com_ect_vmi_ov_per_c: null,
        com_ect_vmi_total_amt_c: null,
        com_ect_vmi_total_per_c: null,
        com_ins_vmi_cbc_amt_c: null,
        com_ins_vmi_oic_amt_c: null,
        com_ins_vmi_ov_amt_c: null,
        com_ins_vmi_total_amt_c: null,
        com_rev_gross_c: null,
        com_rev_mkt_inc_c: null,
        com_rev_net_c: null,
        com_rev_total_com_c: null,
        com_rev_total_discount_c: null,
        condition_1_c: '',
        condition_2_c: '',
        condition_3_c: '',
        contact_car_inspection_c: '',
        contact_id_c: null,
        cover_note_no_c: null,
        created_by: '3c0d03dd-0249-05fb-7357-58c64900cec5',
        currency_id: null,
        current_insurer_c: null,
        customer_received_date_c: null,
        customer_received_date_cmi_c: null,
        date_entered: '2020-04-29T09:44:55+00:00',
        date_modified: '2020-05-09T07:08:31.913+00:00',
        deleted: false,
        description: null,
        discount_amount: null,
        discount_amount_usdollar: 0,
        discount_broker_c: null,
        ecamp_easycampaigns_id_c: '8aa4c26d-92aa-6d87-4a64-5e68b05dc328',
        endorsement_c: false,
        endorsement_description_c: '',
        endorsement_status_c: null,
        engine_number_c: null,
        ermsplanid_c: null,
        expiration: null,
        extend_time_c: false,
        fault_claim_no_c: null,
        fault_claim_value_c: null,
        forecast_due_date_c: null,
        form_id_c: 'PG-CMB-TH-Compare',
        free_health_send_date_c: null,
        free_home_send_date_c: null,
        free_rsa_send_date_c: null,
        fuel_type_c: null,
        ga_campaign_c: '',
        ga_leadsource_c: 'S3E19NPS26',
        ga_medium_c: '',
        gas_tank_number_c: null,
        gclid_c: '',
        gg_customer_id_c: '2079470879.1588153406',
        gross_premium_c: null,
        id: '27fa5215-d894-8ede-f49e-5ea94c4bc8bd',
        id_c: '27fa5215-d894-8ede-f49e-5ea94c4bc8bd',
        insurance_class_c: '1',
        insurance_country_c: null,
        insurer_name_c: null,
        insurer_reject_reason_c: null,
        invoice_status: 'Not Invoiced',
        ipp_periods_c: null,
        is_automatic_renewal_c: null,
        is_compulsory_c: false,
        is_convert_c: false,
        is_free_cmi_c: false,
        is_free_health_assist_c: null,
        is_free_home_assist_c: null,
        is_free_rsa_c: false,
        is_genesys_uploaded_c: null,
        is_modify_car_20000_c: null,
        is_nb_regen_c: null,
        is_nonoil_engine_c: null,
        is_portal_c: null,
        is_renewal_c: false,
        is_special_si_c: null,
        lead_source_c: 'portal',
        mail_rsa_to_insurer_c: false,
        mail_to_insurer_c: null,
        manual_quote_c: false,
        max_suminsured_c: null,
        modified_user_id: '1',
        mordee_code_c: null,
        name: '20P1106547R00',
        net_premium_c: null,
        note_c: '',
        number: 249126,
        opportunity_id: null,
        owndmg_deductible_c: null,
        owndmg_firetheft_c: null,
        owndmg_flood_c: null,
        payment_type_c: null,
        person_covered_no_c: null,
        phone_car_inspection_c: '',
        plan_expire_c: null,
        plan_name_c: null,
        plan_name_detail_c: null,
        policy_cancel_reason_c: null,
        policy_number_c: null,
        policy_received_date_c: null,
        policy_request_date_c: null,
        policy_send_date_c: null,
        portalreeditable_c: null,
        pre_gross_premium_c: null,
        pre_insurance_class_c: null,
        pre_insurer_name_c: null,
        pre_plan_name_c: null,
        pre_repair_type_c: null,
        pre_suminsured_c: null,
        price_aft_disc_c: null,
        promotion_c: '',
        proposal_cancel_reason_c: null,
        question_province_c: '',
        quote_status_c: 'ignore',
        quote_type_c: 'newbusiness',
        redbook_id_c: '',
        remark_c: '',
        repair_type_c: null,
        req_e_policy_c: null,
        req_post_policy_c: null,
        right_claim_no_c: null,
        rn_notice_update_on_c: null,
        roadside_assistance_c: false,
        saving_amount_c: null,
        sd1_dob_c: null,
        sd1_license_no_c: '',
        sd1_name_c: '',
        sd2_dob_c: null,
        sd2_license_no_c: '',
        sd2_name_c: '',
        sda_flag_c: null,
        seednumber_c: 1,
        shipping_address_city: null,
        shipping_address_country: null,
        shipping_address_postalcode: null,
        shipping_address_state: null,
        shipping_address_street: null,
        shipping_amount: null,
        shipping_amount_usdollar: 0,
        shipping_tax: null,
        shipping_tax_amt: null,
        shipping_tax_amt_usdollar: 0,
        specific_driver_c: false,
        specific_driver_number_c: '',
        staff_disc_c: null,
        staff_discount_amt_c: null,
        staff_discount_c: null,
        stage: 'Draft',
        subtotal_amount: null,
        subtotal_amount_usdollar: 0,
        subtotal_tax_amount: null,
        subtotal_tax_amount_usdollar: 0,
        suminsured_c: null,
        super_lead_c: false,
        tax_amount: null,
        tax_amount_usdollar: 0,
        template_ddown_c: null,
        term: null,
        terms_c: null,
        total_amount: null,
        total_amount_usdollar: 0,
        total_amt: null,
        total_amt_usdollar: 0,
        total_gross_premium_c: null,
        total_price_c: null,
        total_saving_amount_c: null,
        total_saving_amount_final_c: null,
        tpl_accident_injury_c: null,
        tpl_person_injury_c: null,
        tpl_propertydmg_c: null,
        tracking_number_c: null,
        transfer_code_c: false,
        transfer_code_description_c: '',
        user_id_c: null,
        vmi_end_date_c: null,
        vmi_start_date_c: null,
        voucher_code_c: null,
      },
    },
  ],
};

const sortedRawData = {
  calls: [],
  contact: {
    assigned_to: {
      created_by: '1',
      date_entered: '2020-05-21T08:46:02+00:00',
      date_modified: '2020-07-20T04:35:45+00:00',
      deleted: false,
      department: 'marketing',
      employee_status: 'Terminated',
      external_auth_only: false,
      factor_auth: false,
      id: '67c94893-c710-c093-9069-5ec63fa94546',
      is_admin: false,
      is_group: false,
      last_name: 'Parinda Jaisamut',
      modified_user_id: '1',
      phone_work: '5598',
      portal_only: false,
      pwd_last_changed: '2020-05-21T08:46:00+00:00',
      receive_notifications: true,
      reports_to_id: 'af75783b-c482-1523-a03d-58a25f4fbe76',
      show_on_employees: true,
      status: 'Inactive',
      sugar_login: true,
      system_generated_password: true,
      user_hash: '$1$bRFSKPT2$nlnZBBy5yeL52FhhgBu801',
      user_name: 'parinda',
    },
    data: {
      age_c: 0,
      assigned_user_id: '67c94893-c710-c093-9069-5ec63fa94546',
      clean_email_c: false,
      corporation_c: false,
      created_by: '3c0d03dd-0249-05fb-7357-58c64900cec5',
      date_entered: '2020-04-29T09:44:55+00:00',
      date_modified: '2020-05-23T08:01:55+00:00',
      deleted: false,
      do_not_call: false,
      duplicate_email_c: false,
      ecamp_easycampaigns_id_c: '8aa4c26d-92aa-6d87-4a64-5e68b05dc328',
      first_name: 'ดี้',
      gg_customer_id_c: '2079470879.1588153406',
      id: '10077ead-b4ed-27ef-945a-5ea94c93e38f',
      id_c: '10077ead-b4ed-27ef-945a-5ea94c93e38f',
      immortal_c: false,
      jjwg_maps_lat_c: 0,
      jjwg_maps_lng_c: 0,
      lawful_basis: '^^',
      lead_source: 'portal',
      modified_user_id: '6622fe92-d88a-6573-d1e0-5c78b2b309d5',
      phone_mobile: '0819996603',
      policy_flag_c: false,
      portal_account_disabled: false,
      portal_user_type: 'Single',
      pre_active_reason_c: 'no_answer',
      proposal_flag_c: false,
      status_c: 'Pre_active',
    },
  },
  documents: [],
  email_addresses: [
    {
      confirm_opt_in: 'confirmed-opt-in',
      date_created: '2020-04-29T09:44:00+00:00',
      date_modified: '2020-05-25T07:42:10+00:00',
      deleted: false,
      email_address: 'Asae.handee@gmAil.com',
      email_address_caps: 'ASAE.HANDEE@GMAIL.COM',
      id: '61c5acf5-df7b-ec8f-0133-5ea94c047487',
      invalid_email: false,
      opt_out: false,
    },
  ],
  quotes: [
    {
      assigned_to: {
        created_by: '5ee4a147-abfa-e3dc-5a3e-598c2b329653',
        date_entered: '2018-09-03T08:27:51+00:00',
        date_modified: '2023-04-18T07:59:16+00:00',
        deleted: false,
        department: 'marketing',
        employee_status: 'Active',
        external_auth_only: false,
        factor_auth: false,
        id: 'a84fd769-c52e-65c3-dc09-5b8cf04cfc12',
        is_admin: false,
        is_group: false,
        last_name: 'Suwat Meeboon',
        modified_user_id: '5639157a-3f78-681f-51b9-6007b3dc1189',
        phone_work: '5533',
        portal_only: false,
        pwd_last_changed: '2018-10-03T22:36:00+00:00',
        receive_notifications: false,
        reports_to_id: 'af75783b-c482-1523-a03d-58a25f4fbe76',
        show_on_employees: true,
        status: 'Inactive',
        sugar_login: true,
        system_generated_password: false,
        title: '6304001385',
        user_hash: '$1$jK5.584.$uEsjvy8/ub1alaULVcbW4/',
        user_name: 'suwat',
      },
      quote: {
        alt1_manual_quote_c: false,
        alt1_roadside_assistance_c: false,
        alt1_specific_driver_c: false,
        alt2_manual_quote_c: false,
        alt2_roadside_assistance_c: false,
        alt2_specific_driver_c: false,
        asset_assets_id_c: '10077ead-b4ed-27ef-945a-5ea94c93e38f',
        assigned_user_id: 'a84fd769-c52e-65c3-dc09-5b8cf04cfc12',
        billing_contact_id: '10077ead-b4ed-27ef-945a-5ea94c93e38f',
        campid_c: '829968422',
        car_camera_c: false,
        car_inspection_c: false,
        car_make_c: 'BMW',
        car_make_id_c: '10013',
        car_model_c: 'X1',
        car_model_id_c: '100094',
        car_submodel_c: 'Wagon 4 Doors sDrive20d 2.0',
        car_submodel_id_c: '50527',
        car_usage_c: 'Personal',
        car_year_registration_c: '2013',
        check_log_c: false,
        cmi_only_c: false,
        created_by: '3c0d03dd-0249-05fb-7357-58c64900cec5',
        date_entered: '2020-04-29T09:44:55+00:00',
        date_modified: '2020-05-09T07:08:31.913+00:00',
        deleted: false,
        discount_amount_usdollar: 0,
        ecamp_easycampaigns_id_c: '8aa4c26d-92aa-6d87-4a64-5e68b05dc328',
        endorsement_c: false,
        extend_time_c: false,
        form_id_c: 'PG-CMB-TH-Compare',
        ga_leadsource_c: 'S3E19NPS26',
        gg_customer_id_c: '2079470879.1588153406',
        id: '27fa5215-d894-8ede-f49e-5ea94c4bc8bd',
        id_c: '27fa5215-d894-8ede-f49e-5ea94c4bc8bd',
        insurance_class_c: '1',
        invoice_status: 'Not Invoiced',
        is_compulsory_c: false,
        is_convert_c: false,
        is_free_cmi_c: false,
        is_free_rsa_c: false,
        is_renewal_c: false,
        lead_source_c: 'portal',
        mail_rsa_to_insurer_c: false,
        manual_quote_c: false,
        modified_user_id: '1',
        name: '20P1106547R00',
        number: 249126,
        quote_status_c: 'ignore',
        quote_type_c: 'newbusiness',
        roadside_assistance_c: false,
        seednumber_c: 1,
        shipping_amount_usdollar: 0,
        shipping_tax_amt_usdollar: 0,
        specific_driver_c: false,
        stage: 'Draft',
        subtotal_amount_usdollar: 0,
        subtotal_tax_amount_usdollar: 0,
        super_lead_c: false,
        tax_amount_usdollar: 0,
        total_amount_usdollar: 0,
        total_amt_usdollar: 0,
        transfer_code_c: false,
      },
    },
  ],
};

const filteredRawData = {
  contact: {
    assigned_to: {
      address_city: null,
      address_country: null,
      address_postalcode: null,
      address_state: null,
      address_street: null,
    },
    data: {
      alt_address_building_c: '',
      alt_address_city: null,
      alt_address_company_c: '',
      alt_address_country: null,
      alt_address_floor_c: '',
      alt_address_moo_c: '',
      alt_address_more_c: '',
      alt_address_name_c: '',
      alt_address_postalcode: null,
      alt_address_road_c: '',
      alt_address_room_c: '',
      alt_address_soi_c: '',
      alt_address_state: null,
      alt_address_street: null,
      alt_address_village_c: '',
      jjwg_maps_address_c: '',
      primary_address_building_c: '',
      primary_address_city: null,
      primary_address_company_c: '',
      primary_address_country: null,
      primary_address_floor_c: '',
      primary_address_moo_c: '',
      primary_address_more_c: '',
      primary_address_postalcode: null,
      primary_address_road_c: '',
      primary_address_room_c: '',
      primary_address_soi_c: '',
      primary_address_state: null,
      primary_address_street: null,
      primary_address_village_c: '',
    },
  },
  email_addresses: {
    '0': {
      email_address: 'Asae.handee@gmAil.com',
      email_address_caps: 'ASAE.HANDEE@GMAIL.COM',
    },
  },
  quotes: {
    '0': {
      assigned_to: {
        address_city: null,
        address_country: null,
        address_postalcode: null,
        address_state: null,
        address_street: null,
      },
      quote: {
        billing_address_city: null,
        billing_address_country: null,
        billing_address_postalcode: null,
        billing_address_state: null,
        billing_address_street: null,
        shipping_address_city: null,
        shipping_address_country: null,
        shipping_address_postalcode: null,
        shipping_address_state: null,
        shipping_address_street: null,
      },
    },
  },
};

const sortedObject = {
  a: {
    a: 'hello',
    b: 'world',
  },
  b: 'hello',
  c: 'world',
  e: {},
  f: [
    {
      h: 'hello',
      i: 'world',
    },
  ],
};

const filteredObject1 = {
  a: {
    a: 'hello',
  },
};

const filteredObject2 = {
  a: {
    b: 'world',
  },
  b: 'hello',
};

const translatedObject = {
  'foreignLead.a': {
    'foreignLead.a': 'hello',
    'foreignLead.b': 'world',
  },
  'foreignLead.b': 'hello',
  'foreignLead.c': 'world',
  'foreignLead.d': null,
  'foreignLead.e': {
    'foreignLead.a': '',
    'foreignLead.b': null,
  },
  'foreignLead.f': [
    {
      'foreignLead.g': null,
      'foreignLead.h': 'hello',
      'foreignLead.i': 'world',
      'foreignLead.j': '',
    },
  ],
};

describe('sortObjectAlphabetically', () => {
  it('filters out keys with null and empty string value and sorts the object alphabetically', () => {
    const result = sortObjectAlphabetically(unsortedObject);
    expect(result).toMatchObject(sortedObject);
  });

  it('filters out keys with null and empty string value and sorts the object alphabetically', () => {
    const result = sortObjectAlphabetically(rawData);
    expect(result).toMatchObject(sortedRawData);
  });
});

describe('filterDeepNestedObjectByKeys', () => {
  it('returns the filtered data', () => {
    const result = filterDeepNestedObjectByKeys(unsortedObject, 'a');
    expect(result).toMatchObject(filteredObject1);
  });

  it('returns the filtered data', () => {
    const result = filterDeepNestedObjectByKeys(unsortedObject, 'b');
    expect(result).toMatchObject(filteredObject2);
  });

  it('returns the filtered data', () => {
    const result = filterDeepNestedObjectByKeys(rawData, 'address');
    expect(result).toMatchObject(filteredRawData);
  });
});

describe('filterDeepNestedObjectByFields', () => {
  it('returns the filtered data', () => {
    const result = filterDeepNestedObjectByFields(unsortedObject, ['a']);
    expect(result).toMatchObject(filteredObject1);
  });

  it('returns the filtered data', () => {
    const result = filterDeepNestedObjectByFields(unsortedObject, ['b']);
    expect(result).toMatchObject(filteredObject2);
  });

  it('returns the filtered data', () => {
    const result = filterDeepNestedObjectByFields(rawData, [
      'address_city',
      'address_country',
      'address_postalcode',
      'address_state',
      'address_street',
    ]);
    expect(result).toMatchObject({
      contact: {
        assigned_to: {
          address_city: null,
          address_country: null,
          address_postalcode: null,
          address_state: null,
          address_street: null,
        },
      },
      quotes: {
        '0': {
          assigned_to: {
            address_city: null,
            address_country: null,
            address_postalcode: null,
            address_state: null,
            address_street: null,
          },
        },
      },
    });
  });
});

describe('addTranslationKey', () => {
  it('returns the object with translatable keys', () => {
    const result = addTranslationKey(unsortedObject);
    expect(result).toMatchObject(translatedObject);
  });
});

describe('getPresetFields', () => {
  it('returns null when source ID doesnt match with any foreign lead', () => {
    const result = getPresetFields('source/fakeSource');
    expect(result).toBe(null);
  });

  it('returns adb presets #1', () => {
    const result = getPresetFields(
      'sources/4d3d97c0-d65a-4a9f-a660-c11b533e186e'
    );
    expect(result).toBe(adbPresetFields);
  });

  it('returns adb presets #2', () => {
    const result = getPresetFields(
      'sources/287cf90d-f15c-4f1d-94ee-e6f10f2be0a0'
    );
    expect(result).toBe(adbPresetFields);
  });

  it('returns nana presets #1', () => {
    const result = getPresetFields(
      'sources/ade2e4bb-23dd-4fa8-bd06-9e0b83df3fad'
    );
    expect(result).toBe(nanaPresetFields);
  });

  it('returns nana presets #2', () => {
    const result = getPresetFields(
      'sources/6a6d72ea-2558-4cae-848d-9e020d55ae39'
    );
    expect(result).toBe(nanaPresetFields);
  });

  it('returns ect presets #1', () => {
    const result = getPresetFields(
      'sources/ac666bff-ec89-423e-a55d-9d0534f33b63'
    );
    expect(result).toBe(ectPresetFields);
  });

  it('returns ect presets #2', () => {
    const result = getPresetFields(
      'sources/6a81eae5-929b-479b-a8aa-8a1ff0fc7fa7'
    );
    expect(result).toBe(ectPresetFields);
  });
});

describe('redactSensitiveData', () => {
  it('returns the object with redacted data', () => {
    const result = redactSensitiveData({
      emails: ['hello@gmail.com', 'tori@hotmail.com', 'ab@cde.gh.ij'],
      phone_home: ['0999999999', '0999999999', 'abcdefg'],
      phone_work: '0999999999',
      user_emails: {
        email_address: 'haakuKaale@hotmail.com',
      },
      Line_ID: 'rabbitCare',
    });

    expect(result).toMatchObject({
      emails: ['helxx@gmail.com', 'torx@hotmail.com', 'ab@cde.gh.ij'],
      phone_home: ['099xxxxxxx', '099xxxxxxx', 'abcdefg'],
      phone_work: '099xxxxxxx',
      user_emails: {
        email_address: 'haaxxxxxxx@hotmail.com',
      },
      Line_ID: 'rabbitCare',
    });
  });
});
