import { waitFor } from '@testing-library/dom';
import { screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import React from 'react';

import {
  paymentHandlerAlreadyException,
  paymentHandlerErrorException,
  paymentHandlerMandatoryException,
} from '__mocks__/handlers/leadHandler';
import { server } from '__mocks__/server';
import { render } from '__tests__/rtl-test-utils';
import { getString } from 'presentation/theme/localization';
import { mockUseFlags } from 'shared/helper/flagsmith';
import { formatSatangToBaht } from 'utils/currency';
import { useGetLeadPaymentDetailsQuery } from 'data/slices/leadSlice';

import CreatePaymentPage from '.';

// Mock the useLeadUpdater hook
jest.mock(
  'presentation/pages/car-insurance/LeadDetailsPage/leadUpdater',
  () => ({
    __esModule: true,
    default: jest.fn(() => ({
      jsonUpdater: jest.fn((payload: any) => {
        console.log('payload in mock', payload);
        throw new Error('test');
      }),
      updateLead: jest.fn(),
      resetCheckout: jest.fn(),
    })),
  })
);

Object.defineProperty(window, 'location', {
  get() {
    return {
      href: 'https://localhost:3030/leads/1a107226-6f37-4ceb-94bc-a352b89c063b',
    };
  },
});

jest.mock('presentation/redux/selectors/lead', () => ({
  useGetLeadSelector: jest.fn().mockReturnValue({ name: 'leads/test-data' }),
}));

jest.mock('data/slices/leadSlice', () => ({
  ...jest.requireActual('data/slices/leadSlice'),
  useGetLeadPaymentDetailsQuery: jest.fn(() => ({
    data: {
      customerInformation: {
        leadId: 'leads/9d94c07e-9d92-477d-9b0c-3b60326dc242',
        humanId: 'L9906227',
        customerName: 'Hein Aung',
      },
      quoteInformation: {
        insurerName: 'บริษัท ธนชาตประกันภัย จำกัด (มหาชน)',
        insuranceKind: 'BOTH',
        insuranceType: 'TYPE_1',
        licensePlate: '111-2222 กท',
        car: 'Toyota Vios 2020 1500 CC (4 Doors) ENTRY ',
        grossMandatoryPremium: '64521',
        grossVoluntaryPremium: '1550000',
        discount: '0',
        totalPremium: '1614521',
      },
      paymentSelections: [],
      paymentOptions: {
        fullPayment: {
          packagePrice: {
            voluntaryPrice: '1550000',
            compulsoryPrice: '64521',
            totalPrice: '1614521',
          },
          paymentDetails: [
            {
              paymentMethod: 'ONLINECARD',
              priceSummary: {
                interestRate: 0,
                interestAmount: '0',
                processingFeeRate: 1,
                processingFeeAmount: '16145',
                feeRate: 1,
                feeAmount: '16145',
                discountRate: 0,
                discountAmount: '0',
                netDiscountRate: 1,
                netDiscountAmount: '16145',
                packagePriceAfterDiscount: '1614521',
                netPremiumAmount: '1630666',
                initialAmount: '0',
                subsequentAmount: '0',
                discount: null,
                shipmentFee: '0',
                feeAmountNoShip: '16145',
              },
              installmentDetail: [],
            },
            {
              paymentMethod: 'QR_CODE',
              priceSummary: {
                interestRate: 0,
                interestAmount: '0',
                processingFeeRate: 0,
                processingFeeAmount: '0',
                feeRate: 0,
                feeAmount: '0',
                discountRate: 0,
                discountAmount: '0',
                netDiscountRate: 0,
                netDiscountAmount: '0',
                packagePriceAfterDiscount: '1614521',
                netPremiumAmount: '1614521',
                initialAmount: '0',
                subsequentAmount: '0',
                discount: null,
                shipmentFee: '0',
                feeAmountNoShip: '0',
              },
              installmentDetail: [],
            },
            {
              paymentMethod: 'BANK_TRANSFER',
              priceSummary: {
                interestRate: 0,
                interestAmount: '0',
                processingFeeRate: 0,
                processingFeeAmount: '0',
                feeRate: 0,
                feeAmount: '0',
                discountRate: 0,
                discountAmount: '0',
                netDiscountRate: 0,
                netDiscountAmount: '0',
                packagePriceAfterDiscount: '1614521',
                netPremiumAmount: '1614521',
                initialAmount: '0',
                subsequentAmount: '0',
                discount: null,
                shipmentFee: '0',
                feeAmountNoShip: '0',
              },
              installmentDetail: [],
            },
            {
              paymentMethod: 'DIRECT_PAYMENT',
              priceSummary: {
                interestRate: 0,
                interestAmount: '0',
                processingFeeRate: 0,
                processingFeeAmount: '0',
                feeRate: 0,
                feeAmount: '0',
                discountRate: 0,
                discountAmount: '0',
                netDiscountRate: 0,
                netDiscountAmount: '0',
                packagePriceAfterDiscount: '1614521',
                netPremiumAmount: '1614521',
                initialAmount: '0',
                subsequentAmount: '0',
                discount: null,
                shipmentFee: '0',
                feeAmountNoShip: '0',
              },
              installmentDetail: [],
            },
            {
              paymentMethod: 'EDC',
              priceSummary: {
                interestRate: 0,
                interestAmount: '0',
                processingFeeRate: 1,
                processingFeeAmount: '16145',
                feeRate: 1,
                feeAmount: '16145',
                discountRate: 0,
                discountAmount: '0',
                netDiscountRate: 1,
                netDiscountAmount: '16145',
                packagePriceAfterDiscount: '1614521',
                netPremiumAmount: '1630666',
                initialAmount: '0',
                subsequentAmount: '0',
                discount: null,
                shipmentFee: '0',
                feeAmountNoShip: '16145',
              },
              installmentDetail: [],
            },
          ],
        },
        rabbitCareInstallment: {
          packagePrice: {
            voluntaryPrice: '1550000',
            compulsoryPrice: '64521',
            totalPrice: '1614521',
          },
          availablePlans: [3, 6, 8, 10],
          installmentPlans: [
            {
              numberOfInstallment: 3,
              paymentDetails: [
                {
                  paymentMethod: 'QR_CODE',
                  priceSummary: {
                    interestRate: 0.74,
                    interestAmount: '11064',
                    processingFeeRate: 0.37,
                    processingFeeAmount: '5533',
                    feeRate: 1.1,
                    feeAmount: '16597',
                    discountRate: 3,
                    discountAmount: '46500',
                    netDiscountRate: -1.85,
                    netDiscountAmount: '-29903',
                    packagePriceAfterDiscount: '1568021',
                    netPremiumAmount: '1584619',
                    initialAmount: '571221',
                    subsequentAmount: '506699',
                    discount: {
                      type: 'DISCOUNT_TYPE_RCL',
                      percentage: 300,
                      amount: '46500',
                    },
                    shipmentFee: '0',
                    feeAmountNoShip: '16597',
                  },
                  installmentDetail: [
                    {
                      period: 1,
                      paymentAmount: '571221',
                      principal: '501167',
                      addOns: '64521',
                      interest: '0',
                      processingFee: '5533',
                      principalBalance: '1002333',
                      interestBalance: '11064',
                      processingFeeBalance: '0',
                      totalBalance: '1013398',
                    },
                    {
                      period: 2,
                      paymentAmount: '506699',
                      principal: '499332',
                      addOns: '0',
                      interest: '7367',
                      processingFee: '0',
                      principalBalance: '503002',
                      interestBalance: '3697',
                      processingFeeBalance: '0',
                      totalBalance: '506699',
                    },
                    {
                      period: 3,
                      paymentAmount: '506699',
                      principal: '503002',
                      addOns: '0',
                      interest: '3697',
                      processingFee: '0',
                      principalBalance: '0',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '0',
                    },
                  ],
                },
              ],
            },
            {
              numberOfInstallment: 6,
              paymentDetails: [
                {
                  paymentMethod: 'QR_CODE',
                  priceSummary: {
                    interestRate: 2.5,
                    interestAmount: '37589',
                    processingFeeRate: 0.5,
                    processingFeeAmount: '7518',
                    feeRate: 3,
                    feeAmount: '45107',
                    discountRate: 3,
                    discountAmount: '46500',
                    netDiscountRate: -0.09,
                    netDiscountAmount: '-1393',
                    packagePriceAfterDiscount: '1568021',
                    netPremiumAmount: '1613127',
                    initialAmount: '322622',
                    subsequentAmount: '258101',
                    discount: {
                      type: 'DISCOUNT_TYPE_RCL',
                      percentage: 300,
                      amount: '46500',
                    },
                    shipmentFee: '0',
                    feeAmountNoShip: '45107',
                  },
                  installmentDetail: [
                    {
                      period: 1,
                      paymentAmount: '322622',
                      principal: '250583',
                      addOns: '64521',
                      interest: '0',
                      processingFee: '7518',
                      principalBalance: '1252917',
                      interestBalance: '37589',
                      processingFeeBalance: '0',
                      totalBalance: '1290506',
                    },
                    {
                      period: 2,
                      paymentAmount: '258101',
                      principal: '245653',
                      addOns: '0',
                      interest: '12448',
                      processingFee: '0',
                      principalBalance: '1007263',
                      interestBalance: '25142',
                      processingFeeBalance: '0',
                      totalBalance: '1032405',
                    },
                    {
                      period: 3,
                      paymentAmount: '258101',
                      principal: '248094',
                      addOns: '0',
                      interest: '10007',
                      processingFee: '0',
                      principalBalance: '759169',
                      interestBalance: '15134',
                      processingFeeBalance: '0',
                      totalBalance: '774304',
                    },
                    {
                      period: 4,
                      paymentAmount: '258101',
                      principal: '250559',
                      addOns: '0',
                      interest: '7542',
                      processingFee: '0',
                      principalBalance: '508610',
                      interestBalance: '7592',
                      processingFeeBalance: '0',
                      totalBalance: '516202',
                    },
                    {
                      period: 5,
                      paymentAmount: '258101',
                      principal: '253048',
                      addOns: '0',
                      interest: '5053',
                      processingFee: '0',
                      principalBalance: '255562',
                      interestBalance: '2539',
                      processingFeeBalance: '0',
                      totalBalance: '258101',
                    },
                    {
                      period: 6,
                      paymentAmount: '258101',
                      principal: '255562',
                      addOns: '0',
                      interest: '2539',
                      processingFee: '0',
                      principalBalance: '0',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '0',
                    },
                  ],
                },
              ],
            },
            {
              numberOfInstallment: 8,
              paymentDetails: [
                {
                  paymentMethod: 'QR_CODE',
                  priceSummary: {
                    interestRate: 3.77,
                    interestAmount: '58370',
                    processingFeeRate: 0.54,
                    processingFeeAmount: '8339',
                    feeRate: 4.3,
                    feeAmount: '66709',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 4.13,
                    netDiscountAmount: '66709',
                    packagePriceAfterDiscount: '1614521',
                    netPremiumAmount: '1681233',
                    initialAmount: '266610',
                    subsequentAmount: '202089',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '66709',
                  },
                  installmentDetail: [
                    {
                      period: 1,
                      paymentAmount: '266610',
                      principal: '193750',
                      addOns: '64521',
                      interest: '0',
                      processingFee: '8339',
                      principalBalance: '1356250',
                      interestBalance: '58370',
                      processingFeeBalance: '0',
                      totalBalance: '1414620',
                    },
                    {
                      period: 2,
                      paymentAmount: '202089',
                      principal: '187649',
                      addOns: '0',
                      interest: '14440',
                      processingFee: '0',
                      principalBalance: '1168601',
                      interestBalance: '43930',
                      processingFeeBalance: '0',
                      totalBalance: '1212531',
                    },
                    {
                      period: 3,
                      paymentAmount: '202089',
                      principal: '189647',
                      addOns: '0',
                      interest: '12442',
                      processingFee: '0',
                      principalBalance: '978954',
                      interestBalance: '31489',
                      processingFeeBalance: '0',
                      totalBalance: '1010443',
                    },
                    {
                      period: 4,
                      paymentAmount: '202089',
                      principal: '191666',
                      addOns: '0',
                      interest: '10423',
                      processingFee: '0',
                      principalBalance: '787288',
                      interestBalance: '21066',
                      processingFeeBalance: '0',
                      totalBalance: '808354',
                    },
                    {
                      period: 5,
                      paymentAmount: '202089',
                      principal: '193707',
                      addOns: '0',
                      interest: '8382',
                      processingFee: '0',
                      principalBalance: '593582',
                      interestBalance: '12684',
                      processingFeeBalance: '0',
                      totalBalance: '606266',
                    },
                    {
                      period: 6,
                      paymentAmount: '202089',
                      principal: '195769',
                      addOns: '0',
                      interest: '6320',
                      processingFee: '0',
                      principalBalance: '397813',
                      interestBalance: '6364',
                      processingFeeBalance: '0',
                      totalBalance: '404177',
                    },
                    {
                      period: 7,
                      paymentAmount: '202089',
                      principal: '197853',
                      addOns: '0',
                      interest: '4235',
                      processingFee: '0',
                      principalBalance: '199960',
                      interestBalance: '2129',
                      processingFeeBalance: '0',
                      totalBalance: '202089',
                    },
                    {
                      period: 8,
                      paymentAmount: '202089',
                      principal: '199960',
                      addOns: '0',
                      interest: '2129',
                      processingFee: '0',
                      principalBalance: '0',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '0',
                    },
                  ],
                },
              ],
            },
            {
              numberOfInstallment: 10,
              paymentDetails: [
                {
                  paymentMethod: 'QR_CODE',
                  priceSummary: {
                    interestRate: 3.45,
                    interestAmount: '53433',
                    processingFeeRate: 1.15,
                    processingFeeAmount: '17825',
                    feeRate: 4.6,
                    feeAmount: '71258',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 4.41,
                    netDiscountAmount: '71258',
                    packagePriceAfterDiscount: '1614521',
                    netPremiumAmount: '1685782',
                    initialAmount: '469846',
                    subsequentAmount: '135104',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '71258',
                  },
                  installmentDetail: [
                    {
                      period: 1,
                      paymentAmount: '469846',
                      principal: '387500',
                      addOns: '64521',
                      interest: '0',
                      processingFee: '17825',
                      principalBalance: '1162500',
                      interestBalance: '53433',
                      processingFeeBalance: '0',
                      totalBalance: '1215933',
                    },
                    {
                      period: 2,
                      paymentAmount: '135104',
                      principal: '124544',
                      addOns: '0',
                      interest: '10559',
                      processingFee: '0',
                      principalBalance: '1037956',
                      interestBalance: '42874',
                      processingFeeBalance: '0',
                      totalBalance: '1080830',
                    },
                    {
                      period: 3,
                      paymentAmount: '135104',
                      principal: '125676',
                      addOns: '0',
                      interest: '9428',
                      processingFee: '0',
                      principalBalance: '912280',
                      interestBalance: '33446',
                      processingFeeBalance: '0',
                      totalBalance: '945726',
                    },
                    {
                      period: 4,
                      paymentAmount: '135104',
                      principal: '126817',
                      addOns: '0',
                      interest: '8287',
                      processingFee: '0',
                      principalBalance: '785463',
                      interestBalance: '25159',
                      processingFeeBalance: '0',
                      totalBalance: '810622',
                    },
                    {
                      period: 5,
                      paymentAmount: '135104',
                      principal: '127969',
                      addOns: '0',
                      interest: '7135',
                      processingFee: '0',
                      principalBalance: '657494',
                      interestBalance: '18025',
                      processingFeeBalance: '0',
                      totalBalance: '675519',
                    },
                    {
                      period: 6,
                      paymentAmount: '135104',
                      principal: '129131',
                      addOns: '0',
                      interest: '5972',
                      processingFee: '0',
                      principalBalance: '528362',
                      interestBalance: '12052',
                      processingFeeBalance: '0',
                      totalBalance: '540415',
                    },
                    {
                      period: 7,
                      paymentAmount: '135104',
                      principal: '130304',
                      addOns: '0',
                      interest: '4799',
                      processingFee: '0',
                      principalBalance: '398058',
                      interestBalance: '7253',
                      processingFeeBalance: '0',
                      totalBalance: '405311',
                    },
                    {
                      period: 8,
                      paymentAmount: '135104',
                      principal: '131488',
                      addOns: '0',
                      interest: '3616',
                      processingFee: '0',
                      principalBalance: '266570',
                      interestBalance: '3637',
                      processingFeeBalance: '0',
                      totalBalance: '270207',
                    },
                    {
                      period: 9,
                      paymentAmount: '135104',
                      principal: '132682',
                      addOns: '0',
                      interest: '2421',
                      processingFee: '0',
                      principalBalance: '133888',
                      interestBalance: '1216',
                      processingFeeBalance: '0',
                      totalBalance: '135104',
                    },
                    {
                      period: 10,
                      paymentAmount: '135104',
                      principal: '133888',
                      addOns: '0',
                      interest: '1216',
                      processingFee: '0',
                      principalBalance: '0',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '0',
                    },
                  ],
                },
              ],
            },
          ],
        },
        creditCardInstallment: {
          packagePrice: {
            voluntaryPrice: '1550000',
            compulsoryPrice: '64521',
            totalPrice: '1614521',
          },
          cardProviders: [
            {
              name: 'card-providers/BAY',
              shortName: 'BAY',
              displayNameTh: 'ธนาคารกรุงศรี',
              displayNameEn: 'Bank of Ayudhya Public Company Limited',
              minimumAmount: '0',
              availablePlans: [3, 6],
              installmentPlans: [
                {
                  numberOfInstallment: 3,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
                {
                  numberOfInstallment: 6,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
              ],
            },
            {
              name: 'card-providers/BBL',
              shortName: 'BBL',
              displayNameTh: 'ธนาคารกรุงเทพ',
              displayNameEn: 'Bangkok Bank Public Company Limited',
              minimumAmount: '0',
              availablePlans: [4, 6],
              installmentPlans: [
                {
                  numberOfInstallment: 4,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '407666',
                        subsequentAmount: '407666',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '407666',
                        subsequentAmount: '407666',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
                {
                  numberOfInstallment: 6,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
              ],
            },
            {
              name: 'card-providers/FIRST_CHOICE',
              shortName: 'FIRST_CHOICE',
              displayNameTh: 'กรุงศรีเฟิร์สช้อยส์',
              displayNameEn: 'Krungsri First Choice',
              minimumAmount: '0',
              availablePlans: [3, 6],
              installmentPlans: [
                {
                  numberOfInstallment: 3,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
                {
                  numberOfInstallment: 6,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
              ],
            },
            {
              name: 'card-providers/KBANK',
              shortName: 'KBANK',
              displayNameTh: 'ธนาคารกสิกร',
              displayNameEn: 'Kasikornbank Public Company Limited',
              minimumAmount: '0',
              availablePlans: [3, 6],
              installmentPlans: [
                {
                  numberOfInstallment: 3,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
                {
                  numberOfInstallment: 6,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
              ],
            },
            {
              name: 'card-providers/KTC',
              shortName: 'KTC',
              displayNameTh: 'บัตรกรุงไทย',
              displayNameEn: 'Krungthai Card',
              minimumAmount: '0',
              availablePlans: [3, 6],
              installmentPlans: [
                {
                  numberOfInstallment: 3,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
                {
                  numberOfInstallment: 6,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
              ],
            },
            {
              name: 'card-providers/SCB',
              shortName: 'SCB',
              displayNameTh: 'ธนาคารไทยพาณิชย์',
              displayNameEn: 'The Siam Commercial Bank Public Company Limited',
              minimumAmount: '0',
              availablePlans: [3, 6],
              installmentPlans: [
                {
                  numberOfInstallment: 3,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
                {
                  numberOfInstallment: 6,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
              ],
            },
            {
              name: 'card-providers/TTB',
              shortName: 'TTB',
              displayNameTh: 'ธนาคารทหารไทยธนชาต',
              displayNameEn: 'TMBThanachart',
              minimumAmount: '0',
              availablePlans: [3, 6],
              installmentPlans: [
                {
                  numberOfInstallment: 3,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '543555',
                        subsequentAmount: '543555',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
                {
                  numberOfInstallment: 6,
                  paymentDetails: [
                    {
                      paymentMethod: 'EDC',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                    {
                      paymentMethod: 'ONLINECARD',
                      priceSummary: {
                        interestRate: 0,
                        interestAmount: '0',
                        processingFeeRate: 1,
                        processingFeeAmount: '16145',
                        feeRate: 1,
                        feeAmount: '16145',
                        discountRate: 0,
                        discountAmount: '0',
                        netDiscountRate: 1,
                        netDiscountAmount: '16145',
                        packagePriceAfterDiscount: '1614521',
                        netPremiumAmount: '1630666',
                        initialAmount: '271777',
                        subsequentAmount: '271777',
                        discount: null,
                        shipmentFee: '0',
                        feeAmountNoShip: '16145',
                      },
                      installmentDetail: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
      },
      packageDetails: {
        paymentOption: 'FULL_PAYMENT',
        paymentMethod: 'ONLINECARD',
        numberOfInstallments: 1,
        cardProvider: '',
        priceDetails: {
          resourceName: 'customPackages/ad7f2220-f5ec-4890-a30c-d31ad0c10c98',
          priceSummary: {
            interestRate: 0,
            interestAmount: '0',
            processingFeeRate: 1,
            processingFeeAmount: '16145',
            feeRate: 1,
            feeAmount: '16145',
            discountRate: 0,
            discountAmount: '0',
            netDiscountRate: 1,
            netDiscountAmount: '16145',
            packagePriceAfterDiscount: '1614521',
            netPremiumAmount: '1630666',
            initialAmount: '0',
            subsequentAmount: '0',
            discount: null,
            shipmentFee: '0',
            feeAmountNoShip: '16145',
          },
          installmentDetails: [],
        },
      },
    },
    isLoading: false,
    isError: false,
  })),
}));

Object.assign(navigator, {
  clipboard: {
    writeText: jest.fn(),
  },
});

describe('Create Payment Page', () => {
  beforeEach(() => {
    mockUseFlags();
    render(<CreatePaymentPage />);
  });

  it.each([['FULL_PAYMENT', 0]])(
    'should display the appropriate for first month installments for %s payment option',
    async (paymentOption, firstMonth) => {
      await waitFor(() => {
        expect(screen.getByTestId('payment-option')).toBeInTheDocument();
      });

      await waitFor(() => {
        expect(
          screen.getByText(getString(`paymentOptions.${paymentOption}`))
        ).toBeInTheDocument();
      });

      const firstMonthInstallment = screen.getByTestId('firstMonthInstallment');

      expect(firstMonthInstallment).toHaveTextContent(
        formatSatangToBaht(firstMonth).toString()
      );
    }
  );

  it('should show success messge if Create Payment success', async () => {
    await waitFor(() => {
      expect(screen.getByTestId('create-payment-button')).toBeEnabled();
    });
    userEvent.click(screen.getByTestId('create-payment-button'));
    await waitFor(() => {
      expect(screen.getByTestId('success-dialog')).toBeInTheDocument();
    });
  });

  it('should show error messge if Create Payment failed', async () => {
    server.use(paymentHandlerErrorException);
    await waitFor(() => {
      expect(screen.getByTestId('create-payment-button')).toBeEnabled();
    });
    userEvent.click(screen.getByTestId('create-payment-button'));
    await waitFor(() => {
      expect(screen.getByTestId('error-dialog')).toBeInTheDocument();
    });
  });

  it('should show error messge if Create Payment already', async () => {
    server.use(paymentHandlerAlreadyException);
    await waitFor(() => {
      expect(screen.getByTestId('create-payment-button')).toBeEnabled();
    });
    userEvent.click(screen.getByTestId('create-payment-button'));
    await waitFor(() => {
      expect(screen.getByTestId('error-dialog')).toBeInTheDocument();
      expect(
        screen.getByText('createPaymentError.alreadyPaid')
      ).toBeInTheDocument();
    });
  });

  it('should show error messge if Create Payment - mandatory error', async () => {
    server.use(paymentHandlerMandatoryException);
    await waitFor(() => {
      expect(screen.getByTestId('create-payment-button')).toBeEnabled();
    });
    userEvent.click(screen.getByTestId('create-payment-button'));
    await waitFor(() => {
      expect(screen.getByTestId('error-dialog')).toBeInTheDocument();
      expect(
        screen.getByText('createPaymentError.mandatory')
      ).toBeInTheDocument();
    });
  });

  it('should render NotFound component when payment details query fails', () => {
    // Mock return value
    (useGetLeadPaymentDetailsQuery as jest.Mock).mockReturnValue({
      data: null,
      isLoading: false,
      isError: true,
    });

    render(<CreatePaymentPage />);

    expect(screen.getByTestId('not-found-wrapper')).toBeInTheDocument();
  });
});
