import type { AccountCurrentProductData } from 'shared/types/policy';

export const MockAccountProductData: AccountCurrentProductData = {
  insuranceProducts: [
    {
      product: 'products/car-insurance',
      productLabel: 'Cars and Motorcycles Insurance',
      policies: [
        {
          orderItemHumanId: 'L9922078-1',
          matterOfConnection: 'phone_number',
          carInfo: {
            year: '2023',
            brand: 'Toyota',
            carModel: 'Yaris',
            licensePlate: 'กข-1234',
          },
          packageInfo: {
            insuranceType: 'First Class',
            expirationDate: '2026-01-31',
            premiumAmount: '18000',
            sumInsured: '600000',
          },
          insurerInfo: {
            insurerName: 'ABC Insurance',
            shortNameEn: 'ABC',
            shortNameTh: 'เอบีซี',
            phone: '02-123-4567',
            website: 'https://abc-insurance.com',
          },
          paymentInfo: {
            numberOfInstallments: 12,
            paidInstallments: 5,
            paymentOption: 'installment',
            paymentMethod: 'credit_card',
            paymentDate: '2024-11-01',
            paymentAmount: 1500,
            paymentStatus: 'Paid',
          },
        },
        {
          orderItemHumanId: 'L9922078-2',
          matterOfConnection: 'phone_number',
          carInfo: {
            year: '2021',
            brand: 'Honda',
            carModel: 'Civic',
            licensePlate: 'ขค-5678',
          },
          packageInfo: {
            insuranceType: 'Second Class',
            expirationDate: '2025-12-31',
            premiumAmount: '12000',
            sumInsured: '400000',
          },
          insurerInfo: {
            insurerName: 'insurers/7',
            shortNameEn: 'ABC',
            shortNameTh: 'เอบีซี',
            phone: '02-123-4567',
            website: 'https://abc-insurance.com',
          },
          paymentInfo: {
            numberOfInstallments: 6,
            paidInstallments: 3,
            paymentOption: 'installment',
            paymentMethod: 'bank_transfer',
            paymentDate: '2024-11-15',
            paymentAmount: 2000,
            paymentStatus: 'Paid',
          },
        },
        {
          orderItemHumanId: 'L9922078-3',
          matterOfConnection: 'national_id',
          carInfo: {
            year: '2022',
            brand: 'Mazda',
            carModel: 'CX-5',
            licensePlate: 'คง-9012',
          },
          packageInfo: {
            insuranceType: 'First Class',
            expirationDate: '2026-03-15',
            premiumAmount: '19500',
            sumInsured: '650000',
          },
          insurerInfo: {
            insurerName: 'insurers/7',
            shortNameEn: 'ABC',
            shortNameTh: 'เอบีซี',
            phone: '02-123-4567',
            website: 'https://abc-insurance.com',
          },
          paymentInfo: {
            numberOfInstallments: 12,
            paidInstallments: 8,
            paymentOption: 'installment',
            paymentMethod: 'credit_card',
            paymentDate: '2024-11-20',
            paymentAmount: 1625,
            paymentStatus: 'Paid',
          },
        },
        {
          orderItemHumanId: 'L9922078-4',
          matterOfConnection: 'national_id',
          carInfo: {
            year: '2020',
            brand: 'Nissan',
            carModel: 'Almera',
            licensePlate: 'งจ-3456',
          },
          packageInfo: {
            insuranceType: 'Third Class',
            expirationDate: '2025-08-30',
            premiumAmount: '8500',
            sumInsured: '250000',
          },
          insurerInfo: {
            insurerName: 'insurers/7',
            shortNameEn: 'ABC',
            shortNameTh: 'เอบีซี',
            phone: '02-123-4567',
            website: 'https://abc-insurance.com',
          },
          paymentInfo: {
            numberOfInstallments: 1,
            paidInstallments: 1,
            paymentOption: 'full',
            paymentMethod: 'bank_transfer',
            paymentDate: '2024-08-30',
            paymentAmount: 8500,
            paymentStatus: 'Paid',
          },
        },
        {
          orderItemHumanId: 'L9922078-5',
          matterOfConnection: 'phone_number',
          carInfo: {
            year: '2019',
            brand: 'Mitsubishi',
            carModel: 'Pajero Sport',
            licensePlate: 'ฉช-7890',
          },
          packageInfo: {
            insuranceType: 'Second Class',
            expirationDate: '2025-10-15',
            premiumAmount: '14500',
            sumInsured: '450000',
          },
          insurerInfo: {
            insurerName: 'insurers/7',
            shortNameEn: 'ABC',
            shortNameTh: 'เอบีซี',
            phone: '02-123-4567',
            website: 'https://abc-insurance.com',
          },
          paymentInfo: {
            numberOfInstallments: 4,
            paidInstallments: 2,
            paymentOption: 'installment',
            paymentMethod: 'credit_card',
            paymentDate: '2024-10-15',
            paymentAmount: 3625,
            paymentStatus: 'Paid',
          },
        },
      ],
    },
    {
      product: 'products/health-insurance',
      productLabel: 'Health Insurance',
      policies: [
        {
          orderItemHumanId: 'H5523101-3',
          matterOfConnection: 'national_id',
          healthInfo: {
            planName: 'Rabbit Care Health Protect',
            beneficiaryName: 'Somchai Jaidee',
            beneficiaryRelationship: 'Mom',
            orderCancellationStatus: true,
            orderCancellationReason:
              'Customer requested cancellation due to personal reasons.',
            orderCancellationDate: '2023-01-01',
          },
          packageInfo: {
            insuranceType: 'Standard Health Plan',
            expirationDate: '2025-12-31',
            premiumAmount: '8500',
            sumInsured: '300000',
          },
          insurerInfo: {
            insurerName: 'insurers/3',
            shortNameEn: 'HealthPlus',
            shortNameTh: 'เฮลท์พลัส',
            phone: '02-888-9999',
            website: 'https://healthplus.co.th',
          },
          paymentInfo: {
            numberOfInstallments: 1,
            paidInstallments: 1,
            paymentOption: 'full',
            paymentMethod: 'bank_transfer',
            paymentDate: '2024-08-15',
            paymentAmount: 8500,
            paymentStatus: 'Paid',
          },
          leadInfo: {
            lead: {
              id: 'leads/987654',
              firstName: 'Suda',
              lastName: 'Wong',
            },
            source: {
              channel: 'Google',
              campaign: 'Health Plan A',
            },
          },
        },
      ],
    },
  ],
};
