import { PerformanceStatsResponse } from 'data/slices/performanceStatisticSlice/types';

export const mockCallStats = {
  stats: [
    {
      user: 'users/f6e41647-8cfc-4a21-9239-bc1a255f54dc',
      userFullName: 'John Farmer',
      team: 'teams/4809ce56-978b-4eb1-8d76-0a13e32378af',
      presence: {
        updateTime: null,
        status: 'STATUS_CALL',
        interactTime: '2025-12-01T03:40:51.853080057Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 50,
      hourlyStats: {
        callAttempts: 30,
        callsSuccessful: 10,
        talkTimeSeconds: 500,
        averageTimePerSuccessfulCallSeconds: 50,
        followupsAttempts: 10,
        followupsSuccessful: 10,
      },
      numberOfLeadsRejected: 20,
      numberOfLeadsContacted: 30,
      numberOfLeadsNoAnswer: 10,
      numberOfFollowUpsSet: 20,
      numberOfLeadsPendingPayment: 5,
      numberOfLeadsInterested: 10,
      activeCall: {
        call: 'calls/28449900-ec3a-44d1-856d-9ca03d8a5843',
        lead: 'leads/7ff2e30c-9de1-4ebf-9c50-a1d02d2542bd',
        startTime: '2025-12-01T03:30:51.853080727Z',
      },
    },
    {
      user: 'users/f6e41647-8cfc-4a21-9239-bc1a255f54dc',
      userFullName: 'Not Null',
      team: 'teams/4809ce56-978b-4eb1-8d76-0a13e32378af',
      presence: {
        updateTime: null,
        status: 'STATUS_AWAY',
        interactTime: null,
        awayReason: '',
      },
      numberOfLeadsInTank: 50,
      hourlyStats: {
        callAttempts: 0,
        callsSuccessful: 0,
        talkTimeSeconds: 0,
        averageTimePerSuccessfulCallSeconds: 0,
        followupsAttempts: 0,
        followupsSuccessful: 0,
      },
      numberOfLeadsRejected: 25,
      numberOfLeadsContacted: 35,
      numberOfLeadsNoAnswer: 15,
      numberOfFollowUpsSet: 10,
      numberOfLeadsPendingPayment: 10,
      numberOfLeadsInterested: 10,
      activeCall: null,
    },
    {
      user: 'users/001',
      userFullName: 'Alex Carter',
      team: 'teams/alpha',
      presence: {
        updateTime: '2025-12-01T05:01:11Z',
        status: 'STATUS_ONLINE',
        interactTime: '2025-12-01T05:00:50Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 45,
      hourlyStats: {
        callAttempts: 32,
        callsSuccessful: 12,
        talkTimeSeconds: 620,
        averageTimePerSuccessfulCallSeconds: 51,
        followupsAttempts: 14,
        followupsSuccessful: 9,
      },
      numberOfLeadsRejected: 12,
      numberOfLeadsContacted: 35,
      numberOfLeadsNoAnswer: 10,
      numberOfFollowUpsSet: 18,
      numberOfLeadsPendingPayment: 6,
      numberOfLeadsInterested: 14,
      activeCall: null,
    },
    {
      user: 'users/002',
      userFullName: 'Maria Lopez',
      team: 'teams/alpha',
      presence: {
        updateTime: '2025-12-01T05:02:10Z',
        status: 'STATUS_CALL',
        interactTime: '2025-12-01T05:02:10Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 52,
      hourlyStats: {
        callAttempts: 40,
        callsSuccessful: 18,
        talkTimeSeconds: 1200,
        averageTimePerSuccessfulCallSeconds: 66,
        followupsAttempts: 20,
        followupsSuccessful: 18,
      },
      numberOfLeadsRejected: 20,
      numberOfLeadsContacted: 38,
      numberOfLeadsNoAnswer: 8,
      numberOfFollowUpsSet: 22,
      numberOfLeadsPendingPayment: 10,
      numberOfLeadsInterested: 18,
      activeCall: {
        call: 'calls/call002',
        lead: 'leads/lead002',
        startTime: '2025-12-01T04:59:10Z',
      },
    },
    {
      user: 'users/003',
      userFullName: 'David Kim',
      team: 'teams/beta',
      presence: {
        updateTime: '2025-12-01T04:55:05Z',
        status: 'STATUS_AWAY',
        interactTime: null,
        awayReason: 'break',
      },
      numberOfLeadsInTank: 60,
      hourlyStats: {
        callAttempts: 0,
        callsSuccessful: 0,
        talkTimeSeconds: 0,
        averageTimePerSuccessfulCallSeconds: 0,
        followupsAttempts: 0,
        followupsSuccessful: 0,
      },
      numberOfLeadsRejected: 30,
      numberOfLeadsContacted: 20,
      numberOfLeadsNoAnswer: 20,
      numberOfFollowUpsSet: 5,
      numberOfLeadsPendingPayment: 2,
      numberOfLeadsInterested: 3,
      activeCall: null,
    },
    {
      user: 'users/004',
      userFullName: 'Sophia Lee',
      team: 'teams/beta',
      presence: {
        updateTime: '2025-12-01T05:03:22Z',
        status: 'STATUS_ONLINE',
        interactTime: '2025-12-01T05:03:01Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 40,
      hourlyStats: {
        callAttempts: 22,
        callsSuccessful: 8,
        talkTimeSeconds: 300,
        averageTimePerSuccessfulCallSeconds: 37,
        followupsAttempts: 8,
        followupsSuccessful: 6,
      },
      numberOfLeadsRejected: 10,
      numberOfLeadsContacted: 24,
      numberOfLeadsNoAnswer: 12,
      numberOfFollowUpsSet: 12,
      numberOfLeadsPendingPayment: 5,
      numberOfLeadsInterested: 7,
      activeCall: null,
    },
    {
      user: 'users/005',
      userFullName: 'Emma Chan',
      team: 'teams/alpha',
      presence: {
        updateTime: '2025-12-01T05:05:10Z',
        status: 'STATUS_CALL',
        interactTime: '2025-12-01T05:05:10Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 48,
      hourlyStats: {
        callAttempts: 35,
        callsSuccessful: 16,
        talkTimeSeconds: 900,
        averageTimePerSuccessfulCallSeconds: 56,
        followupsAttempts: 15,
        followupsSuccessful: 14,
      },
      numberOfLeadsRejected: 18,
      numberOfLeadsContacted: 32,
      numberOfLeadsNoAnswer: 9,
      numberOfFollowUpsSet: 19,
      numberOfLeadsPendingPayment: 7,
      numberOfLeadsInterested: 16,
      activeCall: {
        call: 'calls/call005',
        lead: 'leads/lead005',
        startTime: '2025-12-01T05:02:02Z',
      },
    },
    {
      user: 'users/006',
      userFullName: 'Liam Johnson',
      team: 'teams/gamma',
      presence: {
        updateTime: '2025-12-01T05:06:00Z',
        status: 'STATUS_ONLINE',
        interactTime: '2025-12-01T05:05:50Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 55,
      hourlyStats: {
        callAttempts: 28,
        callsSuccessful: 14,
        talkTimeSeconds: 700,
        averageTimePerSuccessfulCallSeconds: 50,
        followupsAttempts: 12,
        followupsSuccessful: 10,
      },
      numberOfLeadsRejected: 15,
      numberOfLeadsContacted: 40,
      numberOfLeadsNoAnswer: 5,
      numberOfFollowUpsSet: 14,
      numberOfLeadsPendingPayment: 4,
      numberOfLeadsInterested: 12,
      activeCall: null,
    },
    {
      user: 'users/007',
      userFullName: 'Olivia Martinez',
      team: 'teams/gamma',
      presence: {
        updateTime: '2025-12-01T05:07:12Z',
        status: 'STATUS_CALL',
        interactTime: '2025-12-01T05:07:10Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 60,
      hourlyStats: {
        callAttempts: 50,
        callsSuccessful: 25,
        talkTimeSeconds: 1500,
        averageTimePerSuccessfulCallSeconds: 60,
        followupsAttempts: 20,
        followupsSuccessful: 18,
      },
      numberOfLeadsRejected: 22,
      numberOfLeadsContacted: 45,
      numberOfLeadsNoAnswer: 10,
      numberOfFollowUpsSet: 20,
      numberOfLeadsPendingPayment: 12,
      numberOfLeadsInterested: 18,
      activeCall: {
        call: 'calls/call007',
        lead: 'leads/lead007',
        startTime: '2025-12-01T05:05:00Z',
      },
    },
    {
      user: 'users/008',
      userFullName: 'Noah Smith',
      team: 'teams/delta',
      presence: {
        updateTime: '2025-12-01T05:08:15Z',
        status: 'STATUS_AWAY',
        interactTime: null,
        awayReason: 'lunch',
      },
      numberOfLeadsInTank: 42,
      hourlyStats: {
        callAttempts: 0,
        callsSuccessful: 0,
        talkTimeSeconds: 0,
        averageTimePerSuccessfulCallSeconds: 0,
        followupsAttempts: 0,
        followupsSuccessful: 0,
      },
      numberOfLeadsRejected: 18,
      numberOfLeadsContacted: 20,
      numberOfLeadsNoAnswer: 10,
      numberOfFollowUpsSet: 6,
      numberOfLeadsPendingPayment: 3,
      numberOfLeadsInterested: 5,
      activeCall: null,
    },
    {
      user: 'users/009',
      userFullName: 'Ava Brown',
      team: 'teams/delta',
      presence: {
        updateTime: '2025-12-01T05:09:20Z',
        status: 'STATUS_ONLINE',
        interactTime: '2025-12-01T05:09:00Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 47,
      hourlyStats: {
        callAttempts: 26,
        callsSuccessful: 12,
        talkTimeSeconds: 600,
        averageTimePerSuccessfulCallSeconds: 50,
        followupsAttempts: 12,
        followupsSuccessful: 10,
      },
      numberOfLeadsRejected: 14,
      numberOfLeadsContacted: 32,
      numberOfLeadsNoAnswer: 10,
      numberOfFollowUpsSet: 13,
      numberOfLeadsPendingPayment: 5,
      numberOfLeadsInterested: 11,
      activeCall: null,
    },
    {
      user: 'users/010',
      userFullName: 'Ethan Wilson',
      team: 'teams/epsilon',
      presence: {
        updateTime: '2025-12-01T05:10:10Z',
        status: 'STATUS_CALL',
        interactTime: '2025-12-01T05:10:05Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 53,
      hourlyStats: {
        callAttempts: 45,
        callsSuccessful: 22,
        talkTimeSeconds: 1320,
        averageTimePerSuccessfulCallSeconds: 60,
        followupsAttempts: 18,
        followupsSuccessful: 16,
      },
      numberOfLeadsRejected: 20,
      numberOfLeadsContacted: 40,
      numberOfLeadsNoAnswer: 8,
      numberOfFollowUpsSet: 18,
      numberOfLeadsPendingPayment: 10,
      numberOfLeadsInterested: 18,
      activeCall: {
        call: 'calls/call010',
        lead: 'leads/lead010',
        startTime: '2025-12-01T05:08:10Z',
      },
    },

    ////////////////////////
    // Items 11–30 follow the same pattern
    ////////////////////////

    {
      user: 'users/011',
      userFullName: 'Mia Davis',
      team: 'teams/epsilon',
      presence: {
        updateTime: '2025-12-01T05:11:00Z',
        status: 'STATUS_ONLINE',
        interactTime: '2025-12-01T05:00:55Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 44,
      hourlyStats: {
        callAttempts: 20,
        callsSuccessful: 10,
        talkTimeSeconds: 400,
        averageTimePerSuccessfulCallSeconds: 40,
        followupsAttempts: 8,
        followupsSuccessful: 7,
      },
      numberOfLeadsRejected: 12,
      numberOfLeadsContacted: 28,
      numberOfLeadsNoAnswer: 6,
      numberOfFollowUpsSet: 12,
      numberOfLeadsPendingPayment: 5,
      numberOfLeadsInterested: 10,
      activeCall: null,
    },

    {
      user: 'users/012',
      userFullName: 'Lucas Taylor',
      team: 'teams/zeta',
      presence: {
        updateTime: '2025-12-01T05:12:05Z',
        status: 'STATUS_CALL',
        interactTime: '2025-12-01T05:12:00Z',
        awayReason: '',
      },
      numberOfLeadsInTank: 58,
      hourlyStats: {
        callAttempts: 48,
        callsSuccessful: 24,
        talkTimeSeconds: 1440,
        averageTimePerSuccessfulCallSeconds: 60,
        followupsAttempts: 22,
        followupsSuccessful: 20,
      },
      numberOfLeadsRejected: 18,
      numberOfLeadsContacted: 45,
      numberOfLeadsNoAnswer: 9,
      numberOfFollowUpsSet: 21,
      numberOfLeadsPendingPayment: 12,
      numberOfLeadsInterested: 19,
      activeCall: {
        call: 'calls/call012',
        lead: 'leads/lead012',
        startTime: '2025-12-01T05:10:00Z',
      },
    },
  ],
  nextPageToken: '',
} as PerformanceStatsResponse;
