const CarApiSubModelResponse = {
  manufacturedYears: [2020],
  uniqueBrands: [
    {
      id: 24,
      name: 'Honda',
    },
  ],
  uniqueModels: [
    {
      id: 183,
      name: 'City',
    },
  ],
  car: [
    {
      name: 'brands/24/models/183/submodels/12233/years/46440',
      year: 2020,
      submodelName: 'V',
      engineSize: 1000,
      engineDescription: 0,
      transmissionType: '',
      cabType: '',
      doors: 4,
      sumInsuredMin: 0,
      sumInsuredMax: 0,
      fuelType: '',
      month: 0,
      migratedAsCurated: true,
      price: '0',
      displayName: '1000 CC (4 Doors) V ',
      isEnabled: true,
      isCurated: true,
      isVan: false,
    },
    {
      name: 'brands/24/models/183/submodels/12234/years/46441',
      year: 2020,
      submodelName: 'SV',
      engineSize: 1000,
      engineDescription: 0,
      transmissionType: '',
      cabType: '',
      doors: 4,
      sumInsuredMin: 0,
      sumInsuredMax: 0,
      fuelType: '',
      month: 0,
      migratedAsCurated: true,
      price: '0',
      displayName: '1000 CC (4 Doors) SV ',
      isEnabled: true,
      isCurated: true,
      isVan: false,
    },
    {
      name: 'brands/24/models/183/submodels/12235/years/46442',
      year: 2020,
      submodelName: 'S',
      engineSize: 1000,
      engineDescription: 0,
      transmissionType: '',
      cabType: '',
      doors: 4,
      sumInsuredMin: 0,
      sumInsuredMax: 0,
      fuelType: '',
      month: 0,
      migratedAsCurated: true,
      price: '0',
      displayName: '1000 CC (4 Doors) S ',
      isEnabled: true,
      isCurated: true,
      isVan: false,
    },
    {
      name: 'brands/24/models/183/submodels/12236/years/46443',
      year: 2020,
      submodelName: 'RS',
      engineSize: 1000,
      engineDescription: 0,
      transmissionType: '',
      cabType: '',
      doors: 4,
      sumInsuredMin: 0,
      sumInsuredMax: 0,
      fuelType: '',
      month: 0,
      migratedAsCurated: true,
      price: '0',
      displayName: '1000 CC (4 Doors) RS ',
      isEnabled: true,
      isCurated: true,
      isVan: false,
    },
    {
      name: 'brands/24/models/183/submodels/12237/years/46444',
      year: 2020,
      submodelName: 'e:HEV RS (HYBRID)',
      engineSize: 1500,
      engineDescription: 0,
      transmissionType: '',
      cabType: '',
      doors: 4,
      sumInsuredMin: 0,
      sumInsuredMax: 0,
      fuelType: '',
      month: 0,
      migratedAsCurated: true,
      price: '0',
      displayName: '1500 CC (4 Doors) e:HEV RS (HYBRID) ',
      isEnabled: true,
      isCurated: true,
      isVan: false,
    },
  ],
};

export default CarApiSubModelResponse;
