import {
  CustomPackage,
  PackageGroup,
} from 'presentation/pages/car-insurance/PackageListingPageNew/types';

export const mockPackageGroups: PackageGroup[] = [
  {
    name: 'Bangkok Insurance',
    insuranceCompany: {
      name: 'Bangkok Insurance Public Company Limited',
      displayName: 'Bangkok Insurance',
      logo: 'https://storage.googleapis.com/skillful-rush/insurers/7.png',
    },
    carCoverageRange: { min: 100000, max: 150000, highlighted: 100000 },
    priceRange: { min: 17845.21, max: 28245.21, highlighted: 17845.21 },
    total: 4,
    packages: [
      {
        id: '1',
        uploadPackageName: 'Bangkok Insurance',
        packageName: 'Type 1_Standard_Garage_Mazda3_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 1',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Mazda 3 2024 SP',
        carCoverage: 100000,
        deductible: 0,
        price: 17845.21,
        insuranceCompany: 'Bangkok Insurance Public Company Limited',
        insuranceCompanyData: {
          name: 'Bangkok Insurance Public Company Limited',
          displayName: 'Bangkok Insurance',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/7.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'BKK_001',
        startDate: new Date('2024-01-01'),
        expiryDate: new Date('2025-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 17845.21,
        coverageDetails: {
          ownCarDamage: 100000,
          personalInjury: 150000,
          medicalExpense: 150000,
          bailBond: 150000,
          propertyDamage: 3000000,
          deathPerPerson: 800000,
          maximumDeath: 8000000,
          floodCoverage: 100000,
          theftAndFireCoverage: 100000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Standard coverage with garage repair option. Includes roadside assistance and 24/7 customer support.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
      {
        id: '2',
        uploadPackageName: 'Bangkok Insurance Public Company Limited',
        packageName:
          'Type 2_Premium_Garage_HondaCivic_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 2',
        insuranceCategory: 'voluntary',
        repairType: 'Garage',
        subModel: 'Honda Civic 2024 EX',
        carCoverage: 120000,
        deductible: 0,
        price: 19845.21,
        insuranceCompany: 'Bangkok Insurance Public Company Limited',
        insuranceCompanyData: {
          name: 'Bangkok Insurance Public Company Limited',
          displayName: 'Bangkok Insurance',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/7.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'BKK_002',
        startDate: new Date('2024-01-01'),
        expiryDate: new Date('2025-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 19845.21,
        coverageDetails: {
          ownCarDamage: 120000,
          personalInjury: 180000,
          medicalExpense: 180000,
          bailBond: 180000,
          propertyDamage: 3500000,
          deathPerPerson: 1000000,
          maximumDeath: 10000000,
          floodCoverage: 120000,
          theftAndFireCoverage: 120000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Premium coverage with garage repair option. Includes roadside assistance, 24/7 customer support, and additional benefits.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
      {
        id: '3',
        uploadPackageName: 'Bangkok Insurance Public Company Limited',
        packageName:
          'Type 3_Basic_Garage_ToyotaCorolla_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 3',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Toyota Corolla 2024 LE',
        carCoverage: 80000,
        deductible: 0,
        price: 15845.21,
        insuranceCompany: 'Bangkok Insurance Public Company Limited',
        insuranceCompanyData: {
          name: 'Bangkok Insurance Public Company Limited',
          displayName: 'Bangkok Insurance',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/7.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'BKK_003',
        startDate: new Date('2024-01-01'),
        expiryDate: new Date('2025-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 15845.21,
        coverageDetails: {
          ownCarDamage: 80000,
          personalInjury: 100000,
          medicalExpense: 100000,
          bailBond: 100000,
          propertyDamage: 2500000,
          deathPerPerson: 600000,
          maximumDeath: 6000000,
          floodCoverage: 80000,
          theftAndFireCoverage: 80000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Basic coverage with garage repair option. Includes roadside assistance and 24/7 customer support.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
      {
        id: '4',
        uploadPackageName: 'Bangkok Insurance Public Company Limited',
        packageName:
          'Type 4_Premium_Garage_NissanAltima_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 4',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Nissan Altima 2024 SV',
        carCoverage: 150000,
        deductible: 0,
        price: 21845.21,
        insuranceCompany: 'Bangkok Insurance Public Company Limited',
        insuranceCompanyData: {
          name: 'Bangkok Insurance Public Company Limited',
          displayName: 'Bangkok Insurance',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/7.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'BKK_004',
        startDate: new Date('2024-01-01'),
        expiryDate: new Date('2025-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 21845.21,
        coverageDetails: {
          ownCarDamage: 150000,
          personalInjury: 200000,
          medicalExpense: 200000,
          bailBond: 200000,
          propertyDamage: 4000000,
          deathPerPerson: 1200000,
          maximumDeath: 12000000,
          floodCoverage: 150000,
          theftAndFireCoverage: 150000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Premium coverage with garage repair option. Includes roadside assistance, 24/7 customer support, and additional benefits.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
    ],
  },
  {
    name: 'Viriyah Insurance',
    insuranceCompany: {
      name: 'The Viriyah Insurance Company Limited',
      displayName: 'The Viriyah Insurance Company Limited',
      logo: 'https://storage.googleapis.com/skillful-rush/insurers/27.png',
    },
    carCoverageRange: { min: 150000, max: 500000, highlighted: 500000 },
    priceRange: { min: 17000, max: 19000, highlighted: 19000 },
    total: 6,
    packages: [
      {
        id: '5',
        uploadPackageName: 'The Viriyah Insurance Company Limited',
        packageName:
          'Type 1_OIC 110_STD_garage_Ford/Honda/Kia/Mitsubishi/Nissan/Suzuki/Toyota_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 1',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Mazda 3 2024 SP',
        carCoverage: 500000,
        deductible: 0,
        price: 19000,
        insuranceCompany: 'The Viriyah Insurance Company Limited',
        insuranceCompanyData: {
          name: 'The Viriyah Insurance Company Limited',
          displayName: 'The Viriyah Insurance Company Limited',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/27.png',
        },
        includeDashCamDiscount: false,
        oicCode: 'TYPE_110',
        startDate: new Date('2022-01-06'),
        expiryDate: new Date('9999-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 19000,
        coverageDetails: {
          ownCarDamage: 500000,
          personalInjury: 300000,
          medicalExpense: 300000,
          bailBond: 300000,
          propertyDamage: 8000000,
          deathPerPerson: 1500000,
          maximumDeath: 15000000,
          floodCoverage: 500000,
          theftAndFireCoverage: 500000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Premium rates already include discounts on the installation of closed circuit television (CCTV) and applications for reporting a car accident. **OIC 110 only',
        applicableProvinces: [
          'Amnat Charoen',
          'Ang Thong',
          'Bangkok',
          'Bueng Kan',
          'Buri Ram',
          'Chachoengsao',
          'Chai Nat',
          'Chaiyaphum',
          'Chanthaburi',
          'Chiang Mai',
          'Chiang Rai',
          'Chon Buri',
          'Chumphon',
          'Kalasin',
          'Kamphaeng Phet',
          'Kanchanaburi',
          'Khon Kaen',
          'Krabi',
          'Lampang',
          'Lamphun',
          'Loei',
          'Lop Buri',
          'Mae Hong Son',
          'Maha Sarakham',
          'Mukdahan',
          'Nakhon Nayok',
          'Nakhon Pathom',
          'Nakhon Phanom',
          'Nakhon Ratchasima',
          'Nakhon Sawan',
          'Nakhon Si Thammarat',
          'Nan',
          'Narathiwat',
          'Nong Bua Lam Phu',
          'Nong Khai',
          'Nonthaburi',
          'Pathum Thani',
          'Pattani',
          'Phangnga',
          'Phatthalung',
          'Phayao',
          'Phetchabun',
          'Phetchaburi',
          'Phichit',
          'Phitsanulok',
          'Phrae',
          'Phra Nakhon Si Ayutthaya',
          'Phuket',
          'Prachin Buri',
          'Prachuap Khiri Khan',
          'Ranong',
          'Ratchaburi',
          'Rayong',
          'Roi Et',
          'Sa Kaeo',
          'Sakon Nakhon',
          'Samut Prakan',
          'Samut Sakhon',
          'Samut Songkhram',
          'Saraburi',
          'Satun',
          'Sing Buri',
          'Si Sa Ket',
          'Songkhla',
          'Sukhothai',
          'Suphan Buri',
          'Surat Thani',
          'Surin',
          'Tak',
          'Trang',
          'Trat',
          'Ubon Ratchathani',
          'Udon Thani',
          'Uthai Thani',
          'Uttaradit',
          'Yala',
          'Yasothon',
        ],
      },
      {
        id: '6',
        uploadPackageName: 'The Viriyah Insurance Company Limited',
        packageName:
          'Type 2_Premium_Garage_Honda_Civic_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 2',
        insuranceCategory: 'voluntary',
        repairType: 'Garage',
        subModel: 'Honda Civic 2024 EX',
        carCoverage: 400000,
        deductible: 0,
        price: 18000,
        insuranceCompany: 'The Viriyah Insurance Company Limited',
        insuranceCompanyData: {
          name: 'The Viriyah Insurance Company Limited',
          displayName: 'The Viriyah Insurance Company Limited',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/27.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'TYPE_210',
        startDate: new Date('2023-01-01'),
        expiryDate: new Date('2024-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 18000,
        coverageDetails: {
          ownCarDamage: 400000,
          personalInjury: 250000,
          medicalExpense: 250000,
          bailBond: 250000,
          propertyDamage: 7000000,
          deathPerPerson: 1200000,
          maximumDeath: 12000000,
          floodCoverage: 400000,
          theftAndFireCoverage: 400000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Premium coverage with garage repair option. Includes roadside assistance, 24/7 customer support, and additional benefits.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
      {
        id: '7',
        uploadPackageName: 'The Viriyah Insurance Company Limited',
        packageName:
          'Type 3_Standard_Garage_Toyota_Corolla_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 3',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Toyota Corolla 2024 LE',
        carCoverage: 300000,
        deductible: 0,
        price: 17000,
        insuranceCompany: 'The Viriyah Insurance Company Limited',
        insuranceCompanyData: {
          name: 'The Viriyah Insurance Company Limited',
          displayName: 'The Viriyah Insurance Company Limited',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/27.png',
        },
        includeDashCamDiscount: false,
        oicCode: 'TYPE_310',
        startDate: new Date('2022-01-01'),
        expiryDate: new Date('2023-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 17000,
        coverageDetails: {
          ownCarDamage: 300000,
          personalInjury: 200000,
          medicalExpense: 200000,
          bailBond: 200000,
          propertyDamage: 6000000,
          deathPerPerson: 1000000,
          maximumDeath: 10000000,
          floodCoverage: 300000,
          theftAndFireCoverage: 300000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Standard coverage with garage repair option. Includes basic protection and limited benefits.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
      {
        id: '8',
        uploadPackageName: 'The Viriyah Insurance Company Limited',
        packageName:
          'Type 4_Premium_Garage_NissanAltima_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 4',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Nissan Altima 2024 SV',
        carCoverage: 250000,
        deductible: 0,
        price: 16000,
        insuranceCompany: 'The Viriyah Insurance Company Limited',
        insuranceCompanyData: {
          name: 'The Viriyah Insurance Company Limited',
          displayName: 'The Viriyah Insurance Company Limited',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/27.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'TYPE_410',
        startDate: new Date('2023-01-01'),
        expiryDate: new Date('2024-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 16000,
        coverageDetails: {
          ownCarDamage: 250000,
          personalInjury: 150000,
          medicalExpense: 150000,
          bailBond: 150000,
          propertyDamage: 5000000,
          deathPerPerson: 800000,
          maximumDeath: 8000000,
          floodCoverage: 250000,
          theftAndFireCoverage: 250000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Premium coverage with garage repair option. Includes roadside assistance, 24/7 customer support, and additional benefits.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
      {
        id: '9',
        uploadPackageName: 'The Viriyah Insurance Company Limited',
        packageName:
          'Type 5_Basic_Garage_Ford_Focus_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 5',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Ford Focus 2024 SE',
        carCoverage: 200000,
        deductible: 0,
        price: 15000,
        insuranceCompany: 'The Viriyah Insurance Company Limited',
        insuranceCompanyData: {
          name: 'The Viriyah Insurance Company Limited',
          displayName: 'The Viriyah Insurance Company Limited',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/27.png',
        },
        includeDashCamDiscount: false,
        oicCode: 'TYPE_510',
        startDate: new Date('2022-01-01'),
        expiryDate: new Date('2023-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 15000,
        coverageDetails: {
          ownCarDamage: 200000,
          personalInjury: 100000,
          medicalExpense: 100000,
          bailBond: 100000,
          propertyDamage: 4000000,
          deathPerPerson: 600000,
          maximumDeath: 6000000,
          floodCoverage: 200000,
          theftAndFireCoverage: 200000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Basic coverage with garage repair option. Includes minimal protection and limited benefits.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
      {
        id: '10',
        uploadPackageName: 'The Viriyah Insurance Company Limited',
        packageName:
          'Type 6_Premium_Garage_Hyundai_Elantra_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 6',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Hyundai Elantra 2024 SEL',
        carCoverage: 350000,
        deductible: 0,
        price: 16500,
        insuranceCompany: 'The Viriyah Insurance Company Limited',
        insuranceCompanyData: {
          name: 'The Viriyah Insurance Company Limited',
          displayName: 'The Viriyah Insurance Company Limited',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/27.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'TYPE_610',
        startDate: new Date('2023-01-01'),
        expiryDate: new Date('2024-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 16500,
        coverageDetails: {
          ownCarDamage: 350000,
          personalInjury: 220000,
          medicalExpense: 220000,
          bailBond: 220000,
          propertyDamage: 6500000,
          deathPerPerson: 1100000,
          maximumDeath: 11000000,
          floodCoverage: 350000,
          theftAndFireCoverage: 350000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Premium coverage with garage repair option. Includes roadside assistance, 24/7 customer support, and additional benefits.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
      {
        id: '11',
        uploadPackageName: 'The Viriyah Insurance Company Limited',
        packageName:
          'Type 7_Standard_Garage_Kia_Forte_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 7',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Kia Forte 2024 LX',
        carCoverage: 250000,
        deductible: 0,
        price: 15500,
        insuranceCompany: 'The Viriyah Insurance Company Limited',
        insuranceCompanyData: {
          name: 'The Viriyah Insurance Company Limited',
          displayName: 'The Viriyah Insurance Company Limited',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/27.png',
        },
        includeDashCamDiscount: false,
        oicCode: 'TYPE_710',
        startDate: new Date('2022-01-01'),
        expiryDate: new Date('2023-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 15500,
        coverageDetails: {
          ownCarDamage: 250000,
          personalInjury: 180000,
          medicalExpense: 180000,
          bailBond: 180000,
          propertyDamage: 5500000,
          deathPerPerson: 900000,
          maximumDeath: 9000000,
          floodCoverage: 250000,
          theftAndFireCoverage: 250000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Standard coverage with garage repair option. Includes basic protection and limited benefits.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
      {
        id: '12',
        uploadPackageName: 'The Viriyah Insurance Company Limited',
        packageName: 'Type 8_Basic_Garage_Mazda3_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 8',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Mazda 3 2024 SP',
        carCoverage: 150000,
        deductible: 0,
        price: 14000,
        insuranceCompany: 'The Viriyah Insurance Company Limited',
        insuranceCompanyData: {
          name: 'The Viriyah Insurance Company Limited',
          displayName: 'The Viriyah Insurance Company Limited',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/27.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'TYPE_810',
        startDate: new Date('2023-01-01'),
        expiryDate: new Date('2024-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 14000,
        coverageDetails: {
          ownCarDamage: 150000,
          personalInjury: 120000,
          medicalExpense: 120000,
          bailBond: 120000,
          propertyDamage: 4000000,
          deathPerPerson: 700000,
          maximumDeath: 7000000,
          floodCoverage: 150000,
          theftAndFireCoverage: 150000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Basic coverage with garage repair option. Includes minimal protection and limited benefits.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
        ],
      },
    ],
  },
  {
    name: 'ERGO Insurance',
    insuranceCompany: {
      name: 'ERGO Insurance Thailand',
      displayName: 'ERGO Insurance',
      logo: 'https://storage.googleapis.com/skillful-rush/insurers/1.png',
    },
    carCoverageRange: { min: 120000, max: 600000, highlighted: 500000 },
    priceRange: { min: 17000, max: 18000, highlighted: 17500 },
    total: 1,
    packages: [
      {
        id: '13',
        uploadPackageName: 'ERGO Insurance Thailand',
        packageName: 'Type 1_Premium_Garage_Mazda3_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 1',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Mazda 3 2024 SP',
        carCoverage: 500000,
        deductible: 0,
        price: 17500,
        insuranceCompany: 'ERGO Insurance Thailand',
        insuranceCompanyData: {
          name: 'ERGO Insurance Thailand',
          displayName: 'ERGO Insurance',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/1.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'ERGO_001',
        startDate: new Date('2024-01-01'),
        expiryDate: new Date('2025-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 17500,
        coverageDetails: {
          ownCarDamage: 500000,
          personalInjury: 250000,
          medicalExpense: 250000,
          bailBond: 250000,
          propertyDamage: 6000000,
          deathPerPerson: 1200000,
          maximumDeath: 12000000,
          floodCoverage: 500000,
          theftAndFireCoverage: 500000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Premium coverage with comprehensive protection. Includes free windshield replacement and emergency towing service.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
          'Chiang Mai',
          'Chiang Rai',
          'Phuket',
          'Songkhla',
          'Surat Thani',
        ],
      },
    ],
  },
  {
    name: 'Thanachart Insurance',
    insuranceCompany: {
      name: 'Thanachart Insurance Public Company Limited',
      displayName: 'Thanachart Insurance',
      logo: 'https://storage.googleapis.com/skillful-rush/insurers/2.png',
    },
    carCoverageRange: { min: 100000, max: 400000, highlighted: 300000 },
    priceRange: { min: 17200, max: 50700, highlighted: 18000 },
    total: 1,
    packages: [
      {
        id: '14',
        uploadPackageName: 'Thanachart Insurance Public Company Limited',
        packageName: 'Type 1_Standard_Garage_Mazda3_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 1',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Mazda 3 2024 SP',
        carCoverage: 300000,
        deductible: 0,
        price: 18000,
        insuranceCompany: 'Thanachart Insurance Public Company Limited',
        insuranceCompanyData: {
          name: 'Thanachart Insurance Public Company Limited',
          displayName: 'Thanachart Insurance',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/2.png',
        },
        includeDashCamDiscount: false,
        oicCode: 'TIS_001',
        startDate: new Date('2024-01-01'),
        expiryDate: new Date('2025-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 18000,
        coverageDetails: {
          ownCarDamage: 300000,
          personalInjury: 200000,
          medicalExpense: 200000,
          bailBond: 200000,
          propertyDamage: 4000000,
          deathPerPerson: 1000000,
          maximumDeath: 10000000,
          floodCoverage: 300000,
          theftAndFireCoverage: 300000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Standard coverage with competitive pricing. Includes 24/7 roadside assistance and claim support.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
          'Chiang Mai',
          'Chiang Rai',
          'Phuket',
          'Songkhla',
          'Surat Thani',
          'Khon Kaen',
          'Nakhon Ratchasima',
          'Udon Thani',
          'Ubon Ratchathani',
        ],
      },
    ],
  },
  {
    name: 'Southeast Insurance',
    insuranceCompany: {
      name: 'Southeast Insurance Public Company Limited',
      displayName: 'Southeast Insurance',
      logo: 'https://storage.googleapis.com/skillful-rush/insurers/3.png',
    },
    carCoverageRange: { min: 130000, max: 350000, highlighted: 250000 },
    priceRange: { min: 15835.21, max: 25000, highlighted: 16500 },
    total: 1,
    packages: [
      {
        id: '15',
        uploadPackageName: 'Southeast Insurance Public Company Limited',
        packageName: 'Type 1_Standard_Garage_Mazda3_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 1',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Mazda 3 2024 SP',
        carCoverage: 250000,
        deductible: 0,
        price: 16500,
        insuranceCompany: 'Southeast Insurance Public Company Limited',
        insuranceCompanyData: {
          name: 'Southeast Insurance Public Company Limited',
          displayName: 'Southeast Insurance',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/3.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'SEI_001',
        startDate: new Date('2024-01-01'),
        expiryDate: new Date('2025-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 16500,
        coverageDetails: {
          ownCarDamage: 250000,
          personalInjury: 180000,
          medicalExpense: 180000,
          bailBond: 180000,
          propertyDamage: 3500000,
          deathPerPerson: 900000,
          maximumDeath: 9000000,
          floodCoverage: 250000,
          theftAndFireCoverage: 250000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Affordable coverage with reliable protection. Includes free annual car inspection and maintenance reminders.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
          'Chiang Mai',
          'Chiang Rai',
          'Phuket',
          'Songkhla',
          'Surat Thani',
        ],
      },
    ],
  },
  {
    name: 'Dhipaya Insurance',
    insuranceCompany: {
      name: 'Dhipaya Insurance Public Company Limited',
      displayName: 'Dhipaya Insurance',
      logo: 'https://storage.googleapis.com/skillful-rush/insurers/4.png',
    },
    carCoverageRange: { min: 140000, max: 550000, highlighted: 450000 },
    priceRange: { min: 16200, max: 22000, highlighted: 17200 },
    total: 1,
    packages: [
      {
        id: '16',
        uploadPackageName: 'Dhipaya Insurance Public Company Limited',
        packageName: 'Type 1_Premium_Garage_Mazda3_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 1',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Mazda 3 2024 SP',
        carCoverage: 450000,
        deductible: 0,
        price: 17200,
        insuranceCompany: 'Dhipaya Insurance Public Company Limited',
        insuranceCompanyData: {
          name: 'Dhipaya Insurance Public Company Limited',
          displayName: 'Dhipaya Insurance',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/4.png',
        },
        includeDashCamDiscount: true,
        oicCode: 'DHI_001',
        startDate: new Date('2024-01-01'),
        expiryDate: new Date('2025-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 17200,
        coverageDetails: {
          ownCarDamage: 450000,
          personalInjury: 250000,
          medicalExpense: 250000,
          bailBond: 250000,
          propertyDamage: 7000000,
          deathPerPerson: 1200000,
          maximumDeath: 12000000,
          floodCoverage: 450000,
          theftAndFireCoverage: 450000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Premium coverage with comprehensive protection. Includes free car wash service and priority claim processing.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
          'Chiang Mai',
          'Chiang Rai',
          'Phuket',
          'Songkhla',
          'Surat Thani',
          'Khon Kaen',
          'Nakhon Ratchasima',
          'Udon Thani',
          'Ubon Ratchathani',
          'Nakhon Si Thammarat',
          'Hat Yai',
          'Pattaya',
        ],
      },
    ],
  },
  {
    name: 'LMG Insurance',
    insuranceCompany: {
      name: 'LMG Insurance Company Limited',
      displayName: 'LMG Insurance',
      logo: 'https://storage.googleapis.com/skillful-rush/insurers/5.png',
    },
    carCoverageRange: { min: 160000, max: 480000, highlighted: 350000 },
    priceRange: { min: 16800, max: 27500, highlighted: 18200 },
    total: 1,
    packages: [
      {
        id: '17',
        uploadPackageName: 'LMG Insurance Company Limited',
        packageName: 'Type 1_Standard_Garage_Mazda3_Group5_<2,000cc_6-10 years',
        insuranceType: 'Type 1',
        insuranceCategory: 'mandatory',
        repairType: 'Garage',
        subModel: 'Mazda 3 2024 SP',
        carCoverage: 350000,
        deductible: 0,
        price: 18200,
        insuranceCompany: 'LMG Insurance Company Limited',
        insuranceCompanyData: {
          name: 'LMG Insurance Company Limited',
          displayName: 'LMG Insurance',
          logo: 'https://storage.googleapis.com/skillful-rush/insurers/5.png',
        },
        includeDashCamDiscount: false,
        oicCode: 'LMG_001',
        startDate: new Date('2024-01-01'),
        expiryDate: new Date('2025-01-01'),
        mandatoryPricePerYear: 645.21,
        premium: 18200,
        coverageDetails: {
          ownCarDamage: 350000,
          personalInjury: 220000,
          medicalExpense: 220000,
          bailBond: 220000,
          propertyDamage: 5000000,
          deathPerPerson: 1100000,
          maximumDeath: 11000000,
          floodCoverage: 350000,
          theftAndFireCoverage: 350000,
          maximumAnnualCoverage: 12000,
        },
        termsAndConditions:
          'Reliable coverage with excellent customer service. Includes free emergency roadside assistance and claim support.',
        applicableProvinces: [
          'Bangkok',
          'Nonthaburi',
          'Pathum Thani',
          'Samut Prakan',
          'Samut Sakhon',
          'Nakhon Pathom',
          'Chon Buri',
          'Rayong',
          'Chachoengsao',
          'Prachin Buri',
          'Chiang Mai',
          'Chiang Rai',
          'Phuket',
          'Songkhla',
          'Surat Thani',
          'Khon Kaen',
          'Nakhon Ratchasima',
          'Udon Thani',
          'Ubon Ratchathani',
        ],
      },
    ],
  },
];

export const mockCustomPackages: CustomPackage[] = [
  {
    insurer: 'Bangkok Insurance',
    packageName: 'Type 1_OIC 110_Motor Gen X_garage_Group 5_1-10years',
    insuranceType: 'Type 1',
    insuranceCategory: 'mandatory',
    repairType: 'Garage',
    carCoverage: 150000,
    deductible: 0,
    price: 14845.21,
    paymentPlan: 'One time/ Credit/Debit Card',
    shippingFee: 0,
    discount: 0,
    processingFee: 148.45,
    invoiceAmount: 14993.66,
  },
  {
    insurer: 'Thanachart Insurance',
    packageName: 'Type 1_OIC 110_Motor Gen X_garage_Group 5_1-10years',
    insuranceType: 'Type 1',
    insuranceCategory: 'mandatory',
    repairType: 'Garage',
    carCoverage: 150000,
    deductible: 0,
    price: 0,
    paymentPlan: '',
    shippingFee: 0,
    discount: 0,
    processingFee: 0,
    invoiceAmount: 0,
  },
  {
    insurer: 'Southeast Insurance',
    packageName: 'Type 1_OIC 110_Motor Gen X_garage_Group 5_1-10years',
    insuranceType: 'Type 1',
    insuranceCategory: 'mandatory',
    repairType: 'Garage',
    carCoverage: 150000,
    deductible: 0,
    price: 0,
    paymentPlan: '',
    shippingFee: 0,
    discount: 0,
    processingFee: 0,
    invoiceAmount: 0,
  },
  {
    insurer: 'Dhipaya Insurance',
    packageName: 'Type 1_OIC 110_Motor Gen X_garage_Group 5_1-10years',
    insuranceType: 'Type 1',
    insuranceCategory: 'mandatory',
    repairType: 'Garage',
    carCoverage: 150000,
    deductible: 0,
    price: 0,
    paymentPlan: '',
    shippingFee: 0,
    discount: 0,
    processingFee: 0,
    invoiceAmount: 0,
  },
  {
    insurer: 'LMG Insurance',
    packageName: 'Type 1_OIC 110_Motor Gen X_garage_Group 5_1-10years',
    insuranceType: 'Type 1',
    insuranceCategory: 'mandatory',
    repairType: 'Garage',
    carCoverage: 150000,
    deductible: 0,
    price: 0,
    paymentPlan: '',
    shippingFee: 0,
    discount: 0,
    processingFee: 0,
    invoiceAmount: 0,
  },
  {
    insurer: 'Thanachart Insurance',
    packageName: 'Type 1_OIC 110_Motor Gen X_garage_Group 5_1-10years',
    insuranceType: 'Type 1',
    insuranceCategory: 'mandatory',
    repairType: 'Garage',
    carCoverage: 150000,
    deductible: 0,
    price: 0,
    paymentPlan: '',
    shippingFee: 0,
    discount: 0,
    processingFee: 0,
    invoiceAmount: 0,
  },
];

export const mockGenericPackageData = {
  results: [
    {
      premium: {
        name: 'premiums/3e6ff289-8b55-4849-9656-79f1948d4784',
        premiumId: 'GenVIB2025Personal1101SBMW220I20202119991150000',
        price: {
          value: '64521',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: 'ABC123',
        description: '',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
        insurance_package: {
          packageId: 'TYPE_110',
          packageName:
            'Type 2+_OIC 110_Super safe _Garage_Bangkok Metropolitan Region',
          carInsuranceType: 'Type 2+',
          carRepairType: 'Garage',
          subModel: 'Civic 1.8 EL',
          deductibleAmount: 0,
          hasCctvDiscount: true,
          expireTime: '9999-01-01T00:00:00Z',
          oicCode: 'TYPE_110',
          description: 'Same conditions as above',
          applicableProvinces: [
            '100000',
            '730000',
            '120000',
            '130000',
            '110000',
            '740000',
          ],
          coverages: [
            {
              coverageType: 'ownedCarDamage',
              displayName: 'Own Car Damage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalInjury',
              displayName: 'Personal Injury',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalMedicalExpense',
              displayName: 'Medical Expense',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalBailBond',
              displayName: 'Bail Bond',
              singleValue: { value: 20000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyPropertyDamage',
              displayName: 'Property Damage',
              singleValue: { value: 100000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyDeathPerPerson',
              displayName: 'Death per Person',
              singleValue: { value: 50000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyMaxDeath',
              displayName: 'Max. Death',
              singleValue: { value: 1000000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFlood',
              displayName: 'Flood Coverage',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFireTheft',
              displayName: 'Theft and Fire Coverage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'deductible',
              displayName: 'Deductible',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'dashCam',
              displayName: 'Dash Cam Discount',
              textValue: 'true',
            },
            {
              coverageType: 'insuranceType',
              displayName: 'Insurance Type',
              textValue: 'Type 2+',
            },
            {
              coverageType: 'repairType',
              displayName: 'Repair Type',
              textValue: 'Garage',
            },
            {
              coverageType: 'OicCode',
              displayName: 'OIC Code',
              textValue: 'TYPE_110',
            },
          ],
        },
      },
      package: {
        name: 'packages/2c2d5efb-f0eb-4c9b-ac39-9df4d4b98d83',
        packageId: 'GenVIB2025Personal110',
        packageName: 'VIBรถยนต์นั่งส่วนบุคคล(Privateusecar≤7ที่นั่ง)',
        insurer: '27',
        wording: 'VIBรถยนต์นั่งส่วนบุคคล(Privateusecar≤7ที่นั่ง)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2025-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/9bf56480-1896-4cf4-adcb-a3478c9e09c8',
          coverageId: 'GenVIB2025Personal110thirdPartyDeathPerPerson',
          coverageType: 'thirdPartyDeathPerPerson',
          coverageName: 'ThirdPartyDeathperperson',
          singleValue: {
            value: '80000',
            currency: 'THB',
          },
          isAddOn: false,
          displayOrder: 10,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/4f7ga390-9c66-5b5a-a767-8af2a59c5895',
        premiumId: 'GenVIB2025Commercial1201SBMW220I20202219991200000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
        insurance_package: {
          packageId: 'TYPE_110',
          packageName:
            'Type 2+_OIC 110_Super safe _Garage_Bangkok Metropolitan Region',
          carInsuranceType: 'Type 2+',
          carRepairType: 'Garage',
          subModel: 'Civic 1.8 EL',
          deductibleAmount: 0,
          hasCctvDiscount: true,
          expireTime: '9999-01-01T00:00:00Z',
          oicCode: 'TYPE_110',
          description: 'Same conditions as above',
          applicableProvinces: [
            '100000',
            '730000',
            '120000',
            '130000',
            '110000',
            '740000',
          ],
          coverages: [
            {
              coverageType: 'ownedCarDamage',
              displayName: 'Own Car Damage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalInjury',
              displayName: 'Personal Injury',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalMedicalExpense',
              displayName: 'Medical Expense',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalBailBond',
              displayName: 'Bail Bond',
              singleValue: { value: 20000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyPropertyDamage',
              displayName: 'Property Damage',
              singleValue: { value: 100000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyDeathPerPerson',
              displayName: 'Death per Person',
              singleValue: { value: 50000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyMaxDeath',
              displayName: 'Max. Death',
              singleValue: { value: 1000000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFlood',
              displayName: 'Flood Coverage',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFireTheft',
              displayName: 'Theft and Fire Coverage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'deductible',
              displayName: 'Deductible',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'dashCam',
              displayName: 'Dash Cam Discount',
              textValue: 'true',
            },
            {
              coverageType: 'insuranceType',
              displayName: 'Insurance Type',
              textValue: 'Type 2+',
            },
            {
              coverageType: 'repairType',
              displayName: 'Repair Type',
              textValue: 'Garage',
            },
            {
              coverageType: 'OicCode',
              displayName: 'OIC Code',
              textValue: 'TYPE_110',
            },
          ],
        },
      },
      package: {
        name: 'packages/3d3e6ffc-a1fc-5d0c-bd4a-aef5e5c9f94',
        packageId: 'GenVIB2025Commercial120',
        packageName:
          'VIBรถยนต์นั่งเชิงพาณิชย์/ให้เช่า(Commercialusecar≤7ที่นั่ง)',
        insurer: '27',
        wording: '',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/a0c67591-2907-5de5-bd2b-b458ad0f20d9',
          coverageId: 'GenVIB2025Commercial120insuranceType',
          coverageType: 'insuranceType',
          coverageName: 'InsuranceType',
          textValue: '',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/5g8hb401-ad77-6c6b-b878-9bg3b60d6a06',
        premiumId: 'GenVIB2025Personal2101SBMW220I20202319991250000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
        insurance_package: {
          packageId: 'TYPE_110',
          packageName:
            'Type 2+_OIC 110_Super safe _Garage_Bangkok Metropolitan Region',
          carInsuranceType: 'Type 2+',
          carRepairType: 'Garage',
          subModel: 'Civic 1.8 EL',
          deductibleAmount: 0,
          hasCctvDiscount: true,
          expireTime: '9999-01-01T00:00:00Z',
          oicCode: 'TYPE_110',
          description: 'Same conditions as above',
          applicableProvinces: [
            '100000',
            '730000',
            '120000',
            '130000',
            '110000',
            '740000',
          ],
          coverages: [
            {
              coverageType: 'ownedCarDamage',
              displayName: 'Own Car Damage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalInjury',
              displayName: 'Personal Injury',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalMedicalExpense',
              displayName: 'Medical Expense',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalBailBond',
              displayName: 'Bail Bond',
              singleValue: { value: 20000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyPropertyDamage',
              displayName: 'Property Damage',
              singleValue: { value: 100000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyDeathPerPerson',
              displayName: 'Death per Person',
              singleValue: { value: 50000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyMaxDeath',
              displayName: 'Max. Death',
              singleValue: { value: 1000000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFlood',
              displayName: 'Flood Coverage',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFireTheft',
              displayName: 'Theft and Fire Coverage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'deductible',
              displayName: 'Deductible',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'dashCam',
              displayName: 'Dash Cam Discount',
              textValue: 'true',
            },
            {
              coverageType: 'insuranceType',
              displayName: 'Insurance Type',
              textValue: 'Type 2+',
            },
            {
              coverageType: 'repairType',
              displayName: 'Repair Type',
              textValue: 'Garage',
            },
            {
              coverageType: 'OicCode',
              displayName: 'OIC Code',
              textValue: 'TYPE_110',
            },
          ],
        },
      },
      package: {
        name: 'packages/4e4f7agd-b2ad-6e1d-ce5b-bfg6f6daf05',
        packageId: 'GenVIB2025Personal210',
        packageName: 'VIBรถบรรทุกส่วนบุคคล(Truck–Personaluse)',
        insurer: '27',
        wording: '',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/b1d786a2-3a18-6ef6-ce3c-c569be1f31ea',
          coverageId: 'GenVIB2025Personal210vehicleRegistrationPurpose',
          coverageType: 'vehicleRegistrationPurpose',
          coverageName: 'VehicleRegistrationPurpose',
          textValue: '',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/6h9ic512-be88-7d7c-c989-ach4c71e7b17',
        premiumId: 'GenVIB2025Personal2101SBMW220I20202419991250000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
        insurance_package: {
          packageId: 'TYPE_110',
          packageName:
            'Type 2+_OIC 110_Super safe _Garage_Bangkok Metropolitan Region',
          carInsuranceType: 'Type 2+',
          carRepairType: 'Garage',
          subModel: 'Civic 1.8 EL',
          deductibleAmount: 0,
          hasCctvDiscount: true,
          expireTime: '9999-01-01T00:00:00Z',
          oicCode: 'TYPE_110',
          description: 'Same conditions as above',
          applicableProvinces: [
            '100000',
            '730000',
            '120000',
            '130000',
            '110000',
            '740000',
          ],
          coverages: [
            {
              coverageType: 'ownedCarDamage',
              displayName: 'Own Car Damage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalInjury',
              displayName: 'Personal Injury',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalMedicalExpense',
              displayName: 'Medical Expense',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalBailBond',
              displayName: 'Bail Bond',
              singleValue: { value: 20000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyPropertyDamage',
              displayName: 'Property Damage',
              singleValue: { value: 100000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyDeathPerPerson',
              displayName: 'Death per Person',
              singleValue: { value: 50000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyMaxDeath',
              displayName: 'Max. Death',
              singleValue: { value: 1000000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFlood',
              displayName: 'Flood Coverage',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFireTheft',
              displayName: 'Theft and Fire Coverage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'deductible',
              displayName: 'Deductible',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'dashCam',
              displayName: 'Dash Cam Discount',
              textValue: 'true',
            },
            {
              coverageType: 'insuranceType',
              displayName: 'Insurance Type',
              textValue: 'Type 2+',
            },
            {
              coverageType: 'repairType',
              displayName: 'Repair Type',
              textValue: 'Garage',
            },
            {
              coverageType: 'OicCode',
              displayName: 'OIC Code',
              textValue: 'TYPE_110',
            },
          ],
        },
      },
      package: {
        name: 'packages/5f5g8bhe-c3be-7f2e-df6c-cah7g7ebg16',
        packageId: 'GenVIB2025Personal210',
        packageName: 'VIBรถยนต์โดยสารส่วนบุคคล(Passengervan/bus–Personaluse)',
        insurer: '27',
        wording: '',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/c2e897b3-4b29-7fa7-df4d-d67acf2g42fb',
          coverageId: 'GenVIB2025Personal210dashCam',
          coverageType: 'dashCam',
          coverageName: 'DashCam',
          textValue: '',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/7i0jd623-cf99-8e8d-da9a-bdi5d82f8c28',
        premiumId: 'GenVIB2025Commercial2201SBMW320D20202119991300000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
        insurance_package: {
          packageId: 'TYPE_110',
          packageName:
            'Type 2+_OIC 110_Super safe _Garage_Bangkok Metropolitan Region',
          carInsuranceType: 'Type 2+',
          carRepairType: 'Garage',
          subModel: 'Civic 1.8 EL',
          deductibleAmount: 0,
          hasCctvDiscount: true,
          expireTime: '9999-01-01T00:00:00Z',
          oicCode: 'TYPE_110',
          description: 'Same conditions as above',
          applicableProvinces: [
            '100000',
            '730000',
            '120000',
            '130000',
            '110000',
            '740000',
          ],
          coverages: [
            {
              coverageType: 'ownedCarDamage',
              displayName: 'Own Car Damage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalInjury',
              displayName: 'Personal Injury',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalMedicalExpense',
              displayName: 'Medical Expense',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalBailBond',
              displayName: 'Bail Bond',
              singleValue: { value: 20000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyPropertyDamage',
              displayName: 'Property Damage',
              singleValue: { value: 100000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyDeathPerPerson',
              displayName: 'Death per Person',
              singleValue: { value: 50000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyMaxDeath',
              displayName: 'Max. Death',
              singleValue: { value: 1000000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFlood',
              displayName: 'Flood Coverage',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFireTheft',
              displayName: 'Theft and Fire Coverage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'deductible',
              displayName: 'Deductible',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'dashCam',
              displayName: 'Dash Cam Discount',
              textValue: 'true',
            },
            {
              coverageType: 'insuranceType',
              displayName: 'Insurance Type',
              textValue: 'Type 2+',
            },
            {
              coverageType: 'repairType',
              displayName: 'Repair Type',
              textValue: 'Garage',
            },
            {
              coverageType: 'OicCode',
              displayName: 'OIC Code',
              textValue: 'TYPE_110',
            },
          ],
        },
      },
      package: {
        name: 'packages/6g6h9cif-d4cf-8g3f-eg7d-dbi8h8fcg27',
        packageId: 'GenVIB2025Commercial220',
        packageName:
          'VIBรถยนต์โดยสารเพื่อการพาณิชย์(Passengervan/bus–Commercialuse)',
        insurer: '27',
        wording: '',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/d3f9a8c4-5c3a-8gb8-eg5e-e78bda3h53gc',
          coverageId: 'GenVIB2025Commercial220deductible',
          coverageType: 'deductible',
          coverageName: 'Deductible',
          textValue: '',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/8j1ke734-dg0a-9f9e-eb0b-cej6e93g9d39',
        premiumId: 'GenTMITH2025Personal1101SBMW220I20202119991150000',
        price: {
          value: '64521',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
        insurance_package: {
          packageId: 'TYPE_110',
          packageName:
            'Type 2+_OIC 110_Super safe _Garage_Bangkok Metropolitan Region',
          carInsuranceType: 'Type 2+',
          carRepairType: 'Garage',
          subModel: 'Civic 1.8 EL',
          deductibleAmount: 0,
          hasCctvDiscount: true,
          expireTime: '9999-01-01T00:00:00Z',
          oicCode: 'TYPE_110',
          description: 'Same conditions as above',
          applicableProvinces: [
            '100000',
            '730000',
            '120000',
            '130000',
            '110000',
            '740000',
          ],
          coverages: [
            {
              coverageType: 'ownedCarDamage',
              displayName: 'Own Car Damage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalInjury',
              displayName: 'Personal Injury',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalMedicalExpense',
              displayName: 'Medical Expense',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.personalBailBond',
              displayName: 'Bail Bond',
              singleValue: { value: 20000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyPropertyDamage',
              displayName: 'Property Damage',
              singleValue: { value: 100000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyDeathPerPerson',
              displayName: 'Death per Person',
              singleValue: { value: 50000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.thirdPartyMaxDeath',
              displayName: 'Max. Death',
              singleValue: { value: 1000000000, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFlood',
              displayName: 'Flood Coverage',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'insuranceType.ownedCarFireTheft',
              displayName: 'Theft and Fire Coverage',
              singleValue: { value: 10000000, currency: 'THB' },
            },
            {
              coverageType: 'deductible',
              displayName: 'Deductible',
              singleValue: { value: 0, currency: 'THB' },
            },
            {
              coverageType: 'dashCam',
              displayName: 'Dash Cam Discount',
              textValue: 'true',
            },
            {
              coverageType: 'insuranceType',
              displayName: 'Insurance Type',
              textValue: 'Type 2+',
            },
            {
              coverageType: 'repairType',
              displayName: 'Repair Type',
              textValue: 'Garage',
            },
            {
              coverageType: 'OicCode',
              displayName: 'OIC Code',
              textValue: 'TYPE_110',
            },
          ],
        },
      },
      package: {
        name: 'packages/7h7i0djg-e5dg-9h4g-fh8e-ecj9i9gdh38',
        packageId: 'GenTMITH2025Personal110',
        packageName: 'TMITHรถยนต์นั่งส่วนบุคคล(Privateusecar≤7ที่นั่ง)',
        insurer: '26',
        wording: 'TMITHรถยนต์นั่งส่วนบุคคล(Privateusecar≤7ที่นั่ง)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2025-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/e4g0b9d5-6d4b-9hc9-fh6f-f89cea4i64hd',
          coverageId: 'GenTMITH2025Personal110thirdPartyDeathPerPerson',
          coverageType: 'thirdPartyDeathPerPerson',
          coverageName: 'ThirdPartyDeathperperson',
          textValue: '',
          singleValue: {
            value: '80000',
            currency: 'THB',
          },
          isAddOn: false,
          displayOrder: 10,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/9k2lf845-eh1b-0g0f-fc1c-dfk7f04h0e4a',
        premiumId: 'GenTMITH2025Commercial1201SBMW220I20202219991200000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
      },
      package: {
        name: 'packages/8i8j1ekh-f6eh-0i5h-gi9f-fdka0hei49',
        packageId: 'GenTMITH2025Commercial120',
        packageName:
          'TMITHรถยนต์นั่งเชิงพาณิชย์/ให้เช่า(Commercialusecar≤7ที่นั่ง)',
        insurer: '26',
        wording:
          'TMITHรถยนต์นั่งเชิงพาณิชย์/ให้เช่า(Commercialusecar≤7ที่นั่ง)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/f5h1ca6-7e5c-0id0-gi7g-g90dfb5j75ie',
          coverageId: 'GenTMITH2025Commercial120insuranceType',
          coverageType: 'insuranceType',
          coverageName: 'InsuranceType',
          textValue: 'Mandatory',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/0l3mg956-fi2c-1h1g-gd2d-egl8g15i1f5b',
        premiumId: 'GenTMITH2025Personal2101SBMW220I20202319991250000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
      },
      package: {
        name: 'packages/9j9k2fli-g7fi-1j6i-hj0g-gelb1ifj50',
        packageId: 'GenTMITH2025Personal210',
        packageName: 'TMITHรถบรรทุกส่วนบุคคล(Truck–Personaluse)',
        insurer: '26',
        wording: 'TMITHรถบรรทุกส่วนบุคคล(Truck–Personaluse)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/g6i2db7-8f6d-1je1-hj8h-h01egc6k86jf',
          coverageId: 'GenTMITH2025Personal210vehicleRegistrationPurpose',
          coverageType: 'vehicleRegistrationPurpose',
          coverageName: 'VehicleRegistrationPurpose',
          textValue: 'Personal',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/1m4nh067-gj3d-2i2h-he3e-fhm9h26j2g6c',
        premiumId: 'GenTMITH2025Personal2101SBMW220I20202419991250000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
      },
      package: {
        name: 'packages/0k0l3gmj-h8gj-2k7j-ik1h-hfmc2jgk61',
        packageId: 'GenTMITH2025Personal210',
        packageName: 'TMITHรถยนต์โดยสารส่วนบุคคล(Passengervan/bus–Personaluse)',
        insurer: '26',
        wording: 'TMITHรถยนต์โดยสารส่วนบุคคล(Passengervan/bus–Personaluse)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/h7j3ec8-9g7e-2kf2-ik9i-i12fhd7l97kg',
          coverageId: 'GenTMITH2025Personal210deductible',
          coverageType: 'deductible',
          coverageName: 'Deductible',
          textValue: 'Nodeductible',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/2n5oi178-hk4e-3j3i-if4f-gin0i37k3h7d',
        premiumId: 'GenTMITH2025Commercial2201SBMW320D20202119991300000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
      },
      package: {
        name: 'packages/1l1m4hnk-i9hk-3l8k-jl2i-ignd3khl72',
        packageId: 'GenTMITH2025Commercial220',
        packageName:
          'TMITHรถยนต์โดยสารเพื่อการพาณิชย์(Passengervan/bus–Commercialuse)',
        insurer: '26',
        wording:
          'TMITHรถยนต์โดยสารเพื่อการพาณิชย์(Passengervan/bus–Commercialuse)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/i8k4fd9-0h8f-3lg3-jl0j-j23gie8m08lh',
          coverageId: 'GenTMITH2025Commercial220thirdPartyMaxDeath',
          coverageType: 'thirdPartyMaxDeath',
          coverageName: 'ThirdPartyMax.Death',
          textValue: '',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/3o6pj289-il5f-4k4j-jg5g-hjo1j48l4i8e',
        premiumId: 'GenTVI2025Personal1101SBMW220I20202119991150000',
        price: {
          value: '64521',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
      },
      package: {
        name: 'packages/2m2n5iol-j0il-4m9l-km3j-jhoe4lim83',
        packageId: 'GenTVI2025Personal110',
        packageName: 'TVIรถยนต์นั่งส่วนบุคคล(Privateusecar≤7ที่นั่ง)',
        insurer: '25',
        wording: 'TVIรถยนต์นั่งส่วนบุคคล(Privateusecar≤7ที่นั่ง)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2025-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/j9l5ge0-1i9g-4mh4-km1k-k34hjf9n19mi',
          coverageId: 'GenTVI2025Personal110thirdPartyDeathPerPerson',
          coverageType: 'thirdPartyDeathPerPerson',
          coverageName: 'ThirdPartyDeathperperson',
          textValue: '',
          singleValue: {
            value: '80000',
            currency: 'THB',
          },
          isAddOn: false,
          displayOrder: 10,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/4p7qk390-jm6g-5l5k-kh6h-ikp2k59m5j9f',
        premiumId: 'GenTVI2025Commercial1201SBMW220I20202219991200000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
      },
      package: {
        name: 'packages/3n3o6jpm-k1jm-5n0m-ln4k-kipf5mjn94',
        packageId: 'GenTVI2025Commercial120',
        packageName:
          'TVIรถยนต์นั่งเชิงพาณิชย์/ให้เช่า(Commercialusecar≤7ที่นั่ง)',
        insurer: '25',
        wording: 'TVIรถยนต์นั่งเชิงพาณิชย์/ให้เช่า(Commercialusecar≤7ที่นั่ง)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/k0m6hf1-2j0h-5ni5-ln2l-l45ikg0o20nj',
          coverageId: 'GenTVI2025Commercial120personalInjury',
          coverageType: 'personalInjury',
          coverageName: 'PersonalInjuryperperson',
          textValue: '',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/5q8rl401-kn7h-6m6l-li7i-jlq3l60n6k0g',
        premiumId: 'GenTVI2025Personal2101SBMW220I20202319991250000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
      },
      package: {
        name: 'packages/4o4p7kqn-l2kn-6o1n-mo5l-ljqg6nko05',
        packageId: 'GenTVI2025Personal210',
        packageName: 'TVIรถยนต์โดยสารส่วนบุคคล(Passengervan/bus–Personaluse)',
        insurer: '25',
        wording: 'TVIรถยนต์โดยสารส่วนบุคคล(Passengervan/bus–Personaluse)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/l1n7ig2-3k1i-6oj6-mo3m-m56jlh1p31ok',
          coverageId: 'GenTVI2025Personal210insuranceType',
          coverageType: 'insuranceType',
          coverageName: 'InsuranceType',
          textValue: 'Mandatory',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/6r9sm512-lo8i-7n7m-mj8j-kmr4m71o7l1h',
        premiumId: 'GenTVI2025Personal2101SBMW220I20202419991250000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
      },
      package: {
        name: 'packages/5p5q8lro-m3lo-7p2o-np6m-mkrh7olp16',
        packageId: 'GenTVI2025Personal210',
        packageName: 'TVIรถยนต์โดยสารส่วนบุคคล(Passengervan/bus–Personaluse)',
        insurer: '25',
        wording: 'TVIรถยนต์โดยสารส่วนบุคคล(Passengervan/bus–Personaluse)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/m2o8jh3-4l2j-7pk7-np4n-n67kmi2q42pl',
          coverageId: 'GenTVI2025Personal210personalMedicalExpense',
          coverageType: 'personalMedicalExpense',
          coverageName: 'MedicalExpenseperperson',
          textValue: '',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
    {
      premium: {
        name: 'premiums/7s0tn623-mp9j-8o8n-nk9k-lns5n82p8m2i',
        premiumId: 'GenTVI2025Commercial2201SBMW320D20202119991300000',
        price: {
          value: '15300',
          currency: 'THB',
        },
        redbookId: '',
        insurerCarId: '',
        description: '16-20',
        createTime: '2025-06-20T10:49:14.026121Z',
        updateTime: '2025-06-20T10:49:36.295206Z',
      },
      package: {
        name: 'packages/6q6r9msp-n4mp-8q3p-oq7n-nlsi8pmq27',
        packageId: 'GenTVI2025Commercial220',
        packageName:
          'TVIรถยนต์โดยสารเพื่อการพาณิชย์(Passengervan/bus–Commercialuse)',
        insurer: '25',
        wording:
          'TVIรถยนต์โดยสารเพื่อการพาณิชย์(Passengervan/bus–Commercialuse)',
        description: '',
        validFrom: '2025-01-01T00:00:00Z',
        validTo: '2026-12-31T00:00:00Z',
        createTime: '2025-06-20T08:20:52.244419Z',
        updateTime: '2025-06-20T08:20:52.244419Z',
      },
      coverages: [
        {
          name: 'coverages/n3p9ki4-5m3k-8ql8-oq5o-o78lnj3r53qm',
          coverageId: 'GenTVI2025Commercial220thirdPartyMaxDeath',
          coverageType: 'thirdPartyMaxDeath',
          coverageName: 'ThirdPartyMax.Death',
          textValue: '',
          displayOrder: 1,
          createTime: '2025-06-20T09:04:15.078013Z',
          updateTime: '2025-06-20T09:04:15.078013Z',
        },
      ],
    },
  ],
  nextToken:
    'eyJzb3J0QnkiOiJjcmVhdGVUaW1lIiwiZGlyZWN0aW9uIjoiZGVzYyIsImxpbWl0IjoxMCwidmFsdWUiOiIyMDI1LTA2LTIwVDA5OjA0OjE1LjA3ODAxM1oiLCJ0aWVicmVha2VyIjoiaWQiLCJ0aWVicmVha2VyVmFsdWUiOiI5YmY1NjQ4MC0xODk2LTRjZjQtYWRjYi1hMzQ3OGM5ZTA5YzgifQ',
};
