import { Package } from 'data/slices/genericPackageSlice';

export const mockInsurancePackage: Package = {
  name: 'premiums/test-package-id',
  displayName: 'Test Package Display Name',
  price: '1000000',
  insurer: 'insurers/1',
  carInsuranceType: 'TYPE_1',
  isFixedPremium: false,
  deductibleAmount: '5000',
  sumCoverageMin: '1000000',
  sumCoverageMax: '2000000',
  bailBondCoverage: '300000',
  fireTheftCoverage: '1000000',
  floodCoverage: '1000000',
  medicalExpensesCoverage: '500000',
  medicalExpensesCoverageNo: 2,
  personalAccidentCoverage: '1000000',
  personalAccidentCoverageNo: 1,
  liabilityPropertyCoverage: '10000000',
  liabilityPerPersonCoverage: '1000000',
  liabilityPerAccidentCoverage: '2000000',
  carRepairType: 'GARAGE',
  carAgeMin: 0,
  carAgeMax: 10,
  modifiedCarAccepted: false,
  oicCode: 'TYPE_110',
  termsEn: 'English terms',
  termsTh: 'Thai terms',
  expireTime: '2025-12-31T00:00:00Z',
  status: 'ACTIVE',
  filename: 'test.pdf',
  createTime: '2024-01-01T00:00:00Z',
  updateTime: '2024-01-01T00:00:00Z',
  broker: 'BROKER_1',
  source: 'API',
  code: 1,
  insurerPackageCode: 'PKG001',
  isEcoCar: false,
  yearlyMileage: 10000,
  antiTheftDiscount: '0',
  yearsOwned: 0,
  numberVehiclesHousehold: 1,
  carRegistrationCategory: 'PERSONAL',
  drivingPurpose: 'PERSONAL',
  parkingLocation: 'GARAGE',
  maritalStatus: 'SINGLE',
  occupation: 'EMPLOYEE',
  drivingExperience: 5,
  reuseManualPackage: false,
  hasCctvDiscount: true,
  startTime: '2024-01-01T00:00:00Z',
  isLowCost: false,
  provinces: ['Bangkok', 'Chiang Mai'],
  gender: 'MALE',
  carUsingPurpose: 'PERSONAL',
  noClaimBonus: 'NO_CLAIM_BONUS_1',
  excessType: 'EXCESS_TYPE_1',
  minYearsOfHoldingDriverLicense: 1,
  maxYearsOfHoldingDriverLicense: 50,
  minNumberOfClaimsInYear: 0,
  maxNumberOfClaimsInYear: 5,
  maxAge: 80,
  minAge: 18,
  minMileage: 0,
  maxMileage: 100000,
  carSubmodels: ['Model A', 'Model B'],
  insuranceCategory: 'VOLUNTARY',
  packageType: 'STANDARD',
  noClaimBonusAmount: '10000',
  claimValue: '50000',
  numberOfClaims: 0,
  lead: 'LEAD_001',
  searchable: true,
  createBy: 'admin',
  priceResourceName: 'packages/test',
  customPackageStatus: 'APPROVED',
};

export const mockComplexInsurancePackage: Package = {
  name: 'premiums/complex-test',
  displayName: 'Complex Test Package',
  price: '2500000',
  insurer: 'insurers/999',
  carInsuranceType: 'TYPE_2',
  isFixedPremium: true,
  deductibleAmount: '10000',
  sumCoverageMin: '5000000',
  sumCoverageMax: '10000000',
  bailBondCoverage: '500000',
  fireTheftCoverage: '5000000',
  floodCoverage: '5000000',
  medicalExpensesCoverage: '2000000',
  medicalExpensesCoverageNo: 3,
  personalAccidentCoverage: '2000000',
  personalAccidentCoverageNo: 3,
  liabilityPropertyCoverage: '20000000',
  liabilityPerPersonCoverage: '2000000',
  liabilityPerAccidentCoverage: '5000000',
  carRepairType: 'DEALER',
  carAgeMin: 1,
  carAgeMax: 15,
  modifiedCarAccepted: true,
  oicCode: 'TYPE_220',
  termsEn: 'Complex English terms',
  termsTh: 'Complex Thai terms',
  expireTime: '2025-12-31T00:00:00Z',
  status: 'ACTIVE',
  filename: 'complex.pdf',
  createTime: '2024-06-01T10:30:00Z',
  updateTime: '2024-06-01T10:30:00Z',
  broker: 'BROKER_999',
  source: 'MANUAL',
  code: 999,
  insurerPackageCode: 'PKG999',
  isEcoCar: true,
  yearlyMileage: 20000,
  antiTheftDiscount: '5000',
  yearsOwned: 3,
  numberVehiclesHousehold: 2,
  carRegistrationCategory: 'COMMERCIAL',
  drivingPurpose: 'COMMERCIAL',
  parkingLocation: 'STREET',
  maritalStatus: 'MARRIED',
  occupation: 'BUSINESS_OWNER',
  drivingExperience: 10,
  reuseManualPackage: true,
  hasCctvDiscount: false,
  startTime: '2024-06-01T10:30:00Z',
  isLowCost: true,
  provinces: ['Bangkok', 'Chiang Mai', 'Phuket'],
  gender: 'FEMALE',
  carUsingPurpose: 'COMMERCIAL',
  noClaimBonus: 'NO_CLAIM_BONUS_2',
  excessType: 'EXCESS_TYPE_2',
  minYearsOfHoldingDriverLicense: 2,
  maxYearsOfHoldingDriverLicense: 60,
  minNumberOfClaimsInYear: 0,
  maxNumberOfClaimsInYear: 3,
  maxAge: 70,
  minAge: 25,
  minMileage: 1000,
  maxMileage: 150000,
  carSubmodels: ['Model C', 'Model D'],
  insuranceCategory: 'MANDATORY',
  packageType: 'PREMIUM',
  noClaimBonusAmount: '20000',
  claimValue: '100000',
  numberOfClaims: 2,
  lead: 'LEAD_999',
  searchable: false,
  createBy: 'test_user',
  priceResourceName: 'packages/complex',
  customPackageStatus: 'PENDING',
};
