import { Insurer } from 'data/slices/genericPackageSlice';

export const mockInsuranceInsurer: Insurer = {
  name: 'insurers/1',
  displayName: 'Test Insurance Company',
  displayNameTh: 'บริษัททดสอบ',
  shortnameEn: 'Test Ins',
  shortnameTh: 'ทดสอบ',
  rating: 4.5,
  order: 1,
  logo: 'https://example.com/logo.png',
  phone: '02-123-4567',
  website: 'https://test-insurance.com',
  taxId: '1234567890123',
  ticker: 'TEST',
  fax: '02-123-4568',
  addressEn: '123 Test Street, Bangkok',
  addressTh: '123 ถนนทดสอบ กรุงเทพฯ',
  contactEmail: 'contact@test-insurance.com',
  contactPersonName: 'John Doe',
  infoEn: 'Test insurance company info',
  infoTh: 'ข้อมูลบริษัทประกันภัยทดสอบ',
  carPicturesRequired: true,
  brokerCode: 'BRK001',
};

export const mockComplexInsuranceInsurer: Insurer = {
  name: 'insurers/999',
  displayName: 'Complex Insurance Company',
  displayNameTh: 'บริษัทประกันภัยที่ซับซ้อน',
  shortnameEn: 'Complex Ins',
  shortnameTh: 'ซับซ้อน',
  rating: 2.5,
  order: 99,
  logo: 'https://complex.com/logo.png',
  phone: '02-999-9999',
  website: 'https://complex-insurance.com',
  taxId: '9999999999999',
  ticker: 'COMPLEX',
  fax: '02-999-9998',
  addressEn: '999 Complex Street, Bangkok',
  addressTh: '999 ถนนซับซ้อน กรุงเทพฯ',
  contactEmail: 'complex@complex-insurance.com',
  contactPersonName: 'Jane Smith',
  infoEn: 'Complex insurance company information',
  infoTh: 'ข้อมูลบริษัทประกันภัยที่ซับซ้อน',
  carPicturesRequired: false,
  brokerCode: 'BRK999',
};
