/* eslint-disable import/prefer-default-export */
export const MockInsurers = {
  insurers: [
    {
      name: 'insurers/42',
      displayName: 'FPG Insurance',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/40',
      displayName: 'Chubb Samaggi Insurance Co. (PLC)',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/38',
      displayName: 'Roojai Insurance',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/37',
      displayName: 'AIG Insurance (Thailand) Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 18,
    },
    {
      name: 'insurers/36',
      displayName: 'Sri Ayudhaya General Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/35',
      displayName: 'Tokio Marine Safety Insurance (Thailand) PCL',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 5,
    },
    {
      name: 'insurers/34',
      displayName: 'MSIG Insurance (Thailand) Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/33',
      displayName: 'LMG Insurance Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 12,
    },
    {
      name: 'insurers/32',
      displayName: 'Krungthai Panich Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/31',
      displayName: 'The Navakij Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 13,
    },
    {
      name: 'insurers/30',
      displayName: 'Generali Insurance (Thailand) Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/29',
      displayName: 'Samaggi Insurance Company Limited (Thailand)',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/28',
      displayName: 'Thanachart Insurance Co., Ltd',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 4,
    },
    {
      name: 'insurers/27',
      displayName: 'The Viriyah Insurance Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 2,
    },
    {
      name: 'insurers/26',
      displayName: 'Tokio Marine Insurance (Thailand) Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/25',
      displayName: 'Thaivivat Insurance Public Co., Ltd.',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 6,
    },
    {
      name: 'insurers/24',
      displayName: 'Thaisri Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 3,
    },
    {
      name: 'insurers/23',
      displayName: 'Thai Setakij Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/22',
      displayName: 'Siam City Insurance PLC',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/21',
      displayName: 'Thai Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/20',
      displayName: 'Syn Mun Kong Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 15,
    },
    {
      name: 'insurers/19',
      displayName: 'The South East Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 7,
    },
    {
      name: 'insurers/18',
      displayName: 'Nam Seng Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/17',
      displayName: 'Muang Thai Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 9,
    },
    {
      name: 'insurers/16',
      displayName: 'Mittare Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/15',
      displayName: 'KSK Insurance (Thailand) Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/14',
      displayName: 'Kamol Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/13',
      displayName: 'Indara Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/12',
      displayName: 'Erawan Insurance Co.,Ltd.',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/11',
      displayName: 'Dhipaya Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 8,
    },
    {
      name: 'insurers/10',
      displayName: 'The Deves Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 14,
    },
    {
      name: 'insurers/9',
      displayName: 'Charan Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/8',
      displayName: 'Chao Phaya Inurance Pubilic Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/7',
      displayName: 'Bangkok Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 1,
    },
    {
      name: 'insurers/6',
      displayName: 'AXA Insurance Pubilic Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 11,
    },
    {
      name: 'insurers/5',
      displayName: 'Assets Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 17,
    },
    {
      name: 'insurers/4',
      displayName: 'Asia Insurance 1950 Co., Ltd',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 10,
    },
    {
      name: 'insurers/3',
      displayName: 'Aioi Bangkok Insurance Public Company Limited',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/2',
      displayName: 'Thai Paiboon Insurance PLC',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 0,
    },
    {
      name: 'insurers/1',
      displayName: 'Allianz  General Insurance Public Company Limited',
      displayNameTh: 'บริษัท อลิอันซ์ ประกันภัย จำกัด (มหาชน)',
      shortnameEn: '',
      shortnameTh: '',
      rating: 0,
      order: 16,
    },
  ],
  nextPageToken: '',
};
