import {
  LeadPaymentInformation,
  NewLeadPaymentInformation,
  PaymentOptions,
  PaymentSelection,
} from 'shared/types/lead';
import { add, format, sub } from 'utils/datetime';

export const mockPaymentOptions = {
  fullPayment: {
    packagePrice: {
      voluntaryPrice: '599900',
      compulsoryPrice: '0',
      totalPrice: '599900',
      discountPrice: '0',
    },
    paymentDetails: [
      {
        paymentMethod: 'QR_CODE',
        paymentAmount: {
          interestFeePercentage: 0,
          interestFeeAmount: '0',
          processingFeePercentage: 0,
          processingFeeAmount: '0',
          feePercentage: 0,
          feeAmount: '0',
          discountPercentage: 0,
          discountAmount: '0',
          netDiscountPercentage: 0,
          netDiscountAmount: '0',
          packagePriceAfterDiscount: '599900',
          netPremiumAmount: '599900',
          firstMonth: '0',
          nextMonths: '0',
          grandTotal: '599900',
        },
        paymentBreakdowns: [],
        priceSummary: {
          interestRate: 0,
          interestAmount: '0',
          processingFeeRate: 0,
          processingFeeAmount: '0',
          feeRate: 0,
          feeAmount: '0',
          discountRate: 0,
          discountAmount: '0',
          netDiscountRate: 0,
          netDiscountAmount: '0',
          packagePriceAfterDiscount: '599900',
          netPremiumAmount: '599900',
          initialAmount: '0',
          subsequentAmount: '0',
        },
        installmentDetail: [],
      },
    ],
  },
  rabbitCareInstallment: {
    packagePrice: {
      voluntaryPrice: '599900',
      compulsoryPrice: '0',
      totalPrice: '599900',
      discountPrice: '0',
    },
    availablePlans: [3],
    installmentPlans: [
      {
        numberOfInstallment: 3,
        paymentDetails: [
          {
            paymentMethod: 'QR_CODE',
            paymentAmount: {
              interestFeePercentage: 1.33,
              interestFeeAmount: '7678',
              processingFeePercentage: 0.67,
              processingFeeAmount: '3839',
              feePercentage: 2,
              feeAmount: '11518',
              discountPercentage: 4,
              discountAmount: '23996',
              netDiscountPercentage: -2.08,
              netDiscountAmount: '-12477',
              packagePriceAfterDiscount: '575904',
              netPremiumAmount: '587422',
              firstMonth: '195808',
              nextMonths: '195807',
              grandTotal: '587422',
            },
            paymentBreakdowns: [
              {
                period: 1,
                paymentAmount: '195808',
                principal: '191968',
                addOns: '0',
                interest: '0',
                processingFee: '3840',
                principalBalance: '383936',
                interestBalance: '7679',
                processingFeeBalance: '0',
                totalBalance: '391615',
              },
              {
                period: 2,
                paymentAmount: '195807',
                principal: '190699',
                addOns: '0',
                interest: '5108',
                processingFee: '0',
                principalBalance: '193237',
                interestBalance: '2571',
                processingFeeBalance: '0',
                totalBalance: '195807',
              },
              {
                period: 3,
                paymentAmount: '195807',
                principal: '193237',
                addOns: '0',
                interest: '2571',
                processingFee: '0',
                principalBalance: '0',
                interestBalance: '0',
                processingFeeBalance: '0',
                totalBalance: '0',
              },
            ],
            priceSummary: {
              interestRate: 1.33,
              interestAmount: '7678',
              processingFeeRate: 0.67,
              processingFeeAmount: '3839',
              feeRate: 2,
              feeAmount: '11518',
              discountRate: 4,
              discountAmount: '23996',
              netDiscountRate: -2.08,
              netDiscountAmount: '-12477',
              packagePriceAfterDiscount: '575904',
              netPremiumAmount: '587422',
              initialAmount: '195808',
              subsequentAmount: '195807',
            },
            installmentDetail: [
              {
                period: 1,
                paymentAmount: '195808',
                principal: '191968',
                addOns: '0',
                interest: '0',
                processingFee: '3840',
                principalBalance: '383936',
                interestBalance: '7679',
                processingFeeBalance: '0',
                totalBalance: '391615',
              },
              {
                period: 2,
                paymentAmount: '195807',
                principal: '190699',
                addOns: '0',
                interest: '5108',
                processingFee: '0',
                principalBalance: '193237',
                interestBalance: '2571',
                processingFeeBalance: '0',
                totalBalance: '195807',
              },
              {
                period: 3,
                paymentAmount: '195807',
                principal: '193237',
                addOns: '0',
                interest: '2571',
                processingFee: '0',
                principalBalance: '0',
                interestBalance: '0',
                processingFeeBalance: '0',
                totalBalance: '0',
              },
            ],
          },
        ],
      },
    ],
    directDebitProviders: [
      {
        name: 'card-providers/BAY',
        shortName: 'BAY',
        displayNameTh: 'ธนาคารกรุงศรี',
        displayNameEn: 'Bank of Ayudhya Public Company Limited',
        minimumAmount: '0',
        availablePlans: [3],
        installmentPlans: [
          {
            numberOfInstallment: 3,
            paymentDetails: [
              {
                paymentMethod: 'QR_CODE',
                paymentAmount: {
                  interestFeePercentage: 0,
                  interestFeeAmount: '0',
                  processingFeePercentage: 0,
                  processingFeeAmount: '0',
                  feePercentage: 0,
                  feeAmount: '0',
                  discountPercentage: 0,
                  discountAmount: '0',
                  netDiscountPercentage: 0,
                  netDiscountAmount: '0',
                  packagePriceAfterDiscount: '599900',
                  netPremiumAmount: '599900',
                  firstMonth: '199966',
                  nextMonths: '199966',
                  grandTotal: '599900',
                },
                paymentBreakdowns: [],
                priceSummary: {
                  interestRate: 0,
                  interestAmount: '0',
                  processingFeeRate: 0,
                  processingFeeAmount: '0',
                  feeRate: 0,
                  feeAmount: '0',
                  discountRate: 0,
                  discountAmount: '0',
                  netDiscountRate: 0,
                  netDiscountAmount: '0',
                  packagePriceAfterDiscount: '599900',
                  netPremiumAmount: '599900',
                  initialAmount: '199966',
                  subsequentAmount: '199966',
                },
                installmentDetail: [],
              },
            ],
          },
        ],
      },
    ],
  },
  creditCardInstallment: {
    packagePrice: {
      voluntaryPrice: '599900',
      compulsoryPrice: '0',
      totalPrice: '599900',
      discountPrice: '0',
    },
    cardProviders: [
      {
        name: 'card-providers/BAY',
        shortName: 'BAY',
        displayNameTh: 'ธนาคารกรุงศรี',
        displayNameEn: 'Bank of Ayudhya Public Company Limited',
        minimumAmount: '0',
        availablePlans: [3],
        installmentPlans: [
          {
            numberOfInstallment: 3,
            paymentDetails: [
              {
                paymentMethod: 'QR_CODE',
                paymentAmount: {
                  interestFeePercentage: 0,
                  interestFeeAmount: '0',
                  processingFeePercentage: 0,
                  processingFeeAmount: '0',
                  feePercentage: 0,
                  feeAmount: '0',
                  discountPercentage: 0,
                  discountAmount: '0',
                  netDiscountPercentage: 0,
                  netDiscountAmount: '0',
                  packagePriceAfterDiscount: '599900',
                  netPremiumAmount: '599900',
                  firstMonth: '199966',
                  nextMonths: '199966',
                  grandTotal: '599900',
                },
                paymentBreakdowns: [],
                priceSummary: {
                  interestRate: 0,
                  interestAmount: '0',
                  processingFeeRate: 0,
                  processingFeeAmount: '0',
                  feeRate: 0,
                  feeAmount: '0',
                  discountRate: 0,
                  discountAmount: '0',
                  netDiscountRate: 0,
                  netDiscountAmount: '0',
                  packagePriceAfterDiscount: '599900',
                  netPremiumAmount: '599900',
                  initialAmount: '199966',
                  subsequentAmount: '199966',
                },
                installmentDetail: [],
              },
            ],
          },
        ],
      },
    ],
  },
} as PaymentOptions;

export const mockPaymentSelections = [
  {
    paymentOption: 'FULL_PAYMENT',
    paymentMethods: ['ONLINECARD', 'QR_CODE'],
    installmentPlans: [],
    cardProviders: [],
  },
  {
    paymentOption: 'CREDIT_CARD_INSTALLMENT',
    paymentMethods: ['ONLINECARD'],
    installmentPlans: [],
    cardProviders: [
      {
        name: 'card-providers/BAY',
        shortName: 'BAY',
        displayNameTh: 'ธนาคารกรุงศรี',
        displayNameEn: 'Bank of Ayudhya Public Company Limited',
        installmentPlans: [
          {
            numberOfInstallments: 3,
            firstMonthInstallment: 7182,
            nextMonthsInstallment: 7182,
          },
          {
            numberOfInstallments: 4,
            firstMonthInstallment: 5388,
            nextMonthsInstallment: 5386,
          },
          {
            numberOfInstallments: 6,
            firstMonthInstallment: 3591,
            nextMonthsInstallment: 3591,
          },
          {
            numberOfInstallments: 9,
            firstMonthInstallment: 2394,
            nextMonthsInstallment: 2394,
          },
          {
            numberOfInstallments: 10,
            firstMonthInstallment: 2160,
            nextMonthsInstallment: 2154,
          },
        ],
      },
      {
        name: 'card-providers/BBL',
        shortName: 'BBL',
        displayNameTh: 'ธนาคารกรุงเทพ',
        displayNameEn: 'Bangkok Bank Public Company Limited',
        installmentPlans: [
          {
            numberOfInstallments: 4,
            firstMonthInstallment: 5388,
            nextMonthsInstallment: 5386,
          },
          {
            numberOfInstallments: 6,
            firstMonthInstallment: 3591,
            nextMonthsInstallment: 3591,
          },
          {
            numberOfInstallments: 8,
            firstMonthInstallment: 2695,
            nextMonthsInstallment: 2693,
          },
          {
            numberOfInstallments: 9,
            firstMonthInstallment: 2394,
            nextMonthsInstallment: 2394,
          },
          {
            numberOfInstallments: 10,
            firstMonthInstallment: 2160,
            nextMonthsInstallment: 2154,
          },
        ],
      },
      {
        name: 'card-providers/FIRST_CHOICE',
        shortName: 'FIRST_CHOICE',
        displayNameTh: 'กรุงศรีเฟิร์สช้อยส์',
        displayNameEn: 'Krungsri First Choice',
        installmentPlans: [
          {
            numberOfInstallments: 3,
            firstMonthInstallment: 7182,
            nextMonthsInstallment: 7182,
          },
          {
            numberOfInstallments: 4,
            firstMonthInstallment: 5388,
            nextMonthsInstallment: 5386,
          },
          {
            numberOfInstallments: 6,
            firstMonthInstallment: 3591,
            nextMonthsInstallment: 3591,
          },
          {
            numberOfInstallments: 9,
            firstMonthInstallment: 2394,
            nextMonthsInstallment: 2394,
          },
          {
            numberOfInstallments: 10,
            firstMonthInstallment: 2160,
            nextMonthsInstallment: 2154,
          },
          {
            numberOfInstallments: 12,
            firstMonthInstallment: 1801,
            nextMonthsInstallment: 1795,
          },
          {
            numberOfInstallments: 18,
            firstMonthInstallment: 1197,
            nextMonthsInstallment: 1197,
          },
          {
            numberOfInstallments: 24,
            firstMonthInstallment: 915,
            nextMonthsInstallment: 897,
          },
          {
            numberOfInstallments: 36,
            firstMonthInstallment: 616,
            nextMonthsInstallment: 598,
          },
        ],
      },
      {
        name: 'card-providers/KBANK',
        shortName: 'KBANK',
        displayNameTh: 'ธนาคารกสิกร',
        displayNameEn: 'Kasikornbank Public Company Limited',
        installmentPlans: [
          {
            numberOfInstallments: 3,
            firstMonthInstallment: 7182,
            nextMonthsInstallment: 7182,
          },
          {
            numberOfInstallments: 4,
            firstMonthInstallment: 5388,
            nextMonthsInstallment: 5386,
          },
          {
            numberOfInstallments: 6,
            firstMonthInstallment: 3591,
            nextMonthsInstallment: 3591,
          },
          {
            numberOfInstallments: 10,
            firstMonthInstallment: 2160,
            nextMonthsInstallment: 2154,
          },
        ],
      },
      {
        name: 'card-providers/KTC',
        shortName: 'KTC',
        displayNameTh: 'บัตรกรุงไทย',
        displayNameEn: 'Krungthai Card',
        installmentPlans: [
          {
            numberOfInstallments: 3,
            firstMonthInstallment: 7182,
            nextMonthsInstallment: 7182,
          },
          {
            numberOfInstallments: 4,
            firstMonthInstallment: 5388,
            nextMonthsInstallment: 5386,
          },
          {
            numberOfInstallments: 5,
            firstMonthInstallment: 4310,
            nextMonthsInstallment: 4309,
          },
          {
            numberOfInstallments: 6,
            firstMonthInstallment: 3591,
            nextMonthsInstallment: 3591,
          },
          {
            numberOfInstallments: 7,
            firstMonthInstallment: 3078,
            nextMonthsInstallment: 3078,
          },
          {
            numberOfInstallments: 8,
            firstMonthInstallment: 2695,
            nextMonthsInstallment: 2693,
          },
          {
            numberOfInstallments: 9,
            firstMonthInstallment: 2394,
            nextMonthsInstallment: 2394,
          },
          {
            numberOfInstallments: 10,
            firstMonthInstallment: 2160,
            nextMonthsInstallment: 2154,
          },
        ],
      },
      {
        name: 'card-providers/SCB',
        shortName: 'SCB',
        displayNameTh: 'ธนาคารไทยพาณิชย์',
        displayNameEn: 'The Siam Commercial Bank Public Company Limited',
        installmentPlans: [
          {
            numberOfInstallments: 3,
            firstMonthInstallment: 7182,
            nextMonthsInstallment: 7182,
          },
          {
            numberOfInstallments: 4,
            firstMonthInstallment: 5388,
            nextMonthsInstallment: 5386,
          },
          {
            numberOfInstallments: 6,
            firstMonthInstallment: 3591,
            nextMonthsInstallment: 3591,
          },
          {
            numberOfInstallments: 9,
            firstMonthInstallment: 2394,
            nextMonthsInstallment: 2394,
          },
          {
            numberOfInstallments: 10,
            firstMonthInstallment: 2160,
            nextMonthsInstallment: 2154,
          },
        ],
      },
      {
        name: 'card-providers/UOB',
        shortName: 'UOB',
        displayNameTh: 'ธนาคารยูโอบี',
        displayNameEn: 'United Overseas Bank',
        installmentPlans: [
          {
            numberOfInstallments: 3,
            firstMonthInstallment: 7182,
            nextMonthsInstallment: 7182,
          },
          {
            numberOfInstallments: 4,
            firstMonthInstallment: 5388,
            nextMonthsInstallment: 5386,
          },
          {
            numberOfInstallments: 6,
            firstMonthInstallment: 3591,
            nextMonthsInstallment: 3591,
          },
          {
            numberOfInstallments: 10,
            firstMonthInstallment: 2160,
            nextMonthsInstallment: 2154,
          },
        ],
      },
    ],
  },
  {
    paymentOption: 'RABBIT_CARE_INSTALLMENT',
    paymentMethods: ['ONLINECARD', 'QR_CODE', 'RECURRING'],
    installmentPlans: [
      {
        numberOfInstallments: 3,
        firstMonthInstallment: 7614,
        nextMonthsInstallment: 6966,
      },
      {
        numberOfInstallments: 6,
        firstMonthInstallment: 4131,
        nextMonthsInstallment: 3483,
      },
      {
        numberOfInstallments: 10,
        firstMonthInstallment: 2736,
        nextMonthsInstallment: 2090,
      },
    ],
    cardProviders: [],
  },
] as PaymentSelection[];

export const mockLeadPaymentInformation = {
  customerInformation: {
    leadId: 'leads/d49defb2-3a62-11ed-a261-0242ac120002',
    humanId: 'L12345',
    orderType: 'Motor',
    customerId: '1234567890',
    customerName: 'Maetad Sukarasud',
    policyHolderType: 'straw_buyer',
    policyAddress: 'Q. House Lumphini Rama 4, Bangkok Thailand 10110',
    email: 'testemail@rabbit.co.th',
    phoneNumber: '081000000',
  },
  quoteInformation: {
    insurerName: 'Bangkok Insurer',
    insuranceType: 'TYPE_1', // TYPE_1, TYPE_2, TYPE_2_PLUS, TYPE_3, TYPE_3_PLUS
    licensePlate: '999-1234',
    car: 'Toyota Fortuner 2700 CC 4 doors V Wagon',
    grossVoluntaryPremium: 64500,
    processingFee: 5000,
    totalPremium: 1354500,
    startDate: format(sub(new Date(), { days: 2 }), "yyyy-MM-dd'T'00:00:00'Z'"),
    endDate: `${format(
      add(sub(new Date(), { days: 2 }), { years: 1 }),
      'yyyy-MM-dd'
    )}T00:00:00Z`,
  },
  paymentSelections: mockPaymentSelections,
  paymentOptions: mockPaymentOptions,
} as LeadPaymentInformation;

export const mockLeadPaymentInformationChangeOrder = {
  customerInformation: {
    leadId: 'leads/fe4e4ad9-4da3-4a6f-adf2-a6f294dc07b2',
    humanId: 'L9910406',
    customerName: 'Miw ChangeOrder',
  },
  quoteInformation: {
    insurerName: 'บริษัท วิริยะประกันภัย จำกัด (มหาชน)',
    insuranceKind: 'VOLUNTARY',
    insuranceType: 'TYPE_1',
    licensePlate: 'redplate',
    car: 'Toyota Corolla Altis 2021 1600 CC (4 Doors) G ',
    grossMandatoryPremium: '0',
    grossVoluntaryPremium: '2100000',
    discount: '0',
    totalPremium: '2100000',
  },
  paymentSelections: [],
  paymentOptions: {
    fullPayment: {
      packagePrice: {
        voluntaryPrice: '2100000',
        compulsoryPrice: '0',
        totalPrice: '2100000',
      },
      paymentDetails: [
        {
          paymentMethod: 'ONLINECARD',
          priceSummary: {
            interestRate: 0,
            interestAmount: '0',
            processingFeeRate: 1,
            processingFeeAmount: '21000',
            feeRate: 1,
            feeAmount: '21000',
            discountRate: 0,
            discountAmount: '0',
            netDiscountRate: 1,
            netDiscountAmount: '21000',
            packagePriceAfterDiscount: '2100000',
            netPremiumAmount: '2121000',
            initialAmount: '0',
            subsequentAmount: '0',
            discount: null,
            shipmentFee: '0',
            feeAmountNoShip: '21000',
          },
          installmentDetail: [],
        },
        {
          paymentMethod: 'QR_CODE',
          priceSummary: {
            interestRate: 0,
            interestAmount: '0',
            processingFeeRate: 0,
            processingFeeAmount: '0',
            feeRate: 0,
            feeAmount: '0',
            discountRate: 0,
            discountAmount: '0',
            netDiscountRate: 0,
            netDiscountAmount: '0',
            packagePriceAfterDiscount: '2100000',
            netPremiumAmount: '2100000',
            initialAmount: '0',
            subsequentAmount: '0',
            discount: null,
            shipmentFee: '0',
            feeAmountNoShip: '0',
          },
          installmentDetail: [],
        },
        {
          paymentMethod: 'BANK_TRANSFER',
          priceSummary: {
            interestRate: 0,
            interestAmount: '0',
            processingFeeRate: 0,
            processingFeeAmount: '0',
            feeRate: 0,
            feeAmount: '0',
            discountRate: 0,
            discountAmount: '0',
            netDiscountRate: 0,
            netDiscountAmount: '0',
            packagePriceAfterDiscount: '2100000',
            netPremiumAmount: '2100000',
            initialAmount: '0',
            subsequentAmount: '0',
            discount: null,
            shipmentFee: '0',
            feeAmountNoShip: '0',
          },
          installmentDetail: [],
        },
        {
          paymentMethod: 'DIRECT_PAYMENT',
          priceSummary: {
            interestRate: 0,
            interestAmount: '0',
            processingFeeRate: 0,
            processingFeeAmount: '0',
            feeRate: 0,
            feeAmount: '0',
            discountRate: 0,
            discountAmount: '0',
            netDiscountRate: 0,
            netDiscountAmount: '0',
            packagePriceAfterDiscount: '2100000',
            netPremiumAmount: '2100000',
            initialAmount: '0',
            subsequentAmount: '0',
            discount: null,
            shipmentFee: '0',
            feeAmountNoShip: '0',
          },
          installmentDetail: [],
        },
        {
          paymentMethod: 'EDC',
          priceSummary: {
            interestRate: 0,
            interestAmount: '0',
            processingFeeRate: 1,
            processingFeeAmount: '21000',
            feeRate: 1,
            feeAmount: '21000',
            discountRate: 0,
            discountAmount: '0',
            netDiscountRate: 1,
            netDiscountAmount: '21000',
            packagePriceAfterDiscount: '2100000',
            netPremiumAmount: '2121000',
            initialAmount: '0',
            subsequentAmount: '0',
            discount: null,
            shipmentFee: '0',
            feeAmountNoShip: '21000',
          },
          installmentDetail: [],
        },
      ],
    },
    rabbitCareInstallment: {
      packagePrice: {
        voluntaryPrice: '2100000',
        compulsoryPrice: '0',
        totalPrice: '2100000',
      },
      availablePlans: [3, 6, 8, 10],
      installmentPlans: [
        {
          numberOfInstallment: 3,
          paymentDetails: [
            {
              paymentMethod: 'QR_CODE',
              priceSummary: {
                interestRate: 0.74,
                interestAmount: '14990',
                processingFeeRate: 0.37,
                processingFeeAmount: '7496',
                feeRate: 1.1,
                feeAmount: '22486',
                discountRate: 3,
                discountAmount: '63000',
                netDiscountRate: -1.93,
                netDiscountAmount: '-40514',
                packagePriceAfterDiscount: '2037000',
                netPremiumAmount: '2059486',
                initialAmount: '686496',
                subsequentAmount: '686495',
                discount: {
                  type: 'DISCOUNT_TYPE_RCL',
                  percentage: 300,
                  amount: '63000',
                },
                shipmentFee: '0',
                feeAmountNoShip: '22486',
              },
              installmentDetail: [
                {
                  period: 1,
                  paymentAmount: '686496',
                  principal: '679000',
                  addOns: '0',
                  interest: '0',
                  processingFee: '7496',
                  principalBalance: '1358000',
                  interestBalance: '14990',
                  processingFeeBalance: '0',
                  totalBalance: '1372990',
                },
                {
                  period: 2,
                  paymentAmount: '686495',
                  principal: '676514',
                  addOns: '0',
                  interest: '9981',
                  processingFee: '0',
                  principalBalance: '681486',
                  interestBalance: '5009',
                  processingFeeBalance: '0',
                  totalBalance: '686495',
                },
                {
                  period: 3,
                  paymentAmount: '686495',
                  principal: '681486',
                  addOns: '0',
                  interest: '5009',
                  processingFee: '0',
                  principalBalance: '0',
                  interestBalance: '0',
                  processingFeeBalance: '0',
                  totalBalance: '0',
                },
              ],
            },
          ],
        },
        {
          numberOfInstallment: 6,
          paymentDetails: [
            {
              paymentMethod: 'QR_CODE',
              priceSummary: {
                interestRate: 2.5,
                interestAmount: '50927',
                processingFeeRate: 0.5,
                processingFeeAmount: '10185',
                feeRate: 3,
                feeAmount: '61112',
                discountRate: 3,
                discountAmount: '63000',
                netDiscountRate: -0.09,
                netDiscountAmount: '-1888',
                packagePriceAfterDiscount: '2037000',
                netPremiumAmount: '2098110',
                initialAmount: '349685',
                subsequentAmount: '349685',
                discount: {
                  type: 'DISCOUNT_TYPE_RCL',
                  percentage: 300,
                  amount: '63000',
                },
                shipmentFee: '0',
                feeAmountNoShip: '61112',
              },
              installmentDetail: [
                {
                  period: 1,
                  paymentAmount: '349685',
                  principal: '339500',
                  addOns: '0',
                  interest: '0',
                  processingFee: '10185',
                  principalBalance: '1697500',
                  interestBalance: '50927',
                  processingFeeBalance: '0',
                  totalBalance: '1748427',
                },
                {
                  period: 2,
                  paymentAmount: '349685',
                  principal: '332821',
                  addOns: '0',
                  interest: '16865',
                  processingFee: '0',
                  principalBalance: '1364679',
                  interestBalance: '34063',
                  processingFeeBalance: '0',
                  totalBalance: '1398742',
                },
                {
                  period: 3,
                  paymentAmount: '349685',
                  principal: '336127',
                  addOns: '0',
                  interest: '13558',
                  processingFee: '0',
                  principalBalance: '1028552',
                  interestBalance: '20505',
                  processingFeeBalance: '0',
                  totalBalance: '1049056',
                },
                {
                  period: 4,
                  paymentAmount: '349685',
                  principal: '339467',
                  addOns: '0',
                  interest: '10219',
                  processingFee: '0',
                  principalBalance: '689085',
                  interestBalance: '10286',
                  processingFeeBalance: '0',
                  totalBalance: '699371',
                },
                {
                  period: 5,
                  paymentAmount: '349685',
                  principal: '342839',
                  addOns: '0',
                  interest: '6846',
                  processingFee: '0',
                  principalBalance: '346246',
                  interestBalance: '3440',
                  processingFeeBalance: '0',
                  totalBalance: '349685',
                },
                {
                  period: 6,
                  paymentAmount: '349685',
                  principal: '346246',
                  addOns: '0',
                  interest: '3440',
                  processingFee: '0',
                  principalBalance: '0',
                  interestBalance: '0',
                  processingFeeBalance: '0',
                  totalBalance: '0',
                },
              ],
            },
          ],
        },
        {
          numberOfInstallment: 8,
          paymentDetails: [
            {
              paymentMethod: 'QR_CODE',
              priceSummary: {
                interestRate: 3.77,
                interestAmount: '79082',
                processingFeeRate: 0.54,
                processingFeeAmount: '11298',
                feeRate: 4.3,
                feeAmount: '90380',
                discountRate: 0,
                discountAmount: '0',
                netDiscountRate: 4.3,
                netDiscountAmount: '90380',
                packagePriceAfterDiscount: '2100000',
                netPremiumAmount: '2190377',
                initialAmount: '273798',
                subsequentAmount: '273797',
                discount: null,
                shipmentFee: '0',
                feeAmountNoShip: '90380',
              },
              installmentDetail: [
                {
                  period: 1,
                  paymentAmount: '273798',
                  principal: '262500',
                  addOns: '0',
                  interest: '0',
                  processingFee: '11298',
                  principalBalance: '1837500',
                  interestBalance: '79082',
                  processingFeeBalance: '0',
                  totalBalance: '1916582',
                },
                {
                  period: 2,
                  paymentAmount: '273797',
                  principal: '254234',
                  addOns: '0',
                  interest: '19563',
                  processingFee: '0',
                  principalBalance: '1583266',
                  interestBalance: '59518',
                  processingFeeBalance: '0',
                  totalBalance: '1642784',
                },
                {
                  period: 3,
                  paymentAmount: '273797',
                  principal: '256941',
                  addOns: '0',
                  interest: '16857',
                  processingFee: '0',
                  principalBalance: '1326325',
                  interestBalance: '42662',
                  processingFeeBalance: '0',
                  totalBalance: '1368987',
                },
                {
                  period: 4,
                  paymentAmount: '273797',
                  principal: '259676',
                  addOns: '0',
                  interest: '14121',
                  processingFee: '0',
                  principalBalance: '1066649',
                  interestBalance: '28541',
                  processingFeeBalance: '0',
                  totalBalance: '1095190',
                },
                {
                  period: 5,
                  paymentAmount: '273797',
                  principal: '262441',
                  addOns: '0',
                  interest: '11356',
                  processingFee: '0',
                  principalBalance: '804207',
                  interestBalance: '17185',
                  processingFeeBalance: '0',
                  totalBalance: '821392',
                },
                {
                  period: 6,
                  paymentAmount: '273797',
                  principal: '265235',
                  addOns: '0',
                  interest: '8562',
                  processingFee: '0',
                  principalBalance: '538972',
                  interestBalance: '8623',
                  processingFeeBalance: '0',
                  totalBalance: '547595',
                },
                {
                  period: 7,
                  paymentAmount: '273797',
                  principal: '268059',
                  addOns: '0',
                  interest: '5738',
                  processingFee: '0',
                  principalBalance: '270913',
                  interestBalance: '2884',
                  processingFeeBalance: '0',
                  totalBalance: '273797',
                },
                {
                  period: 8,
                  paymentAmount: '273797',
                  principal: '270913',
                  addOns: '0',
                  interest: '2884',
                  processingFee: '0',
                  principalBalance: '0',
                  interestBalance: '0',
                  processingFeeBalance: '0',
                  totalBalance: '0',
                },
              ],
            },
          ],
        },
        {
          numberOfInstallment: 10,
          paymentDetails: [
            {
              paymentMethod: 'QR_CODE',
              priceSummary: {
                interestRate: 3.45,
                interestAmount: '72394',
                processingFeeRate: 1.15,
                processingFeeAmount: '24150',
                feeRate: 4.6,
                feeAmount: '96544',
                discountRate: 0,
                discountAmount: '0',
                netDiscountRate: 4.6,
                netDiscountAmount: '96544',
                packagePriceAfterDiscount: '2100000',
                netPremiumAmount: '2196546',
                initialAmount: '549150',
                subsequentAmount: '183044',
                discount: null,
                shipmentFee: '0',
                feeAmountNoShip: '96544',
              },
              installmentDetail: [
                {
                  period: 1,
                  paymentAmount: '549150',
                  principal: '525000',
                  addOns: '0',
                  interest: '0',
                  processingFee: '24150',
                  principalBalance: '1575000',
                  interestBalance: '72394',
                  processingFeeBalance: '0',
                  totalBalance: '1647394',
                },
                {
                  period: 2,
                  paymentAmount: '183044',
                  principal: '168737',
                  addOns: '0',
                  interest: '14306',
                  processingFee: '0',
                  principalBalance: '1406263',
                  interestBalance: '58087',
                  processingFeeBalance: '0',
                  totalBalance: '1464350',
                },
                {
                  period: 3,
                  paymentAmount: '183044',
                  principal: '170270',
                  addOns: '0',
                  interest: '12774',
                  processingFee: '0',
                  principalBalance: '1235992',
                  interestBalance: '45314',
                  processingFeeBalance: '0',
                  totalBalance: '1281306',
                },
                {
                  period: 4,
                  paymentAmount: '183044',
                  principal: '171817',
                  addOns: '0',
                  interest: '11227',
                  processingFee: '0',
                  principalBalance: '1064176',
                  interestBalance: '34087',
                  processingFeeBalance: '0',
                  totalBalance: '1098262',
                },
                {
                  period: 5,
                  paymentAmount: '183044',
                  principal: '173377',
                  addOns: '0',
                  interest: '9666',
                  processingFee: '0',
                  principalBalance: '890798',
                  interestBalance: '24421',
                  processingFeeBalance: '0',
                  totalBalance: '915219',
                },
                {
                  period: 6,
                  paymentAmount: '183044',
                  principal: '174952',
                  addOns: '0',
                  interest: '8091',
                  processingFee: '0',
                  principalBalance: '715846',
                  interestBalance: '16329',
                  processingFeeBalance: '0',
                  totalBalance: '732175',
                },
                {
                  period: 7,
                  paymentAmount: '183044',
                  principal: '176541',
                  addOns: '0',
                  interest: '6502',
                  processingFee: '0',
                  principalBalance: '539304',
                  interestBalance: '9827',
                  processingFeeBalance: '0',
                  totalBalance: '549131',
                },
                {
                  period: 8,
                  paymentAmount: '183044',
                  principal: '178145',
                  addOns: '0',
                  interest: '4899',
                  processingFee: '0',
                  principalBalance: '361159',
                  interestBalance: '4928',
                  processingFeeBalance: '0',
                  totalBalance: '366087',
                },
                {
                  period: 9,
                  paymentAmount: '183044',
                  principal: '179763',
                  addOns: '0',
                  interest: '3281',
                  processingFee: '0',
                  principalBalance: '181396',
                  interestBalance: '1648',
                  processingFeeBalance: '0',
                  totalBalance: '183044',
                },
                {
                  period: 10,
                  paymentAmount: '183044',
                  principal: '181396',
                  addOns: '0',
                  interest: '1648',
                  processingFee: '0',
                  principalBalance: '0',
                  interestBalance: '0',
                  processingFeeBalance: '0',
                  totalBalance: '0',
                },
              ],
            },
          ],
        },
      ],
      directDebitProviders: [
        {
          name: 'card-providers/BAY',
          shortName: 'BAY',
          displayNameTh: 'ธนาคารกรุงศรี',
          displayNameEn: 'Bank of Ayudhya Public Company Limited',
          minimumAmount: '0',
          availablePlans: [3, 6, 8, 10],
          installmentPlans: [
            {
              numberOfInstallment: 3,
              paymentDetails: [
                {
                  paymentMethod: 'DIRECT_DEBIT',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 0,
                    processingFeeAmount: '0',
                    feeRate: 0,
                    feeAmount: '0',
                    discountRate: 3,
                    discountAmount: '55500',
                    netDiscountRate: -2.9,
                    netDiscountAmount: '-55500',
                    packagePriceAfterDiscount: '1859021',
                    netPremiumAmount: '1859021',
                    initialAmount: '662688',
                    subsequentAmount: '598167',
                    discount: {
                      type: 'DISCOUNT_TYPE_RCL',
                      percentage: 300,
                      amount: '55500',
                    },
                    shipmentFee: '0',
                    feeAmountNoShip: '0',
                    vatRate: 7,
                    vatAmount: '125250',
                    stampRate: 0.4,
                    stampAmount: '7200',
                    whtRate: 1,
                    whtAmount: '0',
                  },
                  installmentDetail: [
                    {
                      period: 1,
                      paymentAmount: '662688',
                      principal: '598167',
                      addOns: '64521',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '1196333',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '1196333',
                    },
                    {
                      period: 2,
                      paymentAmount: '598167',
                      principal: '598167',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '598167',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '598167',
                    },
                    {
                      period: 3,
                      paymentAmount: '598167',
                      principal: '598167',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '0',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '0',
                    },
                  ],
                },
              ],
            },
            {
              numberOfInstallment: 6,
              paymentDetails: [
                {
                  paymentMethod: 'DIRECT_DEBIT',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 0,
                    processingFeeAmount: '0',
                    feeRate: 0,
                    feeAmount: '0',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 0,
                    netDiscountAmount: '0',
                    packagePriceAfterDiscount: '1914521',
                    netPremiumAmount: '1914521',
                    initialAmount: '372854',
                    subsequentAmount: '308333',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '0',
                    vatRate: 7,
                    vatAmount: '125250',
                    stampRate: 0.4,
                    stampAmount: '7200',
                    whtRate: 1,
                    whtAmount: '0',
                  },
                  installmentDetail: [
                    {
                      period: 1,
                      paymentAmount: '372854',
                      principal: '308333',
                      addOns: '64521',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '1541667',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '1541667',
                    },
                    {
                      period: 2,
                      paymentAmount: '308333',
                      principal: '308333',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '1233333',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '1233333',
                    },
                    {
                      period: 3,
                      paymentAmount: '308333',
                      principal: '308333',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '925000',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '925000',
                    },
                    {
                      period: 4,
                      paymentAmount: '308333',
                      principal: '308333',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '616667',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '616667',
                    },
                    {
                      period: 5,
                      paymentAmount: '308333',
                      principal: '308333',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '308333',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '308333',
                    },
                    {
                      period: 6,
                      paymentAmount: '308333',
                      principal: '308333',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '0',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '0',
                    },
                  ],
                },
              ],
            },
            {
              numberOfInstallment: 8,
              paymentDetails: [
                {
                  paymentMethod: 'DIRECT_DEBIT',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 0,
                    processingFeeAmount: '0',
                    feeRate: 0,
                    feeAmount: '0',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 0,
                    netDiscountAmount: '0',
                    packagePriceAfterDiscount: '1914521',
                    netPremiumAmount: '1914521',
                    initialAmount: '295771',
                    subsequentAmount: '231250',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '0',
                    vatRate: 7,
                    vatAmount: '125250',
                    stampRate: 0.4,
                    stampAmount: '7200',
                    whtRate: 1,
                    whtAmount: '0',
                  },
                  installmentDetail: [
                    {
                      period: 1,
                      paymentAmount: '295771',
                      principal: '231250',
                      addOns: '64521',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '1618750',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '1618750',
                    },
                    {
                      period: 2,
                      paymentAmount: '231250',
                      principal: '231250',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '1387500',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '1387500',
                    },
                    {
                      period: 3,
                      paymentAmount: '231250',
                      principal: '231250',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '1156250',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '1156250',
                    },
                    {
                      period: 4,
                      paymentAmount: '231250',
                      principal: '231250',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '925000',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '925000',
                    },
                    {
                      period: 5,
                      paymentAmount: '231250',
                      principal: '231250',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '693750',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '693750',
                    },
                    {
                      period: 6,
                      paymentAmount: '231250',
                      principal: '231250',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '462500',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '462500',
                    },
                    {
                      period: 7,
                      paymentAmount: '231250',
                      principal: '231250',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '231250',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '231250',
                    },
                    {
                      period: 8,
                      paymentAmount: '231250',
                      principal: '231250',
                      addOns: '0',
                      interest: '0',
                      processingFee: '0',
                      principalBalance: '0',
                      interestBalance: '0',
                      processingFeeBalance: '0',
                      totalBalance: '0',
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    creditCardInstallment: {
      packagePrice: {
        voluntaryPrice: '2100000',
        compulsoryPrice: '0',
        totalPrice: '2100000',
      },
      cardProviders: [
        {
          name: 'card-providers/BAY',
          shortName: 'BAY',
          displayNameTh: 'ธนาคารกรุงศรี',
          displayNameEn: 'Bank of Ayudhya Public Company Limited',
          minimumAmount: '0',
          availablePlans: [3, 6, 10],
          installmentPlans: [
            {
              numberOfInstallment: 3,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 6,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 10,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
          ],
        },
        {
          name: 'card-providers/BBL',
          shortName: 'BBL',
          displayNameTh: 'ธนาคารกรุงเทพ',
          displayNameEn: 'Bangkok Bank Public Company Limited',
          minimumAmount: '0',
          availablePlans: [4, 6, 10],
          installmentPlans: [
            {
              numberOfInstallment: 4,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '530250',
                    subsequentAmount: '530250',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '530250',
                    subsequentAmount: '530250',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 6,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 10,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
          ],
        },
        {
          name: 'card-providers/FIRST_CHOICE',
          shortName: 'FIRST_CHOICE',
          displayNameTh: 'กรุงศรีเฟิร์สช้อยส์',
          displayNameEn: 'Krungsri First Choice',
          minimumAmount: '0',
          availablePlans: [3, 6, 10],
          installmentPlans: [
            {
              numberOfInstallment: 3,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 6,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 10,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
          ],
        },
        {
          name: 'card-providers/KBANK',
          shortName: 'KBANK',
          displayNameTh: 'ธนาคารกสิกร',
          displayNameEn: 'Kasikornbank Public Company Limited',
          minimumAmount: '0',
          availablePlans: [3, 6, 10],
          installmentPlans: [
            {
              numberOfInstallment: 3,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 6,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 10,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
          ],
        },
        {
          name: 'card-providers/KTC',
          shortName: 'KTC',
          displayNameTh: 'บัตรกรุงไทย',
          displayNameEn: 'Krungthai Card',
          minimumAmount: '0',
          availablePlans: [3, 6, 10],
          installmentPlans: [
            {
              numberOfInstallment: 3,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 6,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 10,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
          ],
        },
        {
          name: 'card-providers/SCB',
          shortName: 'SCB',
          displayNameTh: 'ธนาคารไทยพาณิชย์',
          displayNameEn: 'The Siam Commercial Bank Public Company Limited',
          minimumAmount: '0',
          availablePlans: [3, 6, 10],
          installmentPlans: [
            {
              numberOfInstallment: 3,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 6,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 10,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
          ],
        },
        {
          name: 'card-providers/TTB',
          shortName: 'TTB',
          displayNameTh: 'ธนาคารทหารไทยธนชาต',
          displayNameEn: 'TMBThanachart',
          minimumAmount: '0',
          availablePlans: [3, 6, 10],
          installmentPlans: [
            {
              numberOfInstallment: 3,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '707000',
                    subsequentAmount: '707000',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 6,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '353500',
                    subsequentAmount: '353500',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
            {
              numberOfInstallment: 10,
              paymentDetails: [
                {
                  paymentMethod: 'EDC',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
                {
                  paymentMethod: 'ONLINECARD',
                  priceSummary: {
                    interestRate: 0,
                    interestAmount: '0',
                    processingFeeRate: 1,
                    processingFeeAmount: '21000',
                    feeRate: 1,
                    feeAmount: '21000',
                    discountRate: 0,
                    discountAmount: '0',
                    netDiscountRate: 1,
                    netDiscountAmount: '21000',
                    packagePriceAfterDiscount: '2100000',
                    netPremiumAmount: '2121000',
                    initialAmount: '212100',
                    subsequentAmount: '212100',
                    discount: null,
                    shipmentFee: '0',
                    feeAmountNoShip: '21000',
                  },
                  installmentDetail: [],
                },
              ],
            },
          ],
        },
      ],
    },
  },
  packageDetails: {
    paymentOption: 'FULL_PAYMENT',
    paymentMethod: 'ONLINECARD',
    numberOfInstallments: 1,
    cardProvider: 'card-providers/BAY',
    priceDetails: {
      resourceName: 'customPackages/9c42ba72-8967-41c7-8041-5c239d750a37',
      priceSummary: {
        interestRate: 0,
        interestAmount: '0',
        processingFeeRate: 1,
        processingFeeAmount: '21000',
        feeRate: 1,
        feeAmount: '21000',
        discountRate: 0,
        discountAmount: '0',
        netDiscountRate: 1,
        netDiscountAmount: '21000',
        packagePriceAfterDiscount: '2100000',
        netPremiumAmount: '2121000',
        initialAmount: '0',
        subsequentAmount: '0',
        discount: null,
        shipmentFee: '0',
        feeAmountNoShip: '21000',
      },
      installmentDetails: [],
    },
  },
  paymentDetails: {
    paidCharges: [
      {
        name: 'transactions/3e0b1419-faad-4356-89fc-3f0f0c6abffb/charges/7e36fb1d-0ccd-44e8-9753-03cf061593b8',
        createTime: '2024-02-27T12:56:15.253879Z',
        updateTime: '2024-02-27T15:04:40.925391Z',
        money: {
          currencyCode: 'THB',
          amount: '656500',
        },
        serviceProvider: 'RCB',
        paymentMethod: 'ONLINECARD',
        returnUri: '',
        authorizeUri:
          'https://api.omise.co/payments/paym_test_5ywsyfu4kp2kjxxobaz/authorize',
        token: '',
        status: 'SUCCESSFUL',
        thirdPartyId: 'chrg_test_5ywsyfu37meszzamw1p',
        sourceUri: '',
        errorCode: '',
        httpStatusCode: 200,
        errorMessage: '',
        installmentNumber: 1,
        cardToken: '',
        dueDate: null,
        slipIdResource: '',
        sendSms: false,
        paymentDate: null,
      },
      {
        name: 'transactions/d13e2926-0b20-4bbc-821a-e00f9eb82be6/charges/98dceb26-c8db-45dc-92e7-996ac23d769d',
        createTime: '2024-02-27T12:56:15.253879Z',
        updateTime: '2024-02-27T12:56:17.686904Z',
        money: {
          currencyCode: 'THB',
          amount: '656500',
        },
        serviceProvider: 'RCB',
        paymentMethod: 'ONLINECARD',
        returnUri: '',
        authorizeUri:
          'https://api.omise.co/payments/paym_test_5ywsyfu4kp2kjxxobaz/authorize',
        token: '',
        status: 'SUCCESSFUL',
        thirdPartyId: 'chrg_test_5ywsyfu37meszzamw1p',
        sourceUri: '',
        errorCode: '',
        httpStatusCode: 200,
        errorMessage: '',
        installmentNumber: 1,
        cardToken: '',
        dueDate: null,
        slipIdResource: '',
        sendSms: false,
        paymentDate: null,
      },
    ],
    firstMonthRemainingAmount: {
      currencyCode: 'THB',
      amount: '808000',
    },
    nextMonthsRemainingAmount: null,
    referenceLeadId: 'L9910405',
    paidAmount: '1313000',
    additionalPaymentAmount: '808000',
  },
} as unknown as LeadPaymentInformation;

export const mockNewLeadPaymentInformationChangeOrder = {
  quote: 'customPackages/5eb79411-adbc-40dd-8e68-6a892c3adccf',
  paidCharges: [
    {
      name: 'transactions/8a65ee7a-6f58-4ec0-b250-6a67762db169/charges/cc2bb247-a704-44bc-8bbb-e3b6369376c6',
      createTime: '2024-07-24T05:32:52.454018Z',
      updateTime: '2024-07-24T05:32:56.365067Z',
      money: {
        currencyCode: 'THB',
        amount: '2287166',
      },
      serviceProvider: 'RCB',
      paymentMethod: 'ONLINECARD',
      returnUri: '',
      authorizeUri:
        'https://api.omise.co/payments/paym_test_60ikkmtyzy74l9dqi6c/authorize',
      token: '',
      status: 'SUCCESSFUL',
      thirdPartyId: 'chrg_test_60ikkmtxbq344r6tzea',
      sourceUri: '',
      errorCode: '',
      httpStatusCode: 200,
      errorMessage: '',
      installmentNumber: 1,
      cardToken: '',
      dueDate: '1970-01-01T00:00:00Z',
      slipIdResource: '',
      sendSms: false,
      paymentDate: '2024-07-24T05:32:53Z',
    },
  ],
  refunds: [],
  parentLeadPayment: {
    lead: '',
    paidCharges: [],
    refunds: [],
    credits: [],
  },
  totalPaidAmount: {
    currencyCode: 'THB',
    amount: '2287166',
  },
  totalRefundedAmount: {
    currencyCode: 'THB',
    amount: '0',
  },
  totalPayableAmount: {
    currencyCode: 'THB',
    amount: '87166',
  },
  termUnpaidAmount: {
    currencyCode: 'THB',
    amount: '87166',
  },
  term: 1,
  credits: [
    {
      name: 'leads/643ec480-0146-437f-a44b-397289859e74/credits/d31dfdc9-23be-412c-b901-b653e0c174b9',
      money: {
        currencyCode: 'THB',
        amount: '2200000',
      },
      status: 'STATUS_PENDING',
      createTime: '2024-07-24T05:34:05.439052Z',
      updateTime: '2024-07-24T05:34:05.439052Z',
      deleteTime: null,
    },
  ],
  totalCreditAmount: {
    currencyCode: 'THB',
    amount: '2200000',
  },
} as unknown as NewLeadPaymentInformation;
