export const leadFilterConfigMock = {
  sort: {
    title: 'leadPackageFilter.sortBy',
    tooltip: 'leadPackageFilter.tooltip.sortBy',
    type: 'selectbox',
    values: [
      {
        key: 'default',
        label: 'text.select',
      },
      {
        key: 'insurer',
        label: 'newPackageListing.insurer',
      },
      {
        key: 'package_name',
        label: 'newPackageListing.displayName',
      },
      {
        key: 'insurer_type',
        label: 'newPackageListing.insuranceType',
      },
      {
        key: 'repair_type',
        label: 'newPackageListing.repairType',
      },
      {
        key: 'car_coverage',
        label: 'newPackageListing.carCoverage',
      },
      {
        key: 'deductible',
        label: 'newPackageListing.deductible',
      },
      {
        key: 'price',
        label: 'newPackageListing.price',
      },
      {
        key: 'paymentPlan',
        label: 'newPackageListing.paymentPlan',
      },
      {
        key: 'shippingFee',
        label: 'newPackageListing.shippingFee',
      },
      {
        key: 'discount',
        label: 'newPackageListing.discount',
      },
      {
        key: 'processingFee',
        label: 'newPackageListing.processingFee',
      },
      {
        key: 'premium',
        label: 'newPackageListing.invoicedAmount',
      },
    ],
  },
  order: {
    title: 'leadPackageFilter.orderBy',
    tooltip: '',
    type: 'selectbox',
    values: [
      {
        key: 'default',
        label: 'text.select',
      },
      {
        key: 'asc',
        label: 'asc',
      },
      {
        key: 'desc',
        label: 'desc',
      },
    ],
  },
  paymentOption: {
    title: 'leadPackageFilter.paymentOption',
    tooltip: 'leadPackageFilter.tooltip.paymentOption',
    type: 'selectbox',
    options: [],
  },
  installment: {
    title: 'leadPackageFilter.numberOfInstallment',
    tooltip: 'leadPackageFilter.tooltip.installmentOption',
    type: 'selectbox',
    options: [],
  },
  insuranceType: {
    title: 'leadPackageFilter.insuranceType',
    tooltip: 'leadPackageFilter.tooltip.insuranceType',
    type: 'checkbox',
    values: [
      {
        key: 'Type 1',
        label: 'leadPackageFilter.possibleValue.insuranceType.type1',
      },
      {
        key: 'Type 2+',
        label: 'leadPackageFilter.possibleValue.insuranceType.type2+',
      },
      {
        key: 'Type 3+',
        label: 'leadPackageFilter.possibleValue.insuranceType.type3+',
      },
      {
        key: 'Type 2',
        label: 'leadPackageFilter.possibleValue.insuranceType.type2',
      },
      {
        key: 'Type 3',
        label: 'leadPackageFilter.possibleValue.insuranceType.type3',
      },
      {
        key: 'mandatory',
        label: 'leadPackageFilter.possibleValue.insuranceType.compulsory',
      },
    ],
  },
  insurer: {
    title: 'leadPackageFilter.insurer',
    tooltip: 'leadPackageFilter.tooltip.insurer',
    type: 'checkbox',
    values: [
      {
        key: 'insurers/7',
        label: 'Bangkok Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/7.png',
      },
      {
        key: 'insurers/27',
        label: 'Viriyah Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/27.png',
      },
      {
        key: 'insurers/28',
        label: 'Thanachart Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/28.png',
      },
      {
        key: 'insurers/35',
        label: 'Tokio Marine Safety Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/35.png',
      },
      {
        key: 'insurers/24',
        label: 'ERGO Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/24.png',
      },
      {
        key: 'insurers/19',
        label: 'Southeast Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/19.png',
      },
      {
        key: 'insurers/11',
        label: 'Dhipaya Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/11.png',
      },
      {
        key: 'insurers/6',
        label: 'AXA Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/6.png',
      },
      {
        key: 'insurers/33',
        label: 'LMG Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/33.png',
      },
      {
        key: 'insurers/17',
        label: 'Muang Thai Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/17.png',
      },
      {
        key: 'insurers/31',
        label: 'Navakij Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/31.png',
      },
      {
        key: 'insurers/25',
        label: 'Thaivivat Insurance',
        logo: 'https://storage.googleapis.com/skillful-rush/insurers/25.png',
      },
    ],
  },
  repairType: {
    title: 'leadPackageFilter.repairType',
    tooltip: 'leadPackageFilter.tooltip.repairType',
    type: 'checkbox',
    values: [
      {
        key: 'Dealer',
        label: 'leadPackageFilter.possibleValue.repairType.dealer',
      },
      {
        key: 'Garage',
        label: 'leadPackageFilter.possibleValue.repairType.garage',
      },
    ],
  },
  sumInsured: {
    title: 'leadPackageFilter.sumInsured',
    tooltip: 'leadPackageFilter.tooltip.sumInsured',
    type: 'slidebar',
    config: {
      min: 0,
      max: 450000,
      step: 10000,
    },
  },
  price: {
    title: 'leadPackageFilter.price',
    tooltip: 'leadPackageFilter.tooltip.price',
    type: 'slidebar',
    config: {
      min: 645,
      max: 54033,
      step: 1,
    },
  },
  deductible: {
    title: 'leadPackageFilter.deductible',
    tooltip: 'leadPackageFilter.tooltip.deductible',
    type: 'checkbox',
    values: [
      {
        key: 'no_deductible',
        label: 'leadPackageFilter.possibleValue.deductible.noDeductible',
      },
      {
        key: 'only_deductible',
        label: 'leadPackageFilter.possibleValue.deductible.onlyDeductible',
      },
    ],
  },
  brand: {
    title: 'leadDetailFields.brand',
    tooltip: '',
    type: 'selectbox',
    options: [
      {
        key: '0',
        label: 'Please Select',
      },
      {
        id: 54,
        value: 54,
        title: 'Toyota',
        key: 54,
        label: 'Toyota',
      },
      {
        id: 24,
        value: 24,
        title: 'Honda',
        key: 24,
        label: 'Honda',
      },
      {
        id: 26,
        value: 26,
        title: 'Isuzu',
        key: 26,
        label: 'Isuzu',
      },
      {
        id: 33,
        value: 33,
        title: 'Mazda',
        key: 33,
        label: 'Mazda',
      },
      {
        id: 38,
        value: 38,
        title: 'Nissan',
        key: 38,
        label: 'Nissan',
      },
      {
        id: 35,
        value: 35,
        title: 'Mitsubishi',
        key: 35,
        label: 'Mitsubishi',
      },
      {
        id: 1,
        value: 1,
        title: 'Aston Martin',
        key: 1,
        label: 'Aston Martin',
      },
      {
        id: 10,
        value: 10,
        title: 'Audi',
        key: 10,
        label: 'Audi',
      },
      {
        id: 2,
        value: 2,
        title: 'Bentley',
        key: 2,
        label: 'Bentley',
      },
      {
        id: 3,
        value: 3,
        title: 'BMW',
        key: 3,
        label: 'BMW',
      },
      {
        id: 12,
        value: 12,
        title: 'Chevrolet',
        key: 12,
        label: 'Chevrolet',
      },
      {
        id: 17,
        value: 17,
        title: 'DFM',
        key: 17,
        label: 'DFM',
      },
      {
        id: 75,
        value: 75,
        title: 'Ducati',
        key: 75,
        label: 'Ducati',
      },
      {
        id: 18,
        value: 18,
        title: 'Ferrari',
        key: 18,
        label: 'Ferrari',
      },
      {
        id: 20,
        value: 20,
        title: 'Ford',
        key: 20,
        label: 'Ford',
      },
      {
        id: 23,
        value: 23,
        title: 'Foton',
        key: 23,
        label: 'Foton',
      },
      {
        id: 76,
        value: 76,
        title: 'GPX',
        key: 76,
        label: 'GPX',
      },
      {
        id: 77,
        value: 77,
        title: 'Harley-davidson',
        key: 77,
        label: 'Harley-davidson',
      },
      {
        id: 4,
        value: 4,
        title: 'Hyundai',
        key: 4,
        label: 'Hyundai',
      },
      {
        id: 25,
        value: 25,
        title: 'Jaguar',
        key: 25,
        label: 'Jaguar',
      },
      {
        id: 78,
        value: 78,
        title: 'Kawasaki',
        key: 78,
        label: 'Kawasaki',
      },
      {
        id: 5,
        value: 5,
        title: 'Kia',
        key: 5,
        label: 'Kia',
      },
      {
        id: 28,
        value: 28,
        title: 'Lamborghini',
        key: 28,
        label: 'Lamborghini',
      },
      {
        id: 29,
        value: 29,
        title: 'Land Rover',
        key: 29,
        label: 'Land Rover',
      },
      {
        id: 30,
        value: 30,
        title: 'Lexus',
        key: 30,
        label: 'Lexus',
      },
      {
        id: 32,
        value: 32,
        title: 'Maserati',
        key: 32,
        label: 'Maserati',
      },
      {
        id: 58,
        value: 58,
        title: 'Maxus',
        key: 58,
        label: 'Maxus',
      },
      {
        id: 59,
        value: 59,
        title: 'McLaren',
        key: 59,
        label: 'McLaren',
      },
      {
        id: 6,
        value: 6,
        title: 'Mercedes-Benz',
        key: 6,
        label: 'Mercedes-Benz',
      },
      {
        id: 60,
        value: 60,
        title: 'MG',
        key: 60,
        label: 'MG',
      },
      {
        id: 34,
        value: 34,
        title: 'Mini',
        key: 34,
        label: 'Mini',
      },
      {
        id: 40,
        value: 40,
        title: 'Peugeot',
        key: 40,
        label: 'Peugeot',
      },
      {
        id: 42,
        value: 42,
        title: 'Porsche',
        key: 42,
        label: 'Porsche',
      },
      {
        id: 7,
        value: 7,
        title: 'Proton',
        key: 7,
        label: 'Proton',
      },
      {
        id: 44,
        value: 44,
        title: 'Rolls-Royce',
        key: 44,
        label: 'Rolls-Royce',
      },
      {
        id: 81,
        value: 81,
        title: 'Royal Enfield',
        key: 81,
        label: 'Royal Enfield',
      },
      {
        id: 51,
        value: 51,
        title: 'Ssangyong',
        key: 51,
        label: 'Ssangyong',
      },
      {
        id: 52,
        value: 52,
        title: 'Subaru',
        key: 52,
        label: 'Subaru',
      },
      {
        id: 8,
        value: 8,
        title: 'Suzuki',
        key: 8,
        label: 'Suzuki',
      },
      {
        id: 53,
        value: 53,
        title: 'Tata',
        key: 53,
        label: 'Tata',
      },
      {
        id: 55,
        value: 55,
        title: 'TR',
        key: 55,
        label: 'TR',
      },
      {
        id: 79,
        value: 79,
        title: 'Triumph',
        key: 79,
        label: 'Triumph',
      },
      {
        id: 80,
        value: 80,
        title: 'Vespa',
        key: 80,
        label: 'Vespa',
      },
      {
        id: 56,
        value: 56,
        title: 'Volkswagen',
        key: 56,
        label: 'Volkswagen',
      },
      {
        id: 57,
        value: 57,
        title: 'Volvo',
        key: 57,
        label: 'Volvo',
      },
      {
        id: 74,
        value: 74,
        title: 'Yamaha',
        key: 74,
        label: 'Yamaha',
      },
    ],
  },
  subModel: {
    title: 'leadDetailFields.subModel',
    tooltip: '',
    type: 'selectbox',
    options: [
      {
        key: '0',
        label: 'Please Select',
      },
      {
        id: 0,
        value: 20412,
        title: 'Jan Sedan 4dr S CVT 7sp Front Wheel Drive 1.5i',
        engineSize: 1500,
        doors: 4,
        key: 20412,
        label: 'Jan Sedan 4dr S CVT 7sp Front Wheel Drive 1.5i',
      },
      {
        id: 1,
        value: 20409,
        title: 'Jan Sedan 4dr J CVT 7sp Front Wheel Drive 1.5i',
        engineSize: 1500,
        doors: 4,
        key: 20409,
        label: 'Jan Sedan 4dr J CVT 7sp Front Wheel Drive 1.5i',
      },
      {
        id: 2,
        value: 20410,
        title: 'Jan Sedan 4dr E CVT 7sp Front Wheel Drive 1.5i',
        engineSize: 1500,
        doors: 4,
        key: 20410,
        label: 'Jan Sedan 4dr E CVT 7sp Front Wheel Drive 1.5i',
      },
      {
        id: 3,
        value: 20411,
        title: 'Jan Sedan 4dr G CVT 7sp Front Wheel Drive 1.5i',
        engineSize: 1500,
        doors: 4,
        key: 20411,
        label: 'Jan Sedan 4dr G CVT 7sp Front Wheel Drive 1.5i',
      },
      {
        id: 4,
        value: 40005,
        title: 'Aug Sedan 4dr GT Street CVT 7sp Front Wheel Drive 1.5i',
        engineSize: 1500,
        doors: 4,
        key: 40005,
        label: 'Aug Sedan 4dr GT Street CVT 7sp Front Wheel Drive 1.5i',
      },
      {
        id: 5,
        value: 46921,
        title: '1500 CC (4 Doors) J',
        engineSize: 1500,
        doors: 4,
        key: 46921,
        label: '1500 CC (4 Doors) J',
      },
      {
        id: 6,
        value: 46924,
        title: '1500 CC (4 Doors) S',
        engineSize: 1500,
        doors: 4,
        key: 46924,
        label: '1500 CC (4 Doors) S',
      },
      {
        id: 7,
        value: 46923,
        title: '1500 CC (4 Doors) G',
        engineSize: 1500,
        doors: 4,
        key: 46923,
        label: '1500 CC (4 Doors) G',
      },
      {
        id: 8,
        value: 46922,
        title: '1500 CC (4 Doors) E',
        engineSize: 1500,
        doors: 4,
        key: 46922,
        label: '1500 CC (4 Doors) E',
      },
    ],
  },
  model: {
    title: 'leadDetailFields.model',
    tooltip: '',
    type: 'selectbox',
    options: [
      {
        key: '0',
        label: 'Please Select',
      },
      {
        id: 613,
        value: 613,
        title: 'Corolla Altis',
        key: 613,
        label: 'Corolla Altis',
      },
      {
        id: 616,
        value: 616,
        title: 'Fortuner',
        key: 616,
        label: 'Fortuner',
      },
      {
        id: 756,
        value: 756,
        title: 'Hilux Revo',
        key: 756,
        label: 'Hilux Revo',
      },
      {
        id: 632,
        value: 632,
        title: 'Vios',
        key: 632,
        label: 'Vios',
      },
      {
        id: 635,
        value: 635,
        title: 'Yaris',
        key: 635,
        label: 'Yaris',
      },
      {
        id: 608,
        value: 608,
        title: 'Alphard',
        key: 608,
        label: 'Alphard',
      },
      {
        id: 609,
        value: 609,
        title: 'Avanza',
        key: 609,
        label: 'Avanza',
      },
      {
        id: 610,
        value: 610,
        title: 'Camry',
        key: 610,
        label: 'Camry',
      },
      {
        id: 1223,
        value: 1223,
        title: 'C-HR',
        key: 1223,
        label: 'C-HR',
      },
      {
        id: 612,
        value: 612,
        title: 'Commuter',
        key: 612,
        label: 'Commuter',
      },
      {
        id: 618,
        value: 618,
        title: 'Hiace',
        key: 618,
        label: 'Hiace',
      },
      {
        id: 622,
        value: 622,
        title: 'Innova',
        key: 622,
        label: 'Innova',
      },
      {
        id: 1138,
        value: 1138,
        title: 'Sienta',
        key: 1138,
        label: 'Sienta',
      },
      {
        id: 755,
        value: 755,
        title: 'Vellfire',
        key: 755,
        label: 'Vellfire',
      },
      {
        id: 631,
        value: 631,
        title: 'Ventury',
        key: 631,
        label: 'Ventury',
      },
      {
        id: 1150,
        value: 1150,
        title: 'Yaris Ativ',
        key: 1150,
        label: 'Yaris Ativ',
      },
    ],
  },
  year: {
    title: 'leadDetailFields.year',
    tooltip: '',
    type: 'selectbox',
    options: [
      {
        key: '0',
        label: 'Please Select',
      },
      {
        id: 0,
        value: 2031,
        title: '2031',
        key: 2031,
        label: '2031',
      },
      {
        id: 1,
        value: 2030,
        title: '2030',
        key: 2030,
        label: '2030',
      },
      {
        id: 2,
        value: 2029,
        title: '2029',
        key: 2029,
        label: '2029',
      },
      {
        id: 3,
        value: 2028,
        title: '2028',
        key: 2028,
        label: '2028',
      },
      {
        id: 4,
        value: 2027,
        title: '2027',
        key: 2027,
        label: '2027',
      },
      {
        id: 5,
        value: 2026,
        title: '2026',
        key: 2026,
        label: '2026',
      },
      {
        id: 6,
        value: 2025,
        title: '2025',
        key: 2025,
        label: '2025',
      },
      {
        id: 7,
        value: 2024,
        title: '2024',
        key: 2024,
        label: '2024',
      },
      {
        id: 8,
        value: 2023,
        title: '2023',
        key: 2023,
        label: '2023',
      },
      {
        id: 9,
        value: 2022,
        title: '2022',
        key: 2022,
        label: '2022',
      },
      {
        id: 10,
        value: 2021,
        title: '2021',
        key: 2021,
        label: '2021',
      },
      {
        id: 11,
        value: 2020,
        title: '2020',
        key: 2020,
        label: '2020',
      },
      {
        id: 12,
        value: 2019,
        title: '2019',
        key: 2019,
        label: '2019',
      },
      {
        id: 13,
        value: 2018,
        title: '2018',
        key: 2018,
        label: '2018',
      },
      {
        id: 14,
        value: 2017,
        title: '2017',
        key: 2017,
        label: '2017',
      },
      {
        id: 15,
        value: 2016,
        title: '2016',
        key: 2016,
        label: '2016',
      },
      {
        id: 16,
        value: 2015,
        title: '2015',
        key: 2015,
        label: '2015',
      },
      {
        id: 17,
        value: 2014,
        title: '2014',
        key: 2014,
        label: '2014',
      },
      {
        id: 18,
        value: 2013,
        title: '2013',
        key: 2013,
        label: '2013',
      },
      {
        id: 19,
        value: 2012,
        title: '2012',
        key: 2012,
        label: '2012',
      },
      {
        id: 20,
        value: 2011,
        title: '2011',
        key: 2011,
        label: '2011',
      },
      {
        id: 21,
        value: 2010,
        title: '2010',
        key: 2010,
        label: '2010',
      },
      {
        id: 22,
        value: 2009,
        title: '2009',
        key: 2009,
        label: '2009',
      },
      {
        id: 23,
        value: 2008,
        title: '2008',
        key: 2008,
        label: '2008',
      },
      {
        id: 24,
        value: 2007,
        title: '2007',
        key: 2007,
        label: '2007',
      },
      {
        id: 25,
        value: 2006,
        title: '2006',
        key: 2006,
        label: '2006',
      },
      {
        id: 26,
        value: 2005,
        title: '2005',
        key: 2005,
        label: '2005',
      },
      {
        id: 27,
        value: 2004,
        title: '2004',
        key: 2004,
        label: '2004',
      },
      {
        id: 28,
        value: 2003,
        title: '2003',
        key: 2003,
        label: '2003',
      },
      {
        id: 29,
        value: 2002,
        title: '2002',
        key: 2002,
        label: '2002',
      },
      {
        id: 30,
        value: 2001,
        title: '2001',
        key: 2001,
        label: '2001',
      },
      {
        id: 31,
        value: 2000,
        title: '2000',
        key: 2000,
        label: '2000',
      },
      {
        id: 32,
        value: 1999,
        title: '1999',
        key: 1999,
        label: '1999',
      },
      {
        id: 33,
        value: 1998,
        title: '1998',
        key: 1998,
        label: '1998',
      },
      {
        id: 34,
        value: 1997,
        title: '1997',
        key: 1997,
        label: '1997',
      },
      {
        id: 35,
        value: 1996,
        title: '1996',
        key: 1996,
        label: '1996',
      },
      {
        id: 36,
        value: 1995,
        title: '1995',
        key: 1995,
        label: '1995',
      },
      {
        id: 37,
        value: 1994,
        title: '1994',
        key: 1994,
        label: '1994',
      },
      {
        id: 38,
        value: 1993,
        title: '1993',
        key: 1993,
        label: '1993',
      },
      {
        id: 39,
        value: 1992,
        title: '1992',
        key: 1992,
        label: '1992',
      },
      {
        id: 40,
        value: 1977,
        title: '1977',
        key: 1977,
        label: '1977',
      },
    ],
  },
  province: {
    title: 'leadDetailFields.province',
    tooltip: '',
    type: 'selectbox',
    options: [
      {
        key: '0',
        label: 'Please Select',
      },
      {
        id: 0,
        value: 370000,
        title: 'Amnat Charoen',
        key: 370000,
        label: 'Amnat Charoen',
      },
      {
        id: 1,
        value: 150000,
        title: 'Ang Thong',
        key: 150000,
        label: 'Ang Thong',
      },
      {
        id: 2,
        value: 100000,
        title: 'Bangkok',
        key: 100000,
        label: 'Bangkok',
      },
      {
        id: 3,
        value: 380000,
        title: 'Bueng Kan',
        key: 380000,
        label: 'Bueng Kan',
      },
      {
        id: 4,
        value: 310000,
        title: 'Buri Ram',
        key: 310000,
        label: 'Buri Ram',
      },
      {
        id: 5,
        value: 240000,
        title: 'Chachoengsao',
        key: 240000,
        label: 'Chachoengsao',
      },
      {
        id: 6,
        value: 180000,
        title: 'Chai Nat',
        key: 180000,
        label: 'Chai Nat',
      },
      {
        id: 7,
        value: 360000,
        title: 'Chaiyaphum',
        key: 360000,
        label: 'Chaiyaphum',
      },
      {
        id: 8,
        value: 220000,
        title: 'Chanthaburi',
        key: 220000,
        label: 'Chanthaburi',
      },
      {
        id: 9,
        value: 500000,
        title: 'Chiang Mai',
        key: 500000,
        label: 'Chiang Mai',
      },
      {
        id: 10,
        value: 570000,
        title: 'Chiang Rai',
        key: 570000,
        label: 'Chiang Rai',
      },
      {
        id: 11,
        value: 200000,
        title: 'Chon Buri',
        key: 200000,
        label: 'Chon Buri',
      },
      {
        id: 12,
        value: 860000,
        title: 'Chumphon',
        key: 860000,
        label: 'Chumphon',
      },
      {
        id: 13,
        value: 460000,
        title: 'Kalasin',
        key: 460000,
        label: 'Kalasin',
      },
      {
        id: 14,
        value: 620000,
        title: 'Kamphaeng Phet',
        key: 620000,
        label: 'Kamphaeng Phet',
      },
      {
        id: 15,
        value: 710000,
        title: 'Kanchanaburi',
        key: 710000,
        label: 'Kanchanaburi',
      },
      {
        id: 16,
        value: 400000,
        title: 'Khon Kaen',
        key: 400000,
        label: 'Khon Kaen',
      },
      {
        id: 17,
        value: 810000,
        title: 'Krabi',
        key: 810000,
        label: 'Krabi',
      },
      {
        id: 18,
        value: 520000,
        title: 'Lampang',
        key: 520000,
        label: 'Lampang',
      },
      {
        id: 19,
        value: 510000,
        title: 'Lamphun',
        key: 510000,
        label: 'Lamphun',
      },
      {
        id: 20,
        value: 420000,
        title: 'Loei',
        key: 420000,
        label: 'Loei',
      },
      {
        id: 21,
        value: 160000,
        title: 'Lop Buri',
        key: 160000,
        label: 'Lop Buri',
      },
      {
        id: 22,
        value: 580000,
        title: 'Mae Hong Son',
        key: 580000,
        label: 'Mae Hong Son',
      },
      {
        id: 23,
        value: 440000,
        title: 'Maha Sarakham',
        key: 440000,
        label: 'Maha Sarakham',
      },
      {
        id: 24,
        value: 490000,
        title: 'Mukdahan',
        key: 490000,
        label: 'Mukdahan',
      },
      {
        id: 25,
        value: 260000,
        title: 'Nakhon Nayok',
        key: 260000,
        label: 'Nakhon Nayok',
      },
      {
        id: 26,
        value: 730000,
        title: 'Nakhon Pathom',
        key: 730000,
        label: 'Nakhon Pathom',
      },
      {
        id: 27,
        value: 480000,
        title: 'Nakhon Phanom',
        key: 480000,
        label: 'Nakhon Phanom',
      },
      {
        id: 28,
        value: 300000,
        title: 'Nakhon Ratchasima',
        key: 300000,
        label: 'Nakhon Ratchasima',
      },
      {
        id: 29,
        value: 600000,
        title: 'Nakhon Sawan',
        key: 600000,
        label: 'Nakhon Sawan',
      },
      {
        id: 30,
        value: 800000,
        title: 'Nakhon Si Thammarat',
        key: 800000,
        label: 'Nakhon Si Thammarat',
      },
      {
        id: 31,
        value: 550000,
        title: 'Nan',
        key: 550000,
        label: 'Nan',
      },
      {
        id: 32,
        value: 960000,
        title: 'Narathiwat',
        key: 960000,
        label: 'Narathiwat',
      },
      {
        id: 33,
        value: 390000,
        title: 'Nong Bua Lam Phu',
        key: 390000,
        label: 'Nong Bua Lam Phu',
      },
      {
        id: 34,
        value: 430000,
        title: 'Nong Khai',
        key: 430000,
        label: 'Nong Khai',
      },
      {
        id: 35,
        value: 120000,
        title: 'Nonthaburi',
        key: 120000,
        label: 'Nonthaburi',
      },
      {
        id: 36,
        value: 130000,
        title: 'Pathum Thani',
        key: 130000,
        label: 'Pathum Thani',
      },
      {
        id: 37,
        value: 940000,
        title: 'Pattani',
        key: 940000,
        label: 'Pattani',
      },
      {
        id: 38,
        value: 820000,
        title: 'Phangnga',
        key: 820000,
        label: 'Phangnga',
      },
      {
        id: 39,
        value: 930000,
        title: 'Phatthalung',
        key: 930000,
        label: 'Phatthalung',
      },
      {
        id: 40,
        value: 560000,
        title: 'Phayao',
        key: 560000,
        label: 'Phayao',
      },
      {
        id: 41,
        value: 670000,
        title: 'Phetchabun',
        key: 670000,
        label: 'Phetchabun',
      },
      {
        id: 42,
        value: 760000,
        title: 'Phetchaburi',
        key: 760000,
        label: 'Phetchaburi',
      },
      {
        id: 43,
        value: 660000,
        title: 'Phichit',
        key: 660000,
        label: 'Phichit',
      },
      {
        id: 44,
        value: 650000,
        title: 'Phitsanulok',
        key: 650000,
        label: 'Phitsanulok',
      },
      {
        id: 45,
        value: 540000,
        title: 'Phrae',
        key: 540000,
        label: 'Phrae',
      },
      {
        id: 46,
        value: 140000,
        title: 'Phra Nakhon Si Ayutthaya',
        key: 140000,
        label: 'Phra Nakhon Si Ayutthaya',
      },
      {
        id: 47,
        value: 830000,
        title: 'Phuket',
        key: 830000,
        label: 'Phuket',
      },
      {
        id: 48,
        value: 250000,
        title: 'Prachin Buri',
        key: 250000,
        label: 'Prachin Buri',
      },
      {
        id: 49,
        value: 770000,
        title: 'Prachuap Khiri Khan',
        key: 770000,
        label: 'Prachuap Khiri Khan',
      },
      {
        id: 50,
        value: 850000,
        title: 'Ranong',
        key: 850000,
        label: 'Ranong',
      },
      {
        id: 51,
        value: 700000,
        title: 'Ratchaburi',
        key: 700000,
        label: 'Ratchaburi',
      },
      {
        id: 52,
        value: 210000,
        title: 'Rayong',
        key: 210000,
        label: 'Rayong',
      },
      {
        id: 53,
        value: 450000,
        title: 'Roi Et',
        key: 450000,
        label: 'Roi Et',
      },
      {
        id: 54,
        value: 270000,
        title: 'Sa Kaeo',
        key: 270000,
        label: 'Sa Kaeo',
      },
      {
        id: 55,
        value: 470000,
        title: 'Sakon Nakhon',
        key: 470000,
        label: 'Sakon Nakhon',
      },
      {
        id: 56,
        value: 110000,
        title: 'Samut Prakan',
        key: 110000,
        label: 'Samut Prakan',
      },
      {
        id: 57,
        value: 740000,
        title: 'Samut Sakhon',
        key: 740000,
        label: 'Samut Sakhon',
      },
      {
        id: 58,
        value: 750000,
        title: 'Samut Songkhram',
        key: 750000,
        label: 'Samut Songkhram',
      },
      {
        id: 59,
        value: 190000,
        title: 'Saraburi',
        key: 190000,
        label: 'Saraburi',
      },
      {
        id: 60,
        value: 910000,
        title: 'Satun',
        key: 910000,
        label: 'Satun',
      },
      {
        id: 61,
        value: 170000,
        title: 'Sing Buri',
        key: 170000,
        label: 'Sing Buri',
      },
      {
        id: 62,
        value: 330000,
        title: 'Si Sa Ket',
        key: 330000,
        label: 'Si Sa Ket',
      },
      {
        id: 63,
        value: 900000,
        title: 'Songkhla',
        key: 900000,
        label: 'Songkhla',
      },
      {
        id: 64,
        value: 640000,
        title: 'Sukhothai',
        key: 640000,
        label: 'Sukhothai',
      },
      {
        id: 65,
        value: 720000,
        title: 'Suphan Buri',
        key: 720000,
        label: 'Suphan Buri',
      },
      {
        id: 66,
        value: 840000,
        title: 'Surat Thani',
        key: 840000,
        label: 'Surat Thani',
      },
      {
        id: 67,
        value: 320000,
        title: 'Surin',
        key: 320000,
        label: 'Surin',
      },
      {
        id: 68,
        value: 630000,
        title: 'Tak',
        key: 630000,
        label: 'Tak',
      },
      {
        id: 69,
        value: 920000,
        title: 'Trang',
        key: 920000,
        label: 'Trang',
      },
      {
        id: 70,
        value: 230000,
        title: 'Trat',
        key: 230000,
        label: 'Trat',
      },
      {
        id: 71,
        value: 340000,
        title: 'Ubon Ratchathani',
        key: 340000,
        label: 'Ubon Ratchathani',
      },
      {
        id: 72,
        value: 410000,
        title: 'Udon Thani',
        key: 410000,
        label: 'Udon Thani',
      },
      {
        id: 73,
        value: 610000,
        title: 'Uthai Thani',
        key: 610000,
        label: 'Uthai Thani',
      },
      {
        id: 74,
        value: 530000,
        title: 'Uttaradit',
        key: 530000,
        label: 'Uttaradit',
      },
      {
        id: 75,
        value: 950000,
        title: 'Yala',
        key: 950000,
        label: 'Yala',
      },
      {
        id: 76,
        value: 350000,
        title: 'Yasothon',
        key: 350000,
        label: 'Yasothon',
      },
    ],
  },
  dashCam: {
    title: 'leadDetailFields.dashCam',
    tooltip: '',
    type: 'radio',
    options: [
      {
        id: 1,
        value: 'true',
        title: 'genericOption.yes',
        key: 'true',
        label: 'genericOption.yes',
      },
      {
        id: 2,
        value: 'false',
        title: 'genericOption.no',
        key: 'false',
        label: 'genericOption.no',
      },
    ],
  },
  modification: {
    title: 'leadDetailFields.modification',
    tooltip: '',
    type: 'radio',
    options: [
      {
        key: 'yes0',
        label: 'text.yes',
        value: 'true',
      },
      {
        key: 'no1',
        label: 'text.no',
        value: 'false',
      },
    ],
  },
  drivingPurpose: {
    title: 'leadDetailFields.drivingPurpose',
    tooltip: '',
    type: 'radio',
    options: [
      {
        key: 'personal0',
        label: 'text.personal',
        value: 'PERSONAL',
      },
      {
        key: 'commercial1',
        label: 'text.commercial',
        value: 'COMMERCIAL',
      },
    ],
  },
  noOfDoors: {
    title: 'leadDetailFields.noOfDoor',
    tooltip: '',
    type: 'selectbox',
    options: [
      {
        key: '',
        label: 'Please Select',
      },
      {
        key: 4,
        label: 4,
        value: 4,
      },
    ],
  },
  engineSize: {
    title: 'leadDetailFields.engineSize',
    tooltip: '',
    type: 'selectbox',
    options: [
      {
        key: '',
        label: 'Please Select',
      },
      {
        key: 1500,
        label: 1500,
        value: 1500,
      },
    ],
  },
};

export const currentDataMock = {
  brand: 54,
  year: 2018,
  model: 632,
  carSubModelYear: 46922,
  province: 100000,
  noOfDoors: 4,
  engineSize: 1500,
  leadId: 'L9947889',
  insuranceType: 'Type 1, Type 2, qc.type2+, Type 3, qc.type3+',
  repairType: 'get from package result after search api',
  drivingPurpose: 'PERSONAL',
  dashCam: true,
  modification: true,
  redPlate: false,
  carLicensePlate: '1กท-0878',
  chassisNumber: '15AugRenewal1755243400319',
  vehicleIdNumber: '123',
  carColor: ['red'],
  currentInsurer: 7,
  insuranceKind: 'both',
  policyStartDate: '2025-08-15',
  compulsoryPolicyStartDate: '2025-08-15',
  customerFirstName: 'Automation',
  customerLastName: 'Renewal I',
  customerEmail: ['testing@rabbit.co.th'],
  customerPhoneNumber: [
    {
      phone: '+66710000878',
      status: 'unverified',
    },
  ],
  customerGender: 'm',
  customerDOB: '2000-02-01',
  customerLanguage: 'th-en',
  customerAge: 25,
  policyHolderDOB: '2000-02-01',
  policyHolderFirstName: 'Automation',
  policyHolderGender: 'm',
  policyHolderLastName: 'Renewal I',
  policyHolderNationalId: '1400000072878',
  policyTitle: 'MR',
  policyHolderAge: 25,
  numberOfFixedDriver: 0,
  policyHolderType: 'customer',
};
