import { PolicySearchResponse } from 'presentation/pages/car-insurance/orders/PrintingAndShipping/helper';

const mockPolicySearch: PolicySearchResponse = {
  total: 3,
  items: [
    {
      name: 'orders/e69bac0e-b7ca-4de9-b0e2-4719d6bbdc83',
      orderId: 'RF0001',
      policyId: 'RF0001-0',
      insuranceCategory: 'Car Insurance',
      productType: 'Type 1',
      insurer: 'Aioi Bangkok Insurance',
      customerPolicyholder: 'Pattawat Jaidee',
      phoneNumber: '0810896177',
      email: 'pattawatc@rabbit.co.th',
      licensePlate: 'nn-0001',
      totalPremium: 500000.78,
      paymentType: 'one-time-payment',
      paymentStatus: 'Pending',
      documentStatus: 'ITEM_DOCUMENT_STATUS_UNSPECIFIED',
      qcStatus: 'QC_SUBMISSION_STATUS_UNSPECIFIED',
      submissionStatus: 'SUBMISSION_STATUS_PRESUBMITTED',
      approvalStatus: 'APPROVAL_STATUS_UNSPECIFIED',
      printingAndShippingStatus: 'ITEM_PRINTING_AND_SHIPPING_STATUS_PENDING',
      policyStartDate: '02/08/2020 5:13:39 PM',
      createdOn: '02/08/2020 5:13:39 PM',
      updatedOn: '02/08/2020 5:13:39 PM',
    },
    {
      name: 'orders/e69bac0e-b7ca-4de9-b0e2-4719d6bbdc83',
      orderId: 'RF0001',
      policyId: 'RF0001-1',
      insuranceCategory: 'Car Insurance',
      productType: 'Type 1',
      insurer: 'Aioi Bangkok Insurance',
      customerPolicyholder: 'Pattawat Jaidee',
      phoneNumber: '0810896177',
      email: 'pattawatc@rabbit.co.th',
      licensePlate: 'nn-0001',
      totalPremium: 500000.78,
      paymentType: 'one-time-payment',
      paymentStatus: 'Pending',
      documentStatus: 'ITEM_DOCUMENT_STATUS_UNSPECIFIED',
      qcStatus: 'QC_SUBMISSION_STATUS_UNSPECIFIED',
      submissionStatus: 'SUBMISSION_STATUS_PRESUBMITTED',
      approvalStatus: 'APPROVAL_STATUS_UNSPECIFIED',
      printingAndShippingStatus:
        'ITEM_PRINTING_AND_SHIPPING_STATUS_UNSPECIFIED',
      policyStartDate: '02/08/2020 5:13:39 PM',
      createdOn: '02/08/2020 5:13:39 PM',
      updatedOn: '02/08/2020 5:13:39 PM',
    },
    {
      name: 'orders/test',
      orderId: 'RF0001',
      policyId: 'RF0003-1',
      insuranceCategory: 'Car Insurance',
      productType: 'Type 1',
      insurer: 'Aioi Bangkok Insurance',
      customerPolicyholder: 'Pattawat Jaidee',
      phoneNumber: '0810896177',
      email: 'pattawatc@rabbit.co.th',
      licensePlate: 'nn-0001',
      totalPremium: 500000.78,
      paymentType: 'one-time-payment',
      paymentStatus: 'Pending',
      documentStatus: 'ITEM_DOCUMENT_STATUS_UNSPECIFIED',
      qcStatus: 'QC_SUBMISSION_STATUS_UNSPECIFIED',
      submissionStatus: 'SUBMISSION_STATUS_PRESUBMITTED',
      approvalStatus: 'APPROVAL_STATUS_UNSPECIFIED',
      printingAndShippingStatus:
        'ITEM_PRINTING_AND_SHIPPING_STATUS_UNSPECIFIED',
      policyStartDate: '02/08/2020 5:13:39 PM',
      createdOn: '02/08/2020 5:13:39 PM',
      updatedOn: '02/08/2020 5:13:39 PM',
    },
  ],
};

export default mockPolicySearch;
