export const importRedbookTemplate = [
  'VehicleKey',
  'MakeCode',
  'MakeDescription',
  'MAKEDESCRIPTIONLL',
  'FamilyCode',
  'FamilyDescription',
  'FAMILYDESCRIPTIONLL',
  'VehicleTypeCode',
  'YearGroup',
  'MonthGroup',
  'ReleaseYear',
  'ReleaseMonth',
  'DiscontinuedYear',
  'DiscontinuedMonth',
  'SequenceNum',
  'Description',
  'DescriptionThai',
  'CurrentRelease',
  'ImportStatus',
  'LimitedEdition',
  'Series',
  'SeriesThai',
  'BadgeDescription',
  'BadgeDescriptionThai',
  'BadgeSecondaryDescription',
  'BadgeSecondaryDescriptionThai',
  'BodyStyleDescription',
  'BodyStyleDescriptionThai',
  'BodyConfigDescription',
  'BodyConfigDescriptionThai',
  'ExtraIdentification',
  'ExtraIdentificationThai',
  'DriveDescription',
  'DriveDescriptionThai',
  'GearTypeDescription',
  'GearTypeDescriptionThai',
  'EngineSize',
  'EngineDescription',
  'Cylinders',
  'SeatCapacity',
  'GearNum',
  'DoorNum',
  'KerbWeight',
  'AvgWholesale',
  'AvgRetail',
  'GoodWholesale',
  'GoodRetail',
  'NewPrice',
  'InsuranceCode',
  'FuelTypeDescription',
  'FuelTypeDescriptionThai',
  'Combined Power',
  'KMRangeElectricEng',
  'TopSpeedElectricEng',
  'BatteryWarrantyYears',
  'BatteryWarrantyKm',
];

export const importRedbookRequireColumn = ['VehicleKey'];

export const importRedbookTemplateWithType = [
  { name: 'VehicleKey', dataType: 'string' },
  { name: 'MakeCode', dataType: 'string' },
  { name: 'MakeDescription', dataType: 'string' },
  { name: 'MAKEDESCRIPTIONLL', dataType: 'string' },
  { name: 'FamilyCode', dataType: 'string|number' },
  { name: 'FamilyDescription', dataType: 'string|number' },
  { name: 'FAMILYDESCRIPTIONLL', dataType: 'string|number' },
  { name: 'VehicleTypeCode', dataType: 'string' },
  { name: 'YearGroup', dataType: 'number' },
  { name: 'MonthGroup', dataType: 'number' },
  { name: 'ReleaseYear', dataType: 'number' },
  { name: 'ReleaseMonth', dataType: 'number' },
  { name: 'DiscontinuedYear', dataType: 'number' },
  { name: 'DiscontinuedMonth', dataType: 'number' },
  { name: 'SequenceNum', dataType: 'number' },
  { name: 'Description', dataType: 'string' },
  { name: 'DescriptionThai', dataType: 'string' },
  { name: 'CurrentRelease', dataType: 'string' },
  { name: 'ImportStatus', dataType: 'string' },
  { name: 'LimitedEdition', dataType: 'string' },
  { name: 'Series', dataType: 'string|number' },
  { name: 'SeriesThai', dataType: 'string|number' },
  { name: 'BadgeDescription', dataType: 'string|number' },
  { name: 'BadgeDescriptionThai', dataType: 'string|number' },
  { name: 'BadgeSecondaryDescription', dataType: 'string|number' },
  { name: 'BadgeSecondaryDescriptionThai', dataType: 'string|number' },
  { name: 'BodyStyleDescription', dataType: 'string' },
  { name: 'BodyStyleDescriptionThai', dataType: 'string' },
  { name: 'BodyConfigDescription', dataType: 'string' },
  { name: 'BodyConfigDescriptionThai', dataType: 'string' },
  { name: 'ExtraIdentification', dataType: 'string' },
  { name: 'ExtraIdentificationThai', dataType: 'string' },
  { name: 'DriveDescription', dataType: 'string' },
  { name: 'DriveDescriptionThai', dataType: 'string' },
  { name: 'GearTypeDescription', dataType: 'string' },
  { name: 'GearTypeDescriptionThai', dataType: 'string' },
  { name: 'EngineSize', dataType: 'number' },
  { name: 'EngineDescription', dataType: 'number' },
  { name: 'Cylinders', dataType: 'number' },
  { name: 'SeatCapacity', dataType: 'number' },
  { name: 'GearNum', dataType: 'number' },
  { name: 'DoorNum', dataType: 'number' },
  { name: 'KerbWeight', dataType: 'number' },
  { name: 'AvgWholesale', dataType: 'number' },
  { name: 'AvgRetail', dataType: 'number' },
  { name: 'GoodWholesale', dataType: 'number' },
  { name: 'GoodRetail', dataType: 'number' },
  { name: 'NewPrice', dataType: 'number' },
  { name: 'InsuranceCode', dataType: 'string' },
  { name: 'FuelTypeDescription', dataType: 'string' },
  { name: 'FuelTypeDescriptionThai', dataType: 'string' },
  { name: 'Combined Power', dataType: 'number' },
  { name: 'KMRangeElectricEng', dataType: 'number' },
  { name: 'TopSpeedElectricEng', dataType: 'number' },
  { name: 'BatteryWarrantyYears', dataType: 'number' },
  { name: 'BatteryWarrantyKm', dataType: 'number' },
];
