import { Column } from 'presentation/components/modal/ImportModal/index.helper';

export const columns: Column[] = [
  {
    id: 'status',
    field: 'status',
    label: 'text.importStatus',
    minWidth: 100,
    sorting: 'none',
    disabled: true,
  },
  {
    id: 'createTime',
    field: 'createTime',
    label: 'text.importDate',
    minWidth: 100,
    sorting: 'desc',
  },
  {
    id: 'filename',
    field: 'filename',
    label: 'package.importFileName',
    minWidth: 100,
    sorting: 'none',
    noTooltip: false,
    disabled: true,
  },
  {
    id: 'createBy',
    field: 'createBy',
    label: 'text.importedBy',
    minWidth: 100,
    sorting: 'none',
    disabled: true,
  },
  {
    id: 'packageType',
    field: 'packageDetails.packageType',
    label: 'text.packageType',
    minWidth: 100,
    sorting: 'none',
    disabled: true,
  },
  {
    id: 'imported',
    field: 'imported',
    label: 'text.numberOfPackages',
    minWidth: 100,
    sorting: 'none',
    disabled: true,
  },
];

export const StatusImportedPackage = [
  { id: 1, title: 'importFileStatus.complete', value: 'COMPLETE' },
  { id: 2, title: 'importFileStatus.inProgress', value: 'IN_PROGRESS' },
  { id: 3, title: 'importFileStatus.error', value: 'ERROR' },
];

export const mandatoryPackageTemplate = [
  'name',
  'insurance_company_id',
  'oic_code',
  'personal_accident_coverage',
  'personal_accident_coverage_no',
  'medical_expenses_coverage',
  'medical_expenses_coverage_no',
  'liability_per_person_coverage',
  'liability_per_accident_coverage',
];

export const mandatoryPackageRequireColumn = [
  'name',
  'insurance_company_id',
  'oic_code',
  'personal_accident_coverage',
  'personal_accident_coverage_no',
  'medical_expenses_coverage',
  'medical_expenses_coverage_no',
  'liability_per_person_coverage',
  'liability_per_accident_coverage',
];

export const mandatoryPackageTemplateWithDatatype = [
  { name: 'name', dataType: 'string' },
  { name: 'insurance_company_id', dataType: 'number' },
  { name: 'oic_code', dataType: 'number' },
  { name: 'personal_accident_coverage', dataType: 'number' },
  { name: 'personal_accident_coverage_no', dataType: 'number' },
  { name: 'medical_expenses_coverage', dataType: 'number' },
  { name: 'medical_expenses_coverage_no', dataType: 'number' },
  { name: 'liability_per_person_coverage', dataType: 'number' },
  { name: 'liability_per_accident_coverage', dataType: 'number' },
];

export const mandatoryPackageMaximumUpload = 100;

export const renewalPackageTemplate = [
  'chassis_no',
  'insurer_id',
  'last_policy_expiration_date',
  'oic_code',
  'car_insurance_type',
  'car_repair_type',
  'liability_property_coverage',
  'liability_per_person_coverage',
  'liability_per_accident_coverage',
  'sum_coverage',
  'fire_theft_coverage',
  'flood_coverage',
  'personal_accident_coverage',
  'personal_accident_coverage_no',
  'medical_expenses_coverage_no',
  'medical_expenses_coverage',
  'bail_bond_coverage',
  'deductible_amount',
  'net_premium',
  'gross_premium',
  'insurer_accept',
];

export const renewalPackageRequireColumnAccepted = [
  'chassis_no',
  'insurer_id',
  'last_policy_expiration_date',
  'oic_code',
  'car_insurance_type',
  'car_repair_type',
  'liability_property_coverage',
  'liability_per_person_coverage',
  'liability_per_accident_coverage',
  'sum_coverage',
  'fire_theft_coverage',
  'flood_coverage',
  'personal_accident_coverage',
  'personal_accident_coverage_no',
  'medical_expenses_coverage_no',
  'medical_expenses_coverage',
  'bail_bond_coverage',
  'deductible_amount',
  'net_premium',
  'gross_premium',
  'insurer_accept',
];

export const renewalPackageRequireColumnNotAccepted = [
  'chassis_no',
  'insurer_id',
  'insurer_accept',
];

export const renewalPackageTemplateWithDatatype = [
  { name: 'chassis_no', dataType: 'string|number' },
  { name: 'insurer_id', dataType: 'number' },
  { name: 'last_policy_expiration_date', dataType: 'string' },
  { name: 'oic_code', dataType: 'number' },
  { name: 'car_insurance_type', dataType: 'insuranceType' },
  { name: 'car_repair_type', dataType: 'string' },
  { name: 'liability_property_coverage', dataType: 'number' },
  { name: 'liability_per_person_coverage', dataType: 'number' },
  { name: 'liability_per_accident_coverage', dataType: 'number' },
  { name: 'sum_coverage', dataType: 'number' },
  { name: 'fire_theft_coverage', dataType: 'number' },
  { name: 'flood_coverage', dataType: 'number' },
  { name: 'personal_accident_coverage', dataType: 'number' },
  { name: 'personal_accident_coverage_no', dataType: 'number' },
  { name: 'medical_expenses_coverage_no', dataType: 'number' },
  { name: 'medical_expenses_coverage', dataType: 'number' },
  { name: 'bail_bond_coverage', dataType: 'number' },
  { name: 'deductible_amount', dataType: 'number' },
  { name: 'net_premium', dataType: 'number' },
  { name: 'gross_premium', dataType: 'number' },
  { name: 'insurer_accept', dataType: 'zeroOneBool' },
];

export const insuranceMotorTemplate = [
  'package_id',
  'premium_id',
  'insurer_package_code',
  'package_label',
  'insurer',
  'package_description',
  'premium_description',
  'applicable_province',
  'package_start_date',
  'package_end_date',
  'gross_premium',
  'owned_car_damage',
  'insurance_type',
  'repair_type',
  'driving_purpose',
  'deductible_amount',
  'dash_cam',
  'vehicle_brand',
  'vehicle_model',
  'vehicle_submodel',
  'vehicle_registration_year',
  'fire_and_theft',
  'flood',
  'vehicle_oic_code',
  'third_party_death_per_person',
  'third_party_max_death',
  'third_party_property_damage',
  'personal_injury_per_person',
  'medical_expense_per_person',
  'bail_bond_per_time',
  'vehicle_transportation_compensation_per_time',
  'medical_compensation_per_day',
  'modification',
  'car_type',
  'personal_accident_coverage_number',
  'value_ratio',
  'redbook_id',
  'maximum_annual_coverage',
  'personal_accident_driver',
  'personal_accident_passenger',
  'terms_and_conditions_en',
  'terms_and_conditions_th',
  'operation',
  'province_ids',
];

export const insuranceMotorTemplateWithDatatype = [
  { name: 'package_id', dataType: 'string' },
  { name: 'premium_id', dataType: 'string' },
  { name: 'insurer_package_code', dataType: 'string|number' },
  { name: 'package_label', dataType: 'string' },
  { name: 'insurer', dataType: 'number' },
  { name: 'package_description', dataType: 'string' },
  { name: 'premium_description', dataType: 'string' },
  { name: 'applicable_province', dataType: 'string' },
  { name: 'package_start_date', dataType: 'string' },
  { name: 'package_end_date', dataType: 'string' },
  { name: 'gross_premium', dataType: 'number' },
  { name: 'owned_car_damage', dataType: 'number' },
  { name: 'insurance_type', dataType: 'string' },
  { name: 'repair_type', dataType: 'string' },
  { name: 'driving_purpose', dataType: 'string' },
  { name: 'deductible_amount', dataType: 'number' },
  { name: 'dash_cam', dataType: 'bool' },
  { name: 'vehicle_brand', dataType: 'string|number' },
  { name: 'vehicle_model', dataType: 'string|number' },
  { name: 'vehicle_submodel', dataType: 'string|number' },
  { name: 'vehicle_registration_year', dataType: 'number' },
  { name: 'fire_and_theft', dataType: 'number' },
  { name: 'flood', dataType: 'number' },
  { name: 'vehicle_oic_code', dataType: 'string|number' },
  { name: 'third_party_death_per_person', dataType: 'number' },
  { name: 'third_party_max_death', dataType: 'number' },
  { name: 'third_party_property_damage', dataType: 'number' },
  { name: 'personal_injury_per_person', dataType: 'number' },
  { name: 'medical_expense_per_person', dataType: 'number' },
  { name: 'bail_bond_per_time', dataType: 'number' },
  { name: 'vehicle_transportation_compensation_per_time', dataType: 'number' },
  { name: 'medical_compensation_per_day', dataType: 'number' },
  { name: 'modification', dataType: 'bool' },
  { name: 'car_type', dataType: 'string' },
  { name: 'personal_accident_coverage_number', dataType: 'number' },
  { name: 'value_ratio', dataType: 'number' },
  { name: 'redbook_id', dataType: 'string' },
  { name: 'maximum_annual_coverage', dataType: 'number' },
  { name: 'personal_accident_driver', dataType: 'number' },
  { name: 'personal_accident_passenger', dataType: 'number' },
  { name: 'terms_and_conditions_en', dataType: 'string' },
  { name: 'terms_and_conditions_th', dataType: 'string' },
  { name: 'operation', dataType: 'importOperation' },
  // province_ids accepts "0" for nationwide or comma-separated 6-digit province codes.
  { name: 'province_ids', dataType: 'provinceIds' },
];

export const insuranceMotorRequireColumn = [
  'package_id',
  'premium_id',
  'insurer_package_code',
  'package_label',
  'insurer',
  'package_description',
  'premium_description',
  'applicable_province',
  'package_start_date',
  'package_end_date',
  'gross_premium',
  'owned_car_damage',
  'insurance_type',
  'repair_type',
  'driving_purpose',
  'deductible_amount',
  'dash_cam',
  'vehicle_brand',
  'vehicle_model',
  'vehicle_submodel',
  'vehicle_registration_year',
  'fire_and_theft',
  'flood',
  'vehicle_oic_code',
  'third_party_death_per_person',
  'third_party_max_death',
  'third_party_property_damage',
  'personal_injury_per_person',
  'medical_expense_per_person',
  'bail_bond_per_time',
  'vehicle_transportation_compensation_per_time',
  'medical_compensation_per_day',
  'personal_accident_coverage_number',
  'value_ratio',
  'redbook_id',
  'maximum_annual_coverage',
  'personal_accident_driver',
  'personal_accident_passenger',
  'province_ids',
];
