import { IFormikControllerProps } from 'interfaces/FormikFieldsInterface';

export const fields: IFormikControllerProps[] = [
  {
    name: 'typeOfVehicle',
    title: 'text.typeOfVehicle',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-type-of-vehicle',
  },
  {
    name: 'carName',
    title: 'text.carName',
    fieldType: 'textContent',
    display: true,
    dataTestId: 'vehicle-car-name',
  },
  {
    name: 'province',
    title: 'package.provinceSearchLabel',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-province',
  },
  {
    name: 'redPlate',
    title: 'leadDetailFields.redPlate',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-red-plate',
  },
  {
    name: 'modelYear',
    title: 'text.modelYear',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-model-year',
  },
  {
    name: 'chassisNumber',
    title: 'text.chassisNumber',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-chassis-number',
  },
  {
    name: 'engineNumber',
    title: 'leadDetailFields.engineNumber',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-engine-number',
  },
  {
    name: 'vehicleColor',
    title: 'leadDetailFields.vehicleColor',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-color',
  },
  {
    name: 'drivingPurpose',
    title: 'leadDetailFields.drivingPurpose',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-driving-purpose',
  },
  {
    name: 'dashCam',
    title: 'leadDetailFields.dashCam',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-dash-cam',
  },
  {
    name: 'carModified',
    title: 'text.customVehicle',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-car-modified',
  },
  {
    name: 'firstDriverName',
    title: 'leadDetailFields.firstDriverName',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-first-driver-name',
  },
  {
    name: 'firstDriverDOB',
    title: 'leadDetailFields.firstDriverDOB',
    fieldType: 'datefield',
    display: true,
    dataTestId: 'vehicle-first-driver-dob',
  },
  {
    name: 'secondDriverName',
    title: 'leadDetailFields.secondDriverName',
    fieldType: 'text',
    display: true,
    dataTestId: 'vehicle-second-driver-name',
  },
  {
    name: 'secondDriverDOB',
    title: 'leadDetailFields.secondDriverDOB',
    fieldType: 'datefield',
    display: true,
    dataTestId: 'vehicle-second-driver-dob',
  },
  {
    name: 'engineSize',
    title: 'leadDetailFields.engineSize',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-engine-size',
  },
  {
    name: 'noOfDoor',
    title: 'leadDetailFields.noOfDoor',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-no-of-door',
  },
  {
    name: 'noOfSeat',
    title: 'leadDetailFields.noOfSeat',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-no-of-seat',
  },
];

export const readOnlyFields: IFormikControllerProps[] = [
  {
    name: 'typeOfVehicle',
    title: 'text.typeOfVehicle',
    fieldType: 'text',
    isReadOnly: true,
    display: true,
    dataTestId: 'vehicle-type-of-vehicle',
  },
  {
    name: 'carName',
    title: 'text.carName',
    fieldType: 'textContent',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-car-name',
  },
  {
    name: 'province',
    title: 'package.provinceSearchLabel',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-province',
  },
  {
    name: 'redPlate',
    title: 'leadDetailFields.redPlate',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-red-plate',
  },
  {
    name: 'modelYear',
    title: 'text.modelYear',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-model-year',
  },
  {
    name: 'chassisNumber',
    title: 'text.chassisNumber',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-chassis-number',
  },
  {
    name: 'engineNumber',
    title: 'leadDetailFields.engineNumber',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-engine-number',
  },
  {
    name: 'vehicleColor',
    title: 'leadDetailFields.vehicleColor',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-color',
  },
  {
    name: 'drivingPurpose',
    title: 'leadDetailFields.drivingPurpose',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-driving-purpose',
  },
  {
    name: 'dashCam',
    title: 'leadDetailFields.dashCam',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-dash-cam',
  },
  {
    name: 'carModified',
    title: 'text.customVehicle',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-car-modified',
  },
  {
    name: 'firstDriverName',
    title: 'leadDetailFields.firstDriverName',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-first-driver-name',
  },
  {
    name: 'firstDriverDOB',
    title: 'leadDetailFields.firstDriverDOB',
    fieldType: 'datefield',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-first-driver-dob',
  },
  {
    name: 'firstDriverIdNumber',
    title: 'qc.firstDriverIdNumber',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-first-driver-id-number',
  },
  {
    name: 'firstDriverDrivingLicense',
    title: 'qc.firstDriverLicense',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-first-driver-driving-license',
  },
  {
    name: 'secondDriverName',
    title: 'leadDetailFields.secondDriverName',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-second-driver-name',
  },
  {
    name: 'secondDriverDOB',
    title: 'leadDetailFields.secondDriverDOB',
    fieldType: 'datefield',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-second-driver-dob',
  },
  {
    name: 'secondDriverIdNumber',
    title: 'qc.secondDriverIdNumber',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-second-driver-id-number',
  },
  {
    name: 'secondDriverDrivingLicense',
    title: 'qc.secondDriverLicense',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-second-driver-driving-license',
  },
  {
    name: 'engineSize',
    title: 'leadDetailFields.engineSize',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-engine-size',
  },
  {
    name: 'noOfDoor',
    title: 'leadDetailFields.noOfDoor',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-no-of-door',
  },
  {
    name: 'noOfSeat',
    title: 'leadDetailFields.noOfSeat',
    fieldType: 'text',
    display: true,
    isReadOnly: true,
    dataTestId: 'vehicle-no-of-seat',
  },
];
