import TextField from 'presentation/components/common/FormikFields/DetailViewTextField/DetailViewTextField';
import { vehicleColorOptions } from 'presentation/components/VehiclePolicySection/helper';
import { getString } from 'presentation/theme/localization';

import { CAR_ROWS, CarRowProps } from './interface';
import CarLicenseField from './LicensePlate';
import RadioGroupField from './RadioGroup';

import Autocomplete from '../../common/FormikFields/LeadAutocomplete';

const carColumns: CarRowProps = {
  [CAR_ROWS.CAR_YEAR]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.CAR_YEAR,
      title: getString('leadDetailFields.year'),
      value: '',
      dataTestId: 'car-year-autocomplete',
      error: null,
      isReadOnly: false,
      options: [],
      multiple: false,
      placeholder: getString('text.pleaseSelect'),
      showAsterisk: true,
      disableClearable: true,
      isDisabled: false,
    },
    type: 'autocomplete',
  },
  [CAR_ROWS.CAR_BRAND]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.CAR_BRAND,
      title: getString('leadDetailFields.brand'),
      value: '',
      dataTestId: 'car-brand-autocomplete',
      error: null,
      isReadOnly: false,
      options: [],
      multiple: false,
      placeholder: getString('text.pleaseSelect'),
      showAsterisk: true,
      disableClearable: true,
      isDisabled: false,
    },
    type: 'autocomplete',
  },
  [CAR_ROWS.CAR_MODEL]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.CAR_MODEL,
      title: getString('leadDetailFields.model'),
      value: '',
      dataTestId: 'car-model-autocomplete',
      error: null,
      isReadOnly: false,
      options: [],
      multiple: false,
      placeholder: getString('text.pleaseSelect'),
      showAsterisk: true,
      disableClearable: true,
      isDisabled: false,
    },
    type: 'autocomplete',
  },
  [CAR_ROWS.SUB_MODEL]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.SUB_MODEL,
      title: getString('leadDetailFields.submodel'),
      value: '',
      dataTestId: 'car-sub-model-autocomplete',
      error: null,
      isReadOnly: false,
      options: [],
      multiple: false,
      placeholder: getString('text.pleaseSelect'),
      showAsterisk: true,
      disableClearable: true,
      isDisabled: false,
    },
    type: 'autocomplete',
  },
  [CAR_ROWS.FUEL_TYPE]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.FUEL_TYPE,
      title: getString('leadDetailFields.fuelType'),
      value: '',
      dataTestId: 'fuel-type-autocomplete',
      error: null,
      isReadOnly: true,
      options: [],
      multiple: false,
      placeholder: getString('text.pleaseSelect'),
      showAsterisk: false,
      disableClearable: true,
      isDisabled: true,
    },
    type: 'autocomplete',
  },
  [CAR_ROWS.TRANSMISSION_GEAR]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.TRANSMISSION_GEAR,
      title: getString('leadDetailFields.transmission'),
      value: '',
      dataTestId: 'transmission-autocomplete',
      error: null,
      isReadOnly: true,
      multiple: false,
      placeholder: getString('text.pleaseSelect'),
      showAsterisk: false,
      disableClearable: true,
      isDisabled: true,
    },
    type: 'autocomplete',
  },
  [CAR_ROWS.ENGINE_SIZE]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.ENGINE_SIZE,
      title: getString('leadDetailFields.engineSize'),
      value: '',
      dataTestId: 'engine-size-autocomplete',
      error: null,
      isReadOnly: true,
      multiple: false,
      placeholder: getString('text.pleaseSelect'),
      showAsterisk: true,
      disableClearable: true,
      isDisabled: true,
    },
    type: 'autocomplete',
  },
  [CAR_ROWS.NUMBER_DOORS]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.NUMBER_DOORS,
      title: getString('leadDetailFields.noOfDoor'),
      value: '',
      dataTestId: 'number-doors-autocomplete',
      error: null,
      isReadOnly: true,
      multiple: false,
      placeholder: getString('text.pleaseSelect'),
      showAsterisk: true,
      disableClearable: true,
      isDisabled: true,
    },
    type: 'autocomplete',
  },
  [CAR_ROWS.CAB_TYPE]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.CAB_TYPE,
      title: getString('leadDetailFields.cabType'),
      value: '',
      dataTestId: 'cab-type-autocomplete',
      error: null,
      isReadOnly: true,
      multiple: false,
      placeholder: getString('text.pleaseSelect'),
      showAsterisk: false,
      disableClearable: true,
      isDisabled: true,
    },
    type: 'autocomplete',
  },
  [CAR_ROWS.MODIFICATION]: {
    InputComponent: RadioGroupField,
    inputProps: {
      name: CAR_ROWS.MODIFICATION,
      title: getString('leadDetailFields.modification'),
      dataTestId: 'modification-radio-group',
      options: [
        {
          id: 0,
          val: true,
          title: 'Yes',
        },
        {
          id: 1,
          val: false,
          title: 'No',
        },
      ],
      row: true,
      showLabel: true,
      isReadOnly: false,
      error: false,
      value: '',
      isDisabled: true,
      showAsterisk: true,
    },
    type: 'radio',
  },
  [CAR_ROWS.DASHCAM]: {
    InputComponent: RadioGroupField,
    inputProps: {
      name: CAR_ROWS.DASHCAM,
      title: getString('leadDetailFields.dashCam'),
      dataTestId: 'dashcam-radio-group',
      options: [
        {
          id: 0,
          val: true,
          title: 'Yes',
        },
        {
          id: 1,
          val: false,
          title: 'No',
        },
      ],
      row: true,
      showLabel: true,
      isReadOnly: false,
      error: false,
      value: '',
      isDisabled: true,
      showAsterisk: true,
    },
    type: 'radio',
  },
  [CAR_ROWS.DRIVING_PURPOSE]: {
    InputComponent: RadioGroupField,
    inputProps: {
      name: CAR_ROWS.DRIVING_PURPOSE,
      title: getString('leadDetailFields.drivingPurpose'),
      dataTestId: 'driving-purpose-radio-group',
      options: [
        {
          id: 0,
          val: 'personal',
          title: 'Personal',
        },
        {
          id: 1,
          val: 'commercial',
          title: 'Commercial',
        },
      ],
      row: true,
      showLabel: true,
      isReadOnly: false,
      error: false,
      value: '',
      isDisabled: true,
      showAsterisk: true,
    },
    type: 'radio',
  },
  [CAR_ROWS.NUMBER_REGISTERED_SEATS]: {
    InputComponent: RadioGroupField,
    inputProps: {
      name: CAR_ROWS.NUMBER_REGISTERED_SEATS,
      title: getString('leadDetailFields.registeredSeats'),
      dataTestId: 'registered-seats-radio-group',
      options: [],
      row: false,
      showLabel: true,
      isReadOnly: false,
      error: false,
      value: '-',
      isDisabled: true,
      showAsterisk: false,
    },
    type: 'radio',
  },
  [CAR_ROWS.PROVINCE]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.PROVINCE,
      title: getString('leadDetailFields.province'),
      value: '',
      dataTestId: 'province-autocomplete',
      error: null,
      isReadOnly: false,
      options: [],
      multiple: false,
      placeholder: getString('text.pleaseSelect'),
      showAsterisk: true,
      disableClearable: true,
      isDisabled: true,
    },
    type: 'autocomplete',
  },
  [CAR_ROWS.RED_PLATE]: {
    InputComponent: RadioGroupField,
    inputProps: {
      name: CAR_ROWS.RED_PLATE,
      title: getString('leadDetailFields.redPlate'),
      dataTestId: 'red-plate-radio-group',
      options: [
        {
          id: 0,
          val: true,
          title: 'Yes',
        },
        {
          id: 1,
          val: false,
          title: 'No',
        },
      ],
      row: true,
      showLabel: true,
      isReadOnly: false,
      error: false,
      value: undefined,
      isDisabled: true,
      showAsterisk: true,
    },
    type: 'radio',
  },
  [CAR_ROWS.LICENSE_PLATE]: {
    InputComponent: CarLicenseField,
    inputProps: {
      name: CAR_ROWS.LICENSE_PLATE,
      title: getString('leadDetailFields.licensePlate'),
      dataTestId: 'license-plate-input',
      error: false,
      value: undefined,
      isReadOnly: false,
      isDisabled: true,
      showAsterisk: true,
    },
    type: 'licensePlate',
  },
  [CAR_ROWS.CHASSIS_NUMBER]: {
    InputComponent: TextField,
    inputProps: {
      name: CAR_ROWS.CHASSIS_NUMBER,
      title: getString('leadDetailFields.chassisNumber'),
      dataTestId: 'chassis-number-input',
      error: false,
      value: '',
      placeholder: getString('text.typeHere'),
      isReadOnly: false,
      isDisabled: true,
      showAsterisk: true,
      textFieldError: false,
    },
    type: 'text',
  },
  [CAR_ROWS.VEHICLE_ID_NUMBER]: {
    InputComponent: TextField,
    inputProps: {
      name: CAR_ROWS.VEHICLE_ID_NUMBER,
      title: getString('leadDetailFields.vehicleIdNumber'),
      dataTestId: 'vehicle-id-number-input',
      error: false,
      value: '',
      placeholder: getString('text.typeHere'),
      isReadOnly: false,
      isDisabled: true,
      showAsterisk: true,
      textFieldError: false,
    },
    type: 'text',
  },
  [CAR_ROWS.VEHICLE_COLOR]: {
    InputComponent: Autocomplete,
    inputProps: {
      name: CAR_ROWS.VEHICLE_COLOR,
      title: getString('leadDetailFields.vehicleColor'),
      value: '',
      dataTestId: 'vehicle-color-autocomplete',
      error: null,
      isReadOnly: false,
      options: vehicleColorOptions,
      multiple: true,
      disableCloseOnSelect: true,
      showAsterisk: true,
      disableClearable: true,
      isDisabled: true,
      textFieldError: false,
    },
    type: 'autocomplete',
  },
};

export default carColumns;
